import {
  Category,
  Brand,
  Seller,
  Coupon,
  UserProfile,
  Order,
  Review,
  ProductQuestion,
  NotificationItem,
  SupportTicket,
  AuditLogEntry,
  HomepageConfig,
  OrderTimelineEvent,
  OrderStatus,
} from './types';

export const INITIAL_HOMEPAGE_CONFIG: HomepageConfig = {
  heroBadgeAr: 'تشكيلة الموسم الفاخرة ٢٠٢٦ • إصدارات حصرية للمملكة',
  heroBadgeEn: 'AUTUMN / WINTER 2026 CURATION • SAUDI EXCLUSIVE EDITIONS',
  heroTitleAr: 'فخامة الأصالة السعودية تلتقي بأرقى المقتنيات العالمية',
  heroTitleEn: 'Where Saudi Heritage Meets World-Class Luxury & Craft',
  heroSubtitleAr:
    'تسوق من نخبة المتاجر والوكلاء المعتمدين في المملكة. ساعات فاخرة، عطور ملكية، أحدث التقنيات، وأزياء راقية مع ضمان الأصالة ١٠٠٪ وتوصيل VIP لباب منزلك.',
  heroSubtitleEn:
    'Discover curated collections from verified Saudi boutiques and authorized dealers. Fine horology, royal oud, flagship technology, and couture fashion.',
  heroCtaAr: 'استكشف التشكيلة الفاخرة',
  heroCtaEn: 'Explore Curated Collection',
  heroSecondaryBannerTitleAr: 'نوادر الدهن والعود الملكي المعتّق',
  heroSecondaryBannerTitleEn: 'Rare Aged Royal Oud & Artisanal Perfumery',
  seasonalBannerTitleAr: 'موسم الفخامة والضيافة السعودية',
  seasonalBannerTitleEn: 'Saudi Season of Luxury & Fine Hospitality',
  seasonalBannerSubtitleAr:
    'خصومات حصرية تصل إلى ٣٠٪ على مكائن القهوة المختصة، أطقم الضيافة المذهّبة، والبخور الملكي مع شحن مجاني سريع لجميع مدن المملكة.',
  seasonalBannerSubtitleEn:
    'Exclusive privileges up to 30% off specialty espresso machines, gilded hospitality sets, and royal incense with complimentary express delivery across KSA.',
  flashDealsActive: true,
  freeShippingThreshold: 350,
};

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'watches',
    nameAr: 'الساعات والإكسسوارات',
    nameEn: 'Watches & Fine Accessories',
    descriptionAr: 'ساعات سويسرية وأوتوماتيكية فاخرة، كبكات ملكية، ونظارات شمسية أصلية',
    descriptionEn: 'Swiss automatic timepieces, royal cufflinks, and luxury eyewear',
    iconName: 'Watch',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=85',
    featuredBannerAr: 'ضمان دولي معتمد وشهادة أصالة مع كل ساعة',
    featuredBannerEn: 'Certified international warranty & authenticity card with every timepiece',
    subcategories: [
      { id: 'watches-swiss', nameAr: 'ساعات سويسرية فاخرة', nameEn: 'Swiss Luxury Watches' },
      { id: 'watches-chrono', nameAr: 'ساعات كرونوغراف رجالية', nameEn: 'Men Chronograph Watches' },
      { id: 'watches-ladies', nameAr: 'ساعات نسائية مرصعة', nameEn: 'Women Diamond Watches' },
      { id: 'watches-cufflinks', nameAr: 'كبكات وأقلام فاخرة', nameEn: 'Luxury Cufflinks & Pens' },
      { id: 'watches-sunglasses', nameAr: 'نظارات شمسية أصلية', nameEn: 'Designer Sunglasses' },
    ],
  },
  {
    id: 'perfumes',
    nameAr: 'العطور والبخور الملكي',
    nameEn: 'Perfumes & Royal Oud',
    descriptionAr: 'دهن عود معتّق، بخور ملكي، وعطور نيش عالمية وسعودية فاخرة',
    descriptionEn: 'Aged royal oud oil, rare bakhoor incense, and niche fragrances',
    iconName: 'Sparkles',
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&q=85',
    featuredBannerAr: 'تركيبات عطرية نادرة من أندى غابات العود الطبيعي',
    featuredBannerEn: 'Rare olfactory compositions crafted from wild natural agarwood',
    subcategories: [
      { id: 'perfumes-oud', nameAr: 'دهن العود والخشب الطبيعي', nameEn: 'Pure Oud Oil & Agarwood' },
      { id: 'perfumes-niche', nameAr: 'عطور النيش الفاخرة', nameEn: 'Luxury Niche Perfumes' },
      { id: 'perfumes-bakhoor', nameAr: 'المبثوث والمعمول الملكي', nameEn: 'Royal Bakhoor & Incense' },
      { id: 'perfumes-sets', nameAr: 'صناديق الإهداء الملكية', nameEn: 'VIP Gift Boxes' },
    ],
  },
  {
    id: 'smartphones',
    nameAr: 'الجوالات والأجهزة الذكية',
    nameEn: 'Smartphones & Wearables',
    descriptionAr: 'أحدث الهواتف الرائدة، الساعات الذكية، والإكسسوارات المعتمدة بضمان الوكيل',
    descriptionEn: 'Flagship smartphones, smartwatches, and certified accessories',
    iconName: 'Smartphone',
    image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=85',
    featuredBannerAr: 'ضمان الوكيل الرسمي في المملكة لمدة ٢٤ شهراً',
    featuredBannerEn: '24-month official KSA authorized distributor warranty',
    subcategories: [
      { id: 'smartphones-flagship', nameAr: 'هواتف الفئة الرائدة', nameEn: 'Flagship Smartphones' },
      { id: 'smartphones-fold', nameAr: 'الهواتف القابلة للطي', nameEn: 'Foldable Phones' },
      { id: 'smartphones-watches', nameAr: 'الساعات الذكية المتقدمة', nameEn: 'Advanced Smartwatches' },
      { id: 'smartphones-acc', nameAr: 'شواحن وإكسسوارات MagSafe', nameEn: 'MagSafe & Fast Chargers' },
    ],
  },
  {
    id: 'electronics',
    nameAr: 'الإلكترونيات والصوتيات',
    nameEn: 'Electronics & High-End Audio',
    descriptionAr: 'سماعات عازلة للضجيج، شاشات سينمائية OLED، وكاميرات احترافية',
    descriptionEn: 'Noise-canceling headphones, OLED home cinema, and pro cameras',
    iconName: 'Headphones',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=85',
    subcategories: [
      { id: 'elec-audio', nameAr: 'سماعات وأنظمة صوتية', nameEn: 'Headphones & Hi-Fi Audio' },
      { id: 'elec-tv', nameAr: 'شاشات التلفاز الذكية OLED', nameEn: 'OLED Smart TVs' },
      { id: 'elec-cameras', nameAr: 'كاميرات التصوير الاحترافية', nameEn: 'Professional Cameras' },
      { id: 'elec-smart', nameAr: 'أنظمة المنزل الذكي', nameEn: 'Smart Home Systems' },
    ],
  },
  {
    id: 'computers',
    nameAr: 'أجهزة الكمبيوتر واللابتوب',
    nameEn: 'Computers & Workstations',
    descriptionAr: 'حواسيب محمولة للأعمال والتصميم، شاشات فائقة الدقة، وملحقات مكتبية',
    descriptionEn: 'Executive laptops, studio monitors, and workstation accessories',
    iconName: 'Laptop',
    image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=85',
    subcategories: [
      { id: 'comp-macbook', nameAr: 'أجهزة لابتوب للأعمال والمبدعين', nameEn: 'Pro Creator Laptops' },
      { id: 'comp-tablets', nameAr: 'الأجهزة اللوحية الاحترافية', nameEn: 'Pro Tablets & Stylus' },
      { id: 'comp-monitors', nameAr: 'شاشات 4K و 5K الاحترافية', nameEn: '4K & 5K Studio Monitors' },
      { id: 'comp-peripherals', nameAr: 'لوحات المفاتيح والملحقات', nameEn: 'Mechanical Keyboards & Mice' },
    ],
  },
  {
    id: 'home-kitchen',
    nameAr: 'المنزل والمطبخ والقهوة',
    nameEn: 'Home, Kitchen & Espresso',
    descriptionAr: 'مكائن إسبريسو إيطالية، أطقم ضيافة سعودية مذهّبة، وأجهزة منزلية ذكية',
    descriptionEn: 'Italian espresso machines, gilded Saudi hospitality sets, and appliances',
    iconName: 'Coffee',
    image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=85',
    subcategories: [
      { id: 'home-coffee', nameAr: 'مكائن القهوة المختصة والإسبريسو', nameEn: 'Specialty Espresso Machines' },
      { id: 'home-hospitality', nameAr: 'دلال وأطقم الضيافة السعودية', nameEn: 'Saudi Dallah & Hospitality Sets' },
      { id: 'home-appliances', nameAr: 'أجهزة تنقية الهواء والعناية بالمنزل', nameEn: 'Air Purifiers & Vacuums' },
      { id: 'home-decor', nameAr: 'مباخر وديكورات رخامية', nameEn: 'Marble Mabkhara & Decor' },
    ],
  },
  {
    id: 'mens-fashion',
    nameAr: 'الأزياء الرجالية الفاخرة',
    nameEn: "Men's Luxury Fashion",
    descriptionAr: 'بشوت ملكية، أشمغة سويسرية وإنجليزية، أحذية جلدية إيطالية، وملابس رسمية',
    descriptionEn: 'Royal Bishts, Swiss/English Shemaghs, and Italian leather footwear',
    iconName: 'Shirt',
    image: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=800&q=85',
    subcategories: [
      { id: 'mens-shemagh', nameAr: 'الأشمغة والغتر الفاخرة', nameEn: 'Luxury Shemaghs & Ghutras' },
      { id: 'mens-bisht', nameAr: 'البشوت الملكية الحساوية', nameEn: 'Royal Hasawi Bishts' },
      { id: 'mens-shoes', nameAr: 'الأحذية الجلدية الإيطالية', nameEn: 'Italian Leather Shoes' },
      { id: 'mens-leather', nameAr: 'المحافظ والحقائب الجلدية', nameEn: 'Leather Wallets & Briefcases' },
    ],
  },
  {
    id: 'womens-fashion',
    nameAr: 'الأزياء النسائية والعبايات',
    nameEn: "Women's Couture & Abayas",
    descriptionAr: 'عبايات كوتور بحرير طبيعي، حقائب جلدية فاخرة، ومجوهرات عصرية',
    descriptionEn: 'Natural silk couture abayas, designer leather handbags, and fine jewelry',
    iconName: 'ShoppingBag',
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=85',
    subcategories: [
      { id: 'womens-abayas', nameAr: 'عبايات الكوتور والحرير', nameEn: 'Couture & Silk Abayas' },
      { id: 'womens-bags', nameAr: 'الحقائب الجلدية الفاخرة', nameEn: 'Luxury Leather Handbags' },
      { id: 'womens-jewelry', nameAr: 'المجوهرات والحلي الذهبية', nameEn: 'Fine Jewelry & Gold' },
      { id: 'womens-scarves', nameAr: 'الطرح والشالات الحريرية', nameEn: 'Silk Scarves & Shawls' },
    ],
  },
  {
    id: 'beauty',
    nameAr: 'الجمال والعناية الشخصية',
    nameEn: 'Beauty & Luxury Skincare',
    descriptionAr: 'أجهزة تصفيف الشعر المتطورة، سيرومات العناية بالبشرة، ومستحضرات التجميل الفاخرة',
    descriptionEn: 'Advanced hair styling tools, clinical skincare serums, and luxury cosmetics',
    iconName: 'HeartHandshake',
    image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=85',
    subcategories: [
      { id: 'beauty-hair', nameAr: 'أجهزة تصفيف الشعر الاحترافية', nameEn: 'Pro Hair Styling Devices' },
      { id: 'beauty-skin', nameAr: 'مجموعات العناية الفائقة بالبشرة', nameEn: 'Luxury Skincare Sets' },
      { id: 'beauty-makeup', nameAr: 'مستحضرات التجميل الفاخرة', nameEn: 'Prestige Makeup' },
    ],
  },
  {
    id: 'kids',
    nameAr: 'الأطفال ومستلزمات المواليد',
    nameEn: 'Kids & Baby Luxury',
    descriptionAr: 'عربات أطفال فاخرة، مقاعد سيارات آمنة، وألعاب تعليمية ذكية',
    descriptionEn: 'First-class baby strollers, ISOFIX car seats, and STEM educational toys',
    iconName: 'Baby',
    image: 'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=800&q=85',
    subcategories: [
      { id: 'kids-strollers', nameAr: 'عربات الأطفال ومقاعد السيارات', nameEn: 'Strollers & Car Seats' },
      { id: 'kids-toys', nameAr: 'الألعاب التعليمية والتركيب', nameEn: 'STEM & Building Sets' },
      { id: 'kids-nursery', nameAr: 'أجهزة مراقبة وغرف المواليد', nameEn: 'Baby Monitors & Nursery' },
    ],
  },
  {
    id: 'supermarket',
    nameAr: 'الذواقة والسوبرماركت الفاخر',
    nameEn: 'Gourmet & Fine Pantry',
    descriptionAr: 'تمور القصيم الملكية، عسل السدر الجبلي، الزعفران الفاخر، والبن المختص',
    descriptionEn: 'Royal Qassim dates, mountain Sidr honey, pure saffron, and specialty coffee beans',
    iconName: 'UtensilsCrossed',
    image: 'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=800&q=85',
    subcategories: [
      { id: 'super-dates', nameAr: 'التمور الملكية وصناديق الضيافة', nameEn: 'Royal Dates & Gift Boxes' },
      { id: 'super-honey', nameAr: 'العسل الطبيعي والزعفران الفاخر', nameEn: 'Pure Honey & Saffron' },
      { id: 'super-coffee', nameAr: 'محاصيل القهوة المختصة والهيل', nameEn: 'Specialty Coffee & Cardamom' },
    ],
  },
  {
    id: 'sports',
    nameAr: 'الرياضة واللياقة البدنية',
    nameEn: 'Sports & Smart Fitness',
    descriptionAr: 'أجهزة تمارين منزلية ذكية، مضارب بادل احترافية، ومعدات استشفاء عضلي',
    descriptionEn: 'Smart home gym equipment, pro Carbon Padel rackets, and recovery gear',
    iconName: 'Dumbbell',
    image: 'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=800&q=85',
    subcategories: [
      { id: 'sports-padel', nameAr: 'مضارب ومعدات البادل الاحترافية', nameEn: 'Pro Padel Rackets & Gear' },
      { id: 'sports-gym', nameAr: 'أجهزة اللياقة المنزلية الذكية', nameEn: 'Smart Home Gym Equipment' },
      { id: 'sports-recovery', nameAr: 'أجهزة المساج والاستشفاء العضلي', nameEn: 'Percussion Recovery Devices' },
    ],
  },
  {
    id: 'automotive',
    nameAr: 'السيارات والرحلات البرية',
    nameEn: 'Automotive & Desert Glamping',
    descriptionAr: 'ثلاجات رحلات للسيارات، محطات طاقة محمولة للكشتات، وكاميرات داش كام 4K',
    descriptionEn: 'Overland 4x4 fridges, portable power stations for desert camping, and 4K dashcams',
    iconName: 'Compass',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=85',
    subcategories: [
      { id: 'auto-camping', nameAr: 'محطات الطاقة وثلاجات الرحلات', nameEn: 'Power Stations & Car Fridges' },
      { id: 'auto-dashcam', nameAr: 'كاميرات السيارات الذكية Dashcam', nameEn: '4K Smart Dashcams' },
      { id: 'auto-care', nameAr: 'مضخات الهواء ومعدات الطوارئ', nameEn: 'Tire Inflators & Jump Starters' },
    ],
  },
  {
    id: 'gaming',
    nameAr: 'الألعاب والترفيه المنزلي',
    nameEn: 'Gaming & Next-Gen Consoles',
    descriptionAr: 'منصات الألعاب الحديثة، نظارات الواقع الافتراضي، وكراسي الألعاب الاحترافية',
    descriptionEn: 'Next-gen gaming consoles, VR headsets, and ergonomic gaming chairs',
    iconName: 'Gamepad2',
    image: 'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=800&q=85',
    subcategories: [
      { id: 'gaming-consoles', nameAr: 'أجهزة الكونسول والمنصات المحمولة', nameEn: 'Consoles & Handhelds' },
      { id: 'gaming-vr', nameAr: 'نظارات الواقع الافتراضي والمحاكاة', nameEn: 'VR Headsets & Racing Sims' },
      { id: 'gaming-gear', nameAr: 'إكسسوارات وكراسي الألعاب', nameEn: 'Pro Controllers & Chairs' },
    ],
  },
  {
    id: 'books',
    nameAr: 'الكتب والإصدارات الثقافية',
    nameEn: 'Coffee Table Books & Culture',
    descriptionAr: 'مجلدات مصورة فاخرة عن التراث السعودي والعمارة، وكتب القيادة والأعمال',
    descriptionEn: 'Luxury illustrated volumes on Saudi heritage, architecture, and leadership',
    iconName: 'BookOpen',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=800&q=85',
    subcategories: [
      { id: 'books-art', nameAr: 'مجلدات الفنون والتراث السعودي', nameEn: 'Saudi Heritage Coffee Table Books' },
      { id: 'books-business', nameAr: 'كتب الإدارة والاقتصاد والريادة', nameEn: 'Leadership & Strategy Books' },
    ],
  },
  {
    id: 'health',
    nameAr: 'الصحة والعافية الذكية',
    nameEn: 'Smart Health & Wellness',
    descriptionAr: 'خواتم تتبع النوم والمؤشرات الحيوية، موازين ذكية، ومكملات صحية موثوقة',
    descriptionEn: 'Biometric smart rings, body composition analyzers, and wellness devices',
    iconName: 'Activity',
    image: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=85',
    subcategories: [
      { id: 'health-trackers', nameAr: 'أجهزة قياس المؤشرات الحيوية والنوم', nameEn: 'Biometric & Sleep Trackers' },
      { id: 'health-care', nameAr: 'أجهزة العناية الصحية المنزلية', nameEn: 'Home Medical & Wellness Monitors' },
    ],
  },
];

export const INITIAL_BRANDS: Brand[] = [
  { id: 'brand-dar-oud', nameAr: 'دار الطيب الملكي', nameEn: 'Dar Al-Teeb Royal', originAr: 'المملكة العربية السعودية', originEn: 'Saudi Arabia', categoryIds: ['perfumes'], featured: true },
  { id: 'brand-geneva', nameAr: 'أورولوجيا جنيف', nameEn: 'Horologia Genève', originAr: 'سويسرا', originEn: 'Switzerland', categoryIds: ['watches'], featured: true },
  { id: 'brand-apple', nameAr: 'آبل', nameEn: 'Apple', originAr: 'الولايات المتحدة', originEn: 'USA', categoryIds: ['smartphones', 'computers', 'electronics'], featured: true },
  { id: 'brand-samsung', nameAr: 'سامسونج', nameEn: 'Samsung', originAr: 'كوريا الجنوبية', originEn: 'South Korea', categoryIds: ['smartphones', 'electronics'], featured: true },
  { id: 'brand-dyson', nameAr: 'دايسون', nameEn: 'Dyson', originAr: 'المملكة المتحدة', originEn: 'United Kingdom', categoryIds: ['beauty', 'home-kitchen'], featured: true },
  { id: 'brand-najd', nameAr: 'أتيليه نجد الملكي', nameEn: 'Najd Royal Atelier', originAr: 'المملكة العربية السعودية', originEn: 'Saudi Arabia', categoryIds: ['mens-fashion', 'womens-fashion'], featured: true },
  { id: 'brand-breville', nameAr: 'بريفيل ولامارزوكو', nameEn: 'La Marzocco & Breville', originAr: 'إيطاليا / أستراليا', originEn: 'Italy / Australia', categoryIds: ['home-kitchen'], featured: true },
  { id: 'brand-sony', nameAr: 'سوني', nameEn: 'Sony', originAr: 'اليابان', originEn: 'Japan', categoryIds: ['electronics', 'gaming'], featured: true },
  { id: 'brand-garmin', nameAr: 'جارمن', nameEn: 'Garmin', originAr: 'الولايات المتحدة', originEn: 'USA', categoryIds: ['watches', 'sports', 'health'], featured: true },
  { id: 'brand-ecoflow', nameAr: 'إيكو فلو وصحارى', nameEn: 'EcoFlow & Sahara', originAr: 'عالمي', originEn: 'Global', categoryIds: ['automotive', 'sports'], featured: true },
  { id: 'brand-qassim', nameAr: 'خيرات القصيم الملكية', nameEn: 'Qassim Royal Harvest', originAr: 'المملكة العربية السعودية', originEn: 'Saudi Arabia', categoryIds: ['supermarket'], featured: true },
  { id: 'brand-assouline', nameAr: 'دار أسولين للنشر', nameEn: 'Assouline Editions', originAr: 'فرنسا', originEn: 'France', categoryIds: ['books'], featured: true },
];

export const INITIAL_SELLERS: Seller[] = [
  {
    id: 'seller-1',
    nameAr: 'دار العود والطيب الملكي',
    nameEn: 'Dar Al-Oud Royal Perfumery',
    descriptionAr: 'تجار معتمدون لنوادر العود الطبيعي المعتّق والعطور الشرقية الملكية في الرياض منذ ١٩٩٨م.',
    descriptionEn: 'Authorized purveyors of rare aged agarwood and royal oriental fragrances in Riyadh since 1998.',
    cityAr: 'الرياض',
    cityEn: 'Riyadh',
    crNumber: '1010482910',
    vatNumber: '310192837400003',
    iban: 'SA4480000204608010167519',
    ownerName: 'عبدالله بن فهد التميمي',
    email: 'info@daraloud.sa',
    phone: '+966 50 411 8899',
    status: 'approved',
    verifiedBadge: true,
    rating: 4.9,
    reviewCount: 642,
    commissionRate: 12,
    grossSales: 486500,
    platformCommission: 58380,
    refundsTotal: 4200,
    netEarnings: 423920,
    availableBalance: 64800,
    nextPayoutDate: '2026-10-05',
    joinedAt: '2025-02-14',
    categories: ['perfumes'],
    payoutHistory: [
      { id: 'pay-101', amount: 82400, status: 'completed', bankNameAr: 'مصرف الراجحي', bankNameEn: 'Al Rajhi Bank', ibanLast4: '7519', date: '2026-09-05' },
      { id: 'pay-102', amount: 74150, status: 'completed', bankNameAr: 'مصرف الراجحي', bankNameEn: 'Al Rajhi Bank', ibanLast4: '7519', date: '2026-08-05' },
    ],
    operationalSettings: {
      defaultCarrier: 'SPL Express VIP',
      sameDayCutoff: '16:00',
      luxuryPackagingEnabled: true,
      coldChainEnabled: true,
      autoZatcaInvoice: true,
      whatsappOrderAlerts: true,
      lowStockEmailAlerts: true,
      updatedAt: '2026-09-20',
    },
  },
  {
    id: 'seller-2',
    applicantUserId: 'user-seller-1',
    nameAr: 'آفاق التقنية المعتمدة',
    nameEn: 'Afaq Tech Authorized Store',
    descriptionAr: 'موزع معتمد لأحدث الأجهزة الذكية والحواسيب المحمولة والصوتيات الاحترافية بضمان الوكيل سنتين.',
    descriptionEn: 'Authorized distributor for flagship smartphones, pro laptops, and audio gear with 2-year KSA warranty.',
    cityAr: 'الرياض',
    cityEn: 'Riyadh',
    crNumber: '1010773921',
    vatNumber: '310556473800003',
    iban: 'SA8910000012345678901234',
    ownerName: 'سلمان بن عبدالعزيز العتيبي',
    email: 'seller@atheel.sa',
    phone: '+966 55 892 3311',
    status: 'approved',
    verifiedBadge: true,
    rating: 4.8,
    reviewCount: 1280,
    commissionRate: 8,
    grossSales: 942000,
    platformCommission: 75360,
    refundsTotal: 11800,
    netEarnings: 854840,
    availableBalance: 118450,
    nextPayoutDate: '2026-10-01',
    joinedAt: '2025-01-10',
    categories: ['smartphones', 'electronics', 'computers', 'gaming', 'health'],
    payoutHistory: [
      { id: 'pay-201', amount: 145000, status: 'completed', bankNameAr: 'البنك الأهلي السعودي SNB', bankNameEn: 'Saudi National Bank', ibanLast4: '1234', date: '2026-09-01' },
      { id: 'pay-202', amount: 132600, status: 'completed', bankNameAr: 'البنك الأهلي السعودي SNB', bankNameEn: 'Saudi National Bank', ibanLast4: '1234', date: '2026-08-01' },
      { id: 'pay-203', amount: 118450, status: 'scheduled', bankNameAr: 'البنك الأهلي السعودي SNB', bankNameEn: 'Saudi National Bank', ibanLast4: '1234', date: '2026-10-01' },
    ],
    operationalSettings: {
      defaultCarrier: 'Aramex Premium',
      sameDayCutoff: '17:00',
      luxuryPackagingEnabled: true,
      coldChainEnabled: true,
      autoZatcaInvoice: true,
      whatsappOrderAlerts: true,
      lowStockEmailAlerts: true,
      updatedAt: '2026-09-25',
    },
  },
  {
    id: 'seller-3',
    nameAr: 'قصر الساعات السويسرية',
    nameEn: 'Swiss Horology Palace',
    descriptionAr: 'بوتيك متخصص في الساعات السويسرية الفاخرة والإكسسوارات الرجالية والنسائية النادرة مع شهادة فحص وأصالة.',
    descriptionEn: 'Premier boutique specializing in Swiss luxury watches and fine accessories with certified authentication.',
    cityAr: 'جدة',
    cityEn: 'Jeddah',
    crNumber: '4030291844',
    vatNumber: '310998271600003',
    iban: 'SA1245000000987654321098',
    ownerName: 'طلال بن خالد باخشب',
    email: 'vip@swisspalace.sa',
    phone: '+966 54 220 9900',
    status: 'approved',
    verifiedBadge: true,
    rating: 4.95,
    reviewCount: 389,
    commissionRate: 10,
    grossSales: 1250000,
    platformCommission: 125000,
    refundsTotal: 0,
    netEarnings: 1125000,
    availableBalance: 194000,
    nextPayoutDate: '2026-10-05',
    joinedAt: '2025-03-01',
    categories: ['watches'],
    payoutHistory: [
      { id: 'pay-301', amount: 210000, status: 'completed', bankNameAr: 'بنك ساب الأول SAB', bankNameEn: 'SAB Bank', ibanLast4: '1098', date: '2026-09-05' },
    ],
  },
  {
    id: 'seller-4',
    nameAr: 'أتيليه نجد للأزياء والعبايات',
    nameEn: 'Najd Couture & Royal Attire',
    descriptionAr: 'تصاميم سعودية معاصرة تجمع بين البشوت الملكية الحساوية، الأشمغة الفاخرة، وعبايات الكوتور النسائية.',
    descriptionEn: 'Contemporary Saudi couture blending royal Hasawi bishts, fine shemaghs, and silk abayas.',
    cityAr: 'الرياض',
    cityEn: 'Riyadh',
    crNumber: '1010998412',
    vatNumber: '310443291800003',
    iban: 'SA5520000001122334455667',
    ownerName: 'العنود بنت محمد السديري',
    email: 'atelier@najdcouture.sa',
    phone: '+966 56 771 4422',
    status: 'approved',
    verifiedBadge: true,
    rating: 4.85,
    reviewCount: 514,
    commissionRate: 14,
    grossSales: 398000,
    platformCommission: 55720,
    refundsTotal: 8400,
    netEarnings: 333880,
    availableBalance: 42300,
    nextPayoutDate: '2026-10-05',
    joinedAt: '2025-04-12',
    categories: ['mens-fashion', 'womens-fashion', 'books'],
    payoutHistory: [
      { id: 'pay-401', amount: 58900, status: 'completed', bankNameAr: 'بنك الرياض', bankNameEn: 'Riyad Bank', ibanLast4: '5667', date: '2026-09-05' },
    ],
  },
  {
    id: 'seller-5',
    nameAr: 'رواق القهوة والمنزل الفاخر',
    nameEn: 'Rawaq Specialty Coffee & Living',
    descriptionAr: 'الوكيل المعتمد لمكائن الإسبريسو الإيطالية، أدوات القهوة المختصة، وأطقم الضيافة السعودية المذهّبة.',
    descriptionEn: 'Authorized dealer for Italian espresso machines, specialty coffee gear, and gilded hospitality sets.',
    cityAr: 'الخبر',
    cityEn: 'Al Khobar',
    crNumber: '2051094823',
    vatNumber: '310776543200003',
    iban: 'SA7705000068201928374650',
    ownerName: 'ماجد بن سعد المعجل',
    email: 'care@rawaqhome.sa',
    phone: '+966 53 119 8877',
    status: 'approved',
    verifiedBadge: true,
    rating: 4.9,
    reviewCount: 720,
    commissionRate: 11,
    grossSales: 524000,
    platformCommission: 57640,
    refundsTotal: 5100,
    netEarnings: 461260,
    availableBalance: 71200,
    nextPayoutDate: '2026-10-05',
    joinedAt: '2025-02-28',
    categories: ['home-kitchen', 'supermarket'],
    payoutHistory: [
      { id: 'pay-501', amount: 89000, status: 'completed', bankNameAr: 'مصرف الإنماء', bankNameEn: 'Alinma Bank', ibanLast4: '4650', date: '2026-09-05' },
    ],
  },
  {
    id: 'seller-6',
    nameAr: 'واحة الجمال والعناية',
    nameEn: 'Beauty Oasis Luxury Care',
    descriptionAr: 'وجهة الجمال الأولى لأجهزة العناية بالشعر، مستحضرات البشرة الإكلينيكية، ومستلزمات الأطفال الفاخرة.',
    descriptionEn: 'Premier destination for pro hair styling tech, clinical skincare, and luxury baby gear.',
    cityAr: 'جدة',
    cityEn: 'Jeddah',
    crNumber: '4030881239',
    vatNumber: '310665432100003',
    iban: 'SA3380000123456789009876',
    ownerName: 'ريم بنت طارق الجفالي',
    email: 'hello@beautyoasis.sa',
    phone: '+966 50 998 1122',
    status: 'approved',
    verifiedBadge: true,
    rating: 4.75,
    reviewCount: 430,
    commissionRate: 13,
    grossSales: 312000,
    platformCommission: 40560,
    refundsTotal: 3900,
    netEarnings: 267540,
    availableBalance: 38900,
    nextPayoutDate: '2026-10-05',
    joinedAt: '2025-05-19',
    categories: ['beauty', 'kids'],
    payoutHistory: [],
  },
  {
    id: 'seller-7',
    nameAr: 'صحارى للرحلات والرياضة',
    nameEn: 'Sahara Overland & Pro Sports',
    descriptionAr: 'متخصصون في تجهيزات الرحلات البرية الفاخرة (Glamping)، محطات الطاقة، ومعدات البادل واللياقة.',
    descriptionEn: 'Specialists in luxury desert glamping gear, portable power stations, and pro Padel equipment.',
    cityAr: 'الدمام',
    cityEn: 'Dammam',
    crNumber: '2050667123',
    vatNumber: '310223344500003',
    iban: 'SA9180000554433221100998',
    ownerName: 'بدر بن ناصر القحطاني',
    email: 'sales@saharaoverland.sa',
    phone: '+966 59 334 5566',
    status: 'approved',
    verifiedBadge: true,
    rating: 4.8,
    reviewCount: 295,
    commissionRate: 10,
    grossSales: 276000,
    platformCommission: 27600,
    refundsTotal: 2100,
    netEarnings: 246300,
    availableBalance: 31500,
    nextPayoutDate: '2026-10-05',
    joinedAt: '2025-06-01',
    categories: ['automotive', 'sports'],
    payoutHistory: [],
  },
  {
    id: 'seller-8',
    applicantUserId: 'user-applicant-8',
    nameAr: 'تمور وخيرات القصيم الملكية',
    nameEn: 'Qassim Royal Dates & Sidr Honey',
    descriptionAr: 'مزارع ومناحل معتمدة لإنتاج أفخر تمور السكري والمجدول الملكي وعسل السدر الجبلي الأصلي.',
    descriptionEn: 'Certified organic farms and apiaries producing royal Majdool dates and pure mountain Sidr honey.',
    cityAr: 'بريدة',
    cityEn: 'Buraidah',
    crNumber: '1131098765',
    vatNumber: '310887766500003',
    iban: 'SA6680000998877665544332',
    ownerName: 'صالح بن إبراهيم أبا الخيل',
    email: 'orders@qassimroyal.sa',
    phone: '+966 50 612 7788',
    status: 'pending',
    verifiedBadge: false,
    rating: 4.9,
    reviewCount: 45,
    commissionRate: 10,
    grossSales: 18500,
    platformCommission: 1850,
    refundsTotal: 0,
    netEarnings: 16650,
    availableBalance: 16650,
    nextPayoutDate: '2026-10-10',
    joinedAt: '2026-09-20',
    categories: ['supermarket'],
    payoutHistory: [],
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    id: 'cpn-1',
    code: 'ATHEEL15',
    titleAr: 'خصم ١٥٪ على جميع الأقسام المختارة',
    titleEn: '15% Off Sitewide Curated Selections',
    type: 'percentage',
    value: 15,
    minOrderAmount: 300,
    maxDiscount: 450,
    maxUses: 1000,
    usedCount: 342,
    sellerId: 'all',
    sellerNameAr: 'جميع متاجر أثيل',
    expiresAt: '2026-12-31',
    isActive: true,
  },
  {
    id: 'cpn-2',
    code: 'WELCOME100',
    titleAr: 'هدية الترحيب ١٠٠ ر.س للطلبات فوق ٥٠٠ ر.س',
    titleEn: '100 SAR Welcome Privilege on Orders 500+ SAR',
    type: 'fixed',
    value: 100,
    minOrderAmount: 500,
    maxUses: 500,
    usedCount: 189,
    sellerId: 'all',
    sellerNameAr: 'جميع متاجر أثيل',
    expiresAt: '2026-12-31',
    isActive: true,
  },
  {
    id: 'cpn-3',
    code: 'RIYADH20',
    titleAr: 'خصم ٢٠٪ خاص لموسم الفخامة (بحد أقصى ٥٠٠ ر.س)',
    titleEn: '20% Luxury Season Privilege (Max 500 SAR)',
    type: 'percentage',
    value: 20,
    minOrderAmount: 1000,
    maxDiscount: 500,
    maxUses: 300,
    usedCount: 112,
    sellerId: 'all',
    sellerNameAr: 'جميع متاجر أثيل',
    expiresAt: '2026-11-30',
    isActive: true,
  },
  {
    id: 'cpn-4',
    code: 'AFAQ10',
    titleAr: 'خصم ١٠٪ خاص بمتجر آفاق التقنية المعتمدة',
    titleEn: '10% Exclusive to Afaq Tech Authorized Store',
    type: 'percentage',
    value: 10,
    minOrderAmount: 400,
    maxDiscount: 350,
    maxUses: 400,
    usedCount: 94,
    sellerId: 'seller-2',
    sellerNameAr: 'آفاق التقنية المعتمدة',
    expiresAt: '2026-12-15',
    isActive: true,
  },
  {
    id: 'cpn-7',
    code: 'AFAQVIP300',
    titleAr: 'خصم ٣٠٠ ر.س على الحواسيب الاحترافية والهواتف الذكية',
    titleEn: '300 SAR Off Flagship Laptops & Smartphones at Afaq Tech',
    type: 'fixed',
    value: 300,
    minOrderAmount: 3500,
    maxUses: 150,
    usedCount: 38,
    sellerId: 'seller-2',
    sellerNameAr: 'آفاق التقنية المعتمدة',
    expiresAt: '2026-11-30',
    isActive: true,
  },
  {
    id: 'cpn-5',
    code: 'OUD25',
    titleAr: 'خصم ٢٥٪ على نوادر دار العود والطيب الملكي',
    titleEn: '25% Off Dar Al-Oud Royal Fragrances',
    type: 'percentage',
    value: 25,
    minOrderAmount: 600,
    maxDiscount: 600,
    maxUses: 200,
    usedCount: 77,
    sellerId: 'seller-1',
    sellerNameAr: 'دار العود والطيب الملكي',
    expiresAt: '2026-12-31',
    isActive: true,
  },
  {
    id: 'cpn-6',
    code: 'VIP250',
    titleAr: 'خصم ٢٥٠ ر.س على الساعات والمقتنيات الفاخرة',
    titleEn: '250 SAR Off Fine Watches & Luxury Goods',
    type: 'fixed',
    value: 250,
    minOrderAmount: 2500,
    maxUses: 150,
    usedCount: 41,
    sellerId: 'all',
    sellerNameAr: 'جميع متاجر أثيل',
    expiresAt: '2026-12-31',
    isActive: true,
  },
];

export const INITIAL_USERS: UserProfile[] = [
  {
    id: 'user-customer-1',
    name: 'فيصل بن عبدالعزيز الراجحي',
    email: 'customer@atheel.sa',
    phone: '+966 50 511 9988',
    role: 'customer',
    walletBalance: 1450.0,
    loyaltyPoints: 4850,
    loyaltyTier: 'Royal Obsidian',
    referralCode: 'FAISAL-ATH26',
    wishlist: ['prod-1', 'prod-3', 'prod-9', 'prod-21'],
    addresses: [
      {
        id: 'addr-1',
        labelAr: 'المنزل الرئيسي - حطين',
        labelEn: 'Primary Residence - Hittin',
        recipientName: 'فيصل بن عبدالعزيز الراجحي',
        phone: '+966 50 511 9988',
        cityAr: 'الرياض',
        cityEn: 'Riyadh',
        districtAr: 'حي حطين',
        streetAr: 'طريق الأمير محمد بن سلمان بن عبدالعزيز',
        buildingNumber: '4281',
        postalCode: '13516',
        additionalNumber: '7392',
        landmarkAr: 'بجوار بوليفارد رياض سيتي - البوابة الشمالية',
        isDefault: true,
      },
      {
        id: 'addr-2',
        labelAr: 'المكتب التنفيذي - كافد KAFD',
        labelEn: 'Executive Office - KAFD',
        recipientName: 'فيصل بن عبدالعزيز الراجحي',
        phone: '+966 50 511 9988',
        cityAr: 'الرياض',
        cityEn: 'Riyadh',
        districtAr: 'حي العقيق - مركز الملك عبدالله المالي',
        streetAr: 'طريق الملك فهد الفرعي - برج ٤٠٢',
        buildingNumber: '2910',
        postalCode: '13519',
        additionalNumber: '6614',
        landmarkAr: 'الطابق ١٨ - مكتب الاستقبال الشرقي',
        isDefault: false,
      },
      {
        id: 'addr-3',
        labelAr: 'منزل العطلات - أبحر الشمالية',
        labelEn: 'Holiday Villa - North Obhur',
        recipientName: 'فيصل بن عبدالعزيز الراجحي',
        phone: '+966 50 511 9988',
        cityAr: 'جدة',
        cityEn: 'Jeddah',
        districtAr: 'حي الشاطئ',
        streetAr: 'طريق الكورنيش الفرعي',
        buildingNumber: '8824',
        postalCode: '23413',
        additionalNumber: '3109',
        landmarkAr: 'مقابل نادي جدة لليخوت',
        isDefault: false,
      },
    ],
    loyaltyHistory: [
      { id: 'lh-1', titleAr: 'مكافأة شراء طلب #ATH-98421', titleEn: 'Purchase Reward Order #ATH-98421', points: 1850, date: '2026-09-22' },
      { id: 'lh-2', titleAr: 'مكافأة العضوية الملكية السنوية', titleEn: 'Annual Royal Obsidian Tier Bonus', points: 2000, date: '2026-09-01' },
      { id: 'lh-3', titleAr: 'دعوة صديق عبر كود FAISAL-ATH26', titleEn: 'Referral Reward via FAISAL-ATH26', points: 1000, date: '2026-08-19' },
    ],
    preferences: {
      newsletter: true,
      smsAlerts: true,
      whatsappUpdates: true,
      language: 'ar',
    },
    createdAt: '2025-05-10',
  },
  {
    id: 'user-seller-1',
    name: 'سلمان بن عبدالعزيز العتيبي',
    email: 'seller@atheel.sa',
    phone: '+966 55 892 3311',
    role: 'seller',
    sellerId: 'seller-2',
    walletBalance: 0,
    loyaltyPoints: 1200,
    loyaltyTier: 'Gold',
    referralCode: 'SALMAN-ATH',
    wishlist: [],
    addresses: [
      {
        id: 'addr-seller-1',
        labelAr: 'المقر الرئيسي - العليا',
        labelEn: 'HQ Office - Olaya',
        recipientName: 'سلمان العتيبي',
        phone: '+966 55 892 3311',
        cityAr: 'الرياض',
        cityEn: 'Riyadh',
        districtAr: 'حي العليا',
        streetAr: 'طريق العليا العام',
        buildingNumber: '3112',
        postalCode: '12214',
        additionalNumber: '4490',
        landmarkAr: 'برج المملكة - الدور ١٢',
        isDefault: true,
      },
    ],
    loyaltyHistory: [],
    preferences: {
      newsletter: true,
      smsAlerts: true,
      whatsappUpdates: true,
      language: 'ar',
    },
    createdAt: '2025-01-10',
  },
  {
    id: 'user-admin-1',
    name: 'نورة بنت سلطان القحطاني',
    email: 'admin@atheel.sa',
    phone: '+966 50 100 2020',
    role: 'admin',
    walletBalance: 5000,
    loyaltyPoints: 9900,
    loyaltyTier: 'Royal Obsidian',
    referralCode: 'NOURA-EXEC',
    wishlist: [],
    addresses: [
      {
        id: 'addr-admin-1',
        labelAr: 'الإدارة التنفيذية - الدرعية',
        labelEn: 'Executive HQ - Diriyah',
        recipientName: 'نورة القحطاني',
        phone: '+966 50 100 2020',
        cityAr: 'الرياض',
        cityEn: 'Riyadh',
        districtAr: 'حي الخزامى',
        streetAr: 'طريق الملك خالد',
        buildingNumber: '1920',
        postalCode: '12572',
        additionalNumber: '8812',
        landmarkAr: 'بجوار بوابة الدرعية',
        isDefault: true,
      },
    ],
    loyaltyHistory: [],
    preferences: {
      newsletter: true,
      smsAlerts: true,
      whatsappUpdates: true,
      language: 'ar',
    },
    createdAt: '2025-01-01',
  },
  {
    id: 'user-customer-2',
    name: 'سارة بنت خالد العليان',
    email: 'sara.olayan@example.sa',
    phone: '+966 54 321 7766',
    role: 'customer',
    walletBalance: 620.0,
    loyaltyPoints: 2400,
    loyaltyTier: 'Gold',
    referralCode: 'SARA-ATH26',
    wishlist: ['prod-2', 'prod-15'],
    addresses: [
      {
        id: 'addr-c2',
        labelAr: 'المنزل - الروضة',
        labelEn: 'Home - Al Rawdah',
        recipientName: 'سارة العليان',
        phone: '+966 54 321 7766',
        cityAr: 'جدة',
        cityEn: 'Jeddah',
        districtAr: 'حي الروضة',
        streetAr: 'شارع الأمير سلطان',
        buildingNumber: '5190',
        postalCode: '23434',
        additionalNumber: '2190',
        landmarkAr: 'قرب الخياط سنتر',
        isDefault: true,
      },
    ],
    loyaltyHistory: [],
    preferences: { newsletter: true, smsAlerts: true, whatsappUpdates: false, language: 'ar' },
    createdAt: '2025-07-14',
  },
  {
    id: 'user-customer-3',
    name: 'فهد بن محمد الدوسري',
    email: 'fahad.dosari@example.sa',
    phone: '+966 56 889 4411',
    role: 'customer',
    walletBalance: 310.0,
    loyaltyPoints: 1650,
    loyaltyTier: 'Silver',
    referralCode: 'FAHAD-ATH26',
    wishlist: ['prod-5'],
    addresses: [
      {
        id: 'addr-c3',
        labelAr: 'المنزل - الحزام الذهبي',
        labelEn: 'Home - Golden Belt',
        recipientName: 'فهد الدوسري',
        phone: '+966 56 889 4411',
        cityAr: 'الخبر',
        cityEn: 'Al Khobar',
        districtAr: 'حي الحزام الذهبي',
        streetAr: 'طريق الأمير فيصل بن فهد',
        buildingNumber: '7412',
        postalCode: '34432',
        additionalNumber: '9012',
        landmarkAr: 'بالقرب من كورنيش الخبر',
        isDefault: true,
      },
    ],
    loyaltyHistory: [],
    preferences: { newsletter: true, smsAlerts: true, whatsappUpdates: true, language: 'ar' },
    createdAt: '2025-09-02',
  },
  {
    id: 'user-applicant-8',
    name: 'صالح بن إبراهيم أبا الخيل',
    email: 'orders@qassimroyal.sa',
    phone: '+966 50 612 7788',
    role: 'customer',
    walletBalance: 450.0,
    loyaltyPoints: 1500,
    loyaltyTier: 'Silver',
    referralCode: 'SALEH-ATH26',
    wishlist: [],
    addresses: [
      {
        id: 'addr-c8',
        labelAr: 'المقر التجاري - بريدة',
        labelEn: 'Commercial HQ - Buraidah',
        recipientName: 'صالح أبا الخيل',
        phone: '+966 50 612 7788',
        cityAr: 'بريدة',
        cityEn: 'Buraidah',
        districtAr: 'حي الصفراء',
        streetAr: 'طريق الملك عبدالعزيز',
        buildingNumber: '3310',
        postalCode: '52382',
        additionalNumber: '6412',
        landmarkAr: 'بجوار مدينة التمور ببريدة',
        isDefault: true,
      },
    ],
    loyaltyHistory: [],
    preferences: { newsletter: true, smsAlerts: true, whatsappUpdates: true, language: 'ar' },
    createdAt: '2026-09-20',
  },
];

export function buildOrderTimeline(currentStatus: OrderStatus, baseDateIso: string): OrderTimelineEvent[] {
  const stages: {
    status: OrderStatus;
    titleAr: string;
    titleEn: string;
    descriptionAr: string;
    descriptionEn: string;
  }[] = [
    {
      status: 'placed',
      titleAr: 'تم استلام الطلب',
      titleEn: 'Order Placed',
      descriptionAr: 'تم تسجيل طلبك بنجاح وإصدار الفاتورة الضريبية الإلكترونية.',
      descriptionEn: 'Your order has been registered and tax invoice generated.',
    },
    {
      status: 'confirmed',
      titleAr: 'تم تأكيد الطلب',
      titleEn: 'Order Confirmed',
      descriptionAr: 'تم التحقق من الدفع وتأكيد توفر القطع لدى المتجر المعتمد.',
      descriptionEn: 'Payment verified and inventory reserved by the verified boutique.',
    },
    {
      status: 'preparing',
      titleAr: 'قيد التجهيز والتغليف الفاخر',
      titleEn: 'Preparing & Luxury Packaging',
      descriptionAr: 'يتم فحص الجودة وتغليف المقتنيات في عبوة أثيل الفاخرة.',
      descriptionEn: 'Quality inspection and signature Atheel luxury gift packaging in progress.',
    },
    {
      status: 'shipped',
      titleAr: 'تم الشحن مع الناقل المعتمد',
      titleEn: 'Shipped with Express Carrier',
      descriptionAr: 'غادرت الشحنة مستودع التاجر وهي في طريقها إلى مدينتك.',
      descriptionEn: 'Parcel departed merchant facility via VIP temperature-controlled courier.',
    },
    {
      status: 'out_for_delivery',
      titleAr: 'خرج للتوصيل',
      titleEn: 'Out for Delivery',
      descriptionAr: 'مندوب التوصيل في طريقه إلى عنوانك الوطني المسجل.',
      descriptionEn: 'Courier is en route to your registered Saudi National Address.',
    },
    {
      status: 'delivered',
      titleAr: 'تم التسليم بنجاح',
      titleEn: 'Delivered',
      descriptionAr: 'تم تسليم الطلب بنجاح للمستلم. نسعد بخدمتكم في أثيل.',
      descriptionEn: 'Order delivered directly to recipient. Thank you for shopping at Atheel.',
    },
  ];

  const statusOrder: OrderStatus[] = [
    'placed',
    'confirmed',
    'preparing',
    'shipped',
    'out_for_delivery',
    'delivered',
  ];

  const activeIdx =
    currentStatus === 'return_requested' || currentStatus === 'returned'
      ? 5
      : currentStatus === 'cancelled'
      ? 0
      : statusOrder.indexOf(currentStatus);

  return stages.map((stage, idx) => ({
    ...stage,
    timestamp: idx <= activeIdx ? baseDateIso : '',
    completed: idx <= activeIdx,
  }));
}

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-98421',
    orderNumber: 'ATH-98421',
    customerId: 'user-customer-1',
    customerName: 'فيصل بن عبدالعزيز الراجحي',
    customerEmail: 'customer@atheel.sa',
    customerPhone: '+966 50 511 9988',
    sellerIds: ['seller-3', 'seller-1'],
    productIds: ['prod-1', 'prod-5'],
    items: [
      {
        productId: 'prod-1',
        sku: 'ATH-WTC-001',
        titleAr: 'ساعة أورولوجيا جنيف كرونوغراف أوتوماتيك - إصدار الدرعية الملكي',
        titleEn: 'Horologia Genève Automatic Chronograph - Diriyah Royal Edition',
        image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=85',
        sellerId: 'seller-3',
        sellerNameAr: 'قصر الساعات السويسرية',
        sellerNameEn: 'Swiss Horology Palace',
        quantity: 1,
        unitPrice: 6450,
        selectedVariants: { 'لون الميناء': 'أخضر زمردي ملكي (Emerald)', 'المقاس': '41 mm' },
      },
      {
        productId: 'prod-5',
        sku: 'ATH-PRF-001',
        titleAr: 'دهن عود كمبودي ملكي معتّق نادر - توله كاملة في صندوق خشب الجوز',
        titleEn: 'Rare Aged Royal Cambodian Oud Oil - Full Tola in Walnut Box',
        image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=800&q=85',
        sellerId: 'seller-1',
        sellerNameAr: 'دار العود والطيب الملكي',
        sellerNameEn: 'Dar Al-Oud Royal Perfumery',
        quantity: 1,
        unitPrice: 1850,
        selectedVariants: { 'الحجم': 'توله كاملة (12 مل)' },
      },
    ],
    address: INITIAL_USERS[0].addresses[0],
    deliverySpeed: 'express',
    paymentMethod: 'mada',
    paymentReference: 'MADA-TX-8849201',
    subtotal: 8300,
    discountAmount: 450,
    couponCode: 'ATHEEL15',
    shippingFee: 0,
    vatAmount: 1023.91,
    total: 7850,
    status: 'delivered',
    trackingNumber: 'SPL-882910442SA',
    carrierAr: 'سبل إكسبريس VIP',
    carrierEn: 'SPL Express VIP',
    timeline: buildOrderTimeline('delivered', '2026-09-22'),
    createdAt: '2026-09-20T14:30:00Z',
    updatedAt: '2026-09-22T18:10:00Z',
  },
  {
    id: 'ord-98504',
    orderNumber: 'ATH-98504',
    customerId: 'user-customer-1',
    customerName: 'فيصل بن عبدالعزيز الراجحي',
    customerEmail: 'customer@atheel.sa',
    customerPhone: '+966 50 511 9988',
    sellerIds: ['seller-2'],
    productIds: ['prod-9', 'prod-13'],
    items: [
      {
        productId: 'prod-9',
        sku: 'ATH-MOB-001',
        titleAr: 'هاتف آيفون ١٦ برو ماكس سعة ٥١٢ جيجابايت - تيتانيوم صحراوي (ضمان حاسبات العرب)',
        titleEn: 'iPhone 16 Pro Max 512GB - Desert Titanium (Official KSA Warranty)',
        image: 'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=800&q=85',
        sellerId: 'seller-2',
        sellerNameAr: 'آفاق التقنية المعتمدة',
        sellerNameEn: 'Afaq Tech Authorized Store',
        quantity: 1,
        unitPrice: 5699,
        selectedVariants: { 'اللون': 'تيتانيوم صحراوي', 'السعة': '512 GB' },
      },
      {
        productId: 'prod-13',
        sku: 'ATH-AUD-001',
        titleAr: 'سماعة سوني اللاسلكية WH-1000XM5 العازلة للضجيج - إصدار البلاتين الفاخر',
        titleEn: 'Sony WH-1000XM5 Wireless Noise Canceling Headphones - Platinum Silver',
        image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=85',
        sellerId: 'seller-2',
        sellerNameAr: 'آفاق التقنية المعتمدة',
        sellerNameEn: 'Afaq Tech Authorized Store',
        quantity: 1,
        unitPrice: 1299,
        selectedVariants: { 'اللون': 'فضي بلاتيني' },
      },
    ],
    address: INITIAL_USERS[0].addresses[0],
    deliverySpeed: 'express',
    paymentMethod: 'apple_pay',
    paymentReference: 'APAY-SA-9920118',
    subtotal: 6998,
    discountAmount: 350,
    couponCode: 'AFAQ10',
    shippingFee: 0,
    vatAmount: 867.13,
    total: 6648,
    status: 'out_for_delivery',
    trackingNumber: 'ARMX-99401288SA',
    carrierAr: 'أرامكس بريميوم',
    carrierEn: 'Aramex Premium',
    timeline: buildOrderTimeline('out_for_delivery', '2026-09-27'),
    createdAt: '2026-09-26T10:15:00Z',
    updatedAt: '2026-09-27T09:00:00Z',
  },
  {
    id: 'ord-98539',
    orderNumber: 'ATH-98539',
    customerId: 'user-customer-1',
    customerName: 'فيصل بن عبدالعزيز الراجحي',
    customerEmail: 'customer@atheel.sa',
    customerPhone: '+966 50 511 9988',
    sellerIds: ['seller-5'],
    productIds: ['prod-21'],
    items: [
      {
        productId: 'prod-21',
        sku: 'ATH-HOM-001',
        titleAr: 'ماكينة إسبريسو بريفيل أوراكل تاتش الاحترافية مع مطحنة مدمجة - ستانلس ستيل مصقول',
        titleEn: 'Breville Oracle Touch Dual Boiler Espresso Machine - Brushed Steel',
        image: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=85',
        sellerId: 'seller-5',
        sellerNameAr: 'رواق القهوة والمنزل الفاخر',
        sellerNameEn: 'Rawaq Specialty Coffee & Living',
        quantity: 1,
        unitPrice: 8490,
        selectedVariants: { 'اللون': 'ستانلس ستيل مصقول' },
      },
    ],
    address: INITIAL_USERS[0].addresses[1],
    deliverySpeed: 'express',
    paymentMethod: 'visa_mastercard',
    paymentReference: 'VISA-4419-8821',
    subtotal: 8490,
    discountAmount: 250,
    couponCode: 'VIP250',
    shippingFee: 0,
    vatAmount: 1074.78,
    total: 8240,
    status: 'preparing',
    trackingNumber: 'SMSA-77129940SA',
    carrierAr: 'سمسا إكسبريس',
    carrierEn: 'SMSA Express',
    timeline: buildOrderTimeline('preparing', '2026-09-27'),
    createdAt: '2026-09-27T08:45:00Z',
    updatedAt: '2026-09-27T11:20:00Z',
  },
  {
    id: 'ord-98310',
    orderNumber: 'ATH-98310',
    customerId: 'user-customer-2',
    customerName: 'سارة بنت خالد العليان',
    customerEmail: 'sara.olayan@example.sa',
    customerPhone: '+966 54 321 7766',
    sellerIds: ['seller-4', 'seller-6'],
    productIds: ['prod-29', 'prod-33'],
    items: [
      {
        productId: 'prod-29',
        sku: 'ATH-WOM-001',
        titleAr: 'عباية كوتور نجدي من الحرير الياباني الطبيعي مع تطريز يدوي بخيوط القصب الذهبي',
        titleEn: 'Najdi Couture Natural Japanese Silk Abaya with Hand-Spun Gold Embroidery',
        image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=85',
        sellerId: 'seller-4',
        sellerNameAr: 'أتيليه نجد للأزياء والعبايات',
        sellerNameEn: 'Najd Couture & Royal Attire',
        quantity: 1,
        unitPrice: 2450,
        selectedVariants: { 'المقاس': '56', 'اللون': 'أسود ملكي مطرز بالذهب' },
      },
      {
        productId: 'prod-33',
        sku: 'ATH-BTY-001',
        titleAr: 'جهاز تصفيف الشعر دايسون إير راب ملتي ستايلر كومبليت لونج - إصدار أزرق بروسيا والنحاس',
        titleEn: 'Dyson Airwrap Multi-Styler Complete Long - Prussian Blue & Rich Copper',
        image: 'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=800&q=85',
        sellerId: 'seller-6',
        sellerNameAr: 'واحة الجمال والعناية',
        sellerNameEn: 'Beauty Oasis Luxury Care',
        quantity: 1,
        unitPrice: 2399,
        selectedVariants: { 'الإصدار': 'كومبليت لونج (للشعر الطويل)' },
      },
    ],
    address: INITIAL_USERS[3].addresses[0],
    deliverySpeed: 'express',
    paymentMethod: 'stc_pay',
    paymentReference: 'STCPAY-7729104',
    subtotal: 4849,
    discountAmount: 100,
    couponCode: 'WELCOME100',
    shippingFee: 0,
    vatAmount: 619.43,
    total: 4749,
    status: 'delivered',
    trackingNumber: 'SPL-66120984SA',
    carrierAr: 'سبل إكسبريس VIP',
    carrierEn: 'SPL Express VIP',
    timeline: buildOrderTimeline('delivered', '2026-09-18'),
    createdAt: '2026-09-15T16:20:00Z',
    updatedAt: '2026-09-18T13:05:00Z',
  },
  {
    id: 'ord-98490',
    orderNumber: 'ATH-98490',
    customerId: 'user-customer-3',
    customerName: 'فهد بن محمد الدوسري',
    customerEmail: 'fahad.dosari@example.sa',
    customerPhone: '+966 56 889 4411',
    sellerIds: ['seller-2'],
    productIds: ['prod-17'],
    items: [
      {
        productId: 'prod-17',
        sku: 'ATH-CMP-001',
        titleAr: 'حاسوب أبل ماك بوك برو ١٦ إنش شريحة M3 Max بذاكرة ٤٨ جيجابايت وسعة ١ تيرابايت - أسود فلكي',
        titleEn: 'Apple MacBook Pro 16" M3 Max 48GB RAM 1TB SSD - Space Black (Arabic/English Keyboard)',
        image: 'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=800&q=85',
        sellerId: 'seller-2',
        sellerNameAr: 'آفاق التقنية المعتمدة',
        sellerNameEn: 'Afaq Tech Authorized Store',
        quantity: 1,
        unitPrice: 14999,
        selectedVariants: { 'اللون': 'أسود فلكي (Space Black)', 'الذاكرة': '48GB / 1TB SSD' },
      },
    ],
    address: INITIAL_USERS[4].addresses[0],
    deliverySpeed: 'express',
    paymentMethod: 'mada',
    paymentReference: 'MADA-TX-6619204',
    subtotal: 14999,
    discountAmount: 500,
    couponCode: 'RIYADH20',
    shippingFee: 0,
    vatAmount: 1891.17,
    total: 14499,
    status: 'shipped',
    trackingNumber: 'DHL-55201948SA',
    carrierAr: 'دي إتش إل إكسبريس',
    carrierEn: 'DHL Express KSA',
    timeline: buildOrderTimeline('shipped', '2026-09-26'),
    createdAt: '2026-09-25T19:00:00Z',
    updatedAt: '2026-09-26T15:30:00Z',
  },
  {
    id: 'ord-98275',
    orderNumber: 'ATH-98275',
    customerId: 'user-customer-1',
    customerName: 'فيصل بن عبدالعزيز الراجحي',
    customerEmail: 'customer@atheel.sa',
    customerPhone: '+966 50 511 9988',
    sellerIds: ['seller-4'],
    productIds: ['prod-25'],
    items: [
      {
        productId: 'prod-25',
        sku: 'ATH-MEN-001',
        titleAr: 'بشت ملكي حساوي صوف وبر طبيعي مطرز بزري ألماني مذهّب عيار ٢٤ - صناعة يدوية',
        titleEn: 'Royal Hasawi Bisht with 24K Gold-Plated German Zari Embroidery - Handwoven',
        image: 'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=800&q=85',
        sellerId: 'seller-4',
        sellerNameAr: 'أتيليه نجد للأزياء والعبايات',
        sellerNameEn: 'Najd Couture & Royal Attire',
        quantity: 1,
        unitPrice: 3850,
        selectedVariants: { 'اللون': 'أسود ملكي', 'المقاس (الطول)': '58 إنش' },
      },
    ],
    address: INITIAL_USERS[0].addresses[0],
    deliverySpeed: 'standard',
    paymentMethod: 'mada',
    paymentReference: 'MADA-TX-3310982',
    subtotal: 3850,
    discountAmount: 0,
    shippingFee: 0,
    vatAmount: 502.17,
    total: 3850,
    status: 'return_requested',
    trackingNumber: 'SPL-33109482SA',
    carrierAr: 'سبل إكسبريس VIP',
    carrierEn: 'SPL Express VIP',
    timeline: buildOrderTimeline('return_requested', '2026-09-14'),
    returnRequest: {
      reasonAr: 'المقاس غير مناسب وأرغب باستبداله بمقاس 60 إنش أو استرداد المبلغ للمحفظة',
      reasonEn: 'Size 58 does not fit perfectly; requesting return credit to wallet for size 60',
      details: 'المنتج بحالته الأصلية تماماً داخل الصندوق المخملي مع الأختام كاملة.',
      refundMethod: 'wallet',
      requestedAt: '2026-09-16T12:00:00Z',
      status: 'pending',
    },
    createdAt: '2026-09-11T11:00:00Z',
    updatedAt: '2026-09-16T12:00:00Z',
  },
  {
    id: 'ord-98560',
    orderNumber: 'ATH-98560',
    customerId: 'user-customer-2',
    customerName: 'سارة بنت خالد العليان',
    customerEmail: 'sara.olayan@example.sa',
    customerPhone: '+966 54 321 7766',
    sellerIds: ['seller-2'],
    productIds: ['prod-10', 'prod-14'],
    items: [
      {
        productId: 'prod-10',
        sku: 'ATH-MOB-002',
        titleAr: 'هاتف سامسونج جالكسي S24 ألترا ٥١٢ جيجابايت - تيتانيوم رمادي (نسخة الشرق الأوسط)',
        titleEn: 'Samsung Galaxy S24 Ultra 512GB - Titanium Gray (Official ME Version)',
        image: 'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=800&q=85',
        sellerId: 'seller-2',
        sellerNameAr: 'آفاق التقنية المعتمدة',
        sellerNameEn: 'Afaq Tech Authorized Store',
        quantity: 1,
        unitPrice: 4899,
        selectedVariants: { 'اللون': 'تيتانيوم رمادي', 'السعة': '512 GB' },
      },
      {
        productId: 'prod-14',
        sku: 'ATH-AUD-002',
        titleAr: 'سماعة أبل إيربودز برو الجيل الثاني بمنفذ USB-C مع علبة شحن ماج سيف',
        titleEn: 'Apple AirPods Pro (2nd Gen) with MagSafe Charging Case (USB-C)',
        image: 'https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?auto=format&fit=crop&w=800&q=85',
        sellerId: 'seller-2',
        sellerNameAr: 'آفاق التقنية المعتمدة',
        sellerNameEn: 'Afaq Tech Authorized Store',
        quantity: 2,
        unitPrice: 949,
        selectedVariants: { 'الإصدار': 'USB-C MagSafe' },
      },
    ],
    address: INITIAL_USERS[3].addresses[0],
    deliverySpeed: 'express',
    paymentMethod: 'apple_pay',
    paymentReference: 'APAY-SA-7741902',
    subtotal: 6797,
    discountAmount: 300,
    couponCode: 'AFAQVIP300',
    shippingFee: 0,
    vatAmount: 847.43,
    total: 6497,
    status: 'placed',
    trackingNumber: 'SPL-99812034SA',
    carrierAr: 'سبل إكسبريس VIP',
    carrierEn: 'SPL Express VIP',
    timeline: buildOrderTimeline('placed', '2026-09-27'),
    createdAt: '2026-09-27T16:40:00Z',
    updatedAt: '2026-09-27T16:40:00Z',
  },
  {
    id: 'ord-98395',
    orderNumber: 'ATH-98395',
    customerId: 'user-customer-1',
    customerName: 'فيصل بن عبدالعزيز الراجحي',
    customerEmail: 'customer@atheel.sa',
    customerPhone: '+966 50 511 9988',
    sellerIds: ['seller-2'],
    productIds: ['prod-18', 'prod-15'],
    items: [
      {
        productId: 'prod-18',
        sku: 'ATH-CMP-002',
        titleAr: 'جهاز أبل آيباد برو ١٣ إنش شريحة M4 شاشة OLED ألترا ريتينا سعة ٥١٢ جيجابايت Wi-Fi + 5G',
        titleEn: 'Apple iPad Pro 13" M4 Ultra Retina XDR OLED 512GB Wi-Fi + 5G - Space Black',
        image: 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=85',
        sellerId: 'seller-2',
        sellerNameAr: 'آفاق التقنية المعتمدة',
        sellerNameEn: 'Afaq Tech Authorized Store',
        quantity: 1,
        unitPrice: 6299,
        selectedVariants: { 'اللون': 'أسود فلكي', 'الاتصال': 'Wi-Fi + 5G' },
      },
      {
        productId: 'prod-15',
        sku: 'ATH-AUD-003',
        titleAr: 'مكبر صوت بانج آند أولفسن Beosound A5 المحمول بالخشب الطبيعي والألمنيوم الدنماركي',
        titleEn: 'Bang & Olufsen Beosound A5 Portable Wireless Speaker - Nordic Weave',
        image: 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=85',
        sellerId: 'seller-2',
        sellerNameAr: 'آفاق التقنية المعتمدة',
        sellerNameEn: 'Afaq Tech Authorized Store',
        quantity: 1,
        unitPrice: 4490,
        selectedVariants: { 'التشطيب': 'خشب البلوط الإسكندنافي' },
      },
    ],
    address: INITIAL_USERS[0].addresses[1],
    deliverySpeed: 'express',
    paymentMethod: 'mada',
    paymentReference: 'MADA-TX-5529108',
    subtotal: 10789,
    discountAmount: 350,
    couponCode: 'AFAQ10',
    shippingFee: 0,
    vatAmount: 1361.61,
    total: 10439,
    status: 'delivered',
    trackingNumber: 'ARMX-66381920SA',
    carrierAr: 'أرامكس بريميوم',
    carrierEn: 'Aramex Premium',
    timeline: buildOrderTimeline('delivered', '2026-09-21'),
    createdAt: '2026-09-19T11:20:00Z',
    updatedAt: '2026-09-21T17:45:00Z',
  },
  {
    id: 'ord-98340',
    orderNumber: 'ATH-98340',
    customerId: 'user-customer-3',
    customerName: 'فهد بن محمد الدوسري',
    customerEmail: 'fahad.dosari@example.sa',
    customerPhone: '+966 56 889 4411',
    sellerIds: ['seller-2'],
    productIds: ['prod-16'],
    items: [
      {
        productId: 'prod-16',
        sku: 'ATH-AUD-004',
        titleAr: 'سماعة الرأس أبل إيربودز ماكس الفاخرة من الألمنيوم المؤكسد - سماء الليل (Midnight)',
        titleEn: 'Apple AirPods Max Over-Ear Luxury Headphones - Midnight Aluminum',
        image: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=800&q=85',
        sellerId: 'seller-2',
        sellerNameAr: 'آفاق التقنية المعتمدة',
        sellerNameEn: 'Afaq Tech Authorized Store',
        quantity: 1,
        unitPrice: 2399,
        selectedVariants: { 'اللون': 'سماء الليل (Midnight)' },
      },
    ],
    address: INITIAL_USERS[4].addresses[0],
    deliverySpeed: 'standard',
    paymentMethod: 'visa_mastercard',
    paymentReference: 'VISA-9910-3321',
    subtotal: 2399,
    discountAmount: 0,
    shippingFee: 0,
    vatAmount: 312.91,
    total: 2399,
    status: 'return_requested',
    trackingNumber: 'SMSA-44109283SA',
    carrierAr: 'سمسا إكسبريس',
    carrierEn: 'SMSA Express',
    timeline: buildOrderTimeline('return_requested', '2026-09-17'),
    returnRequest: {
      reasonAr: 'رغبة في الاستبدال باللون الفضي النجمي (Starlight) والمنتج بغلاف المصنع الأصلي غير المفتوح',
      reasonEn: 'Customer wishes to exchange for Starlight color; factory shrink-wrap is intact and unopened',
      details: 'لم يتم فتح الغلاف البلاستيكي الخارجي نهائياً والرقم التسلسلي مطابق للفاتورة الضريبية.',
      refundMethod: 'wallet',
      requestedAt: '2026-09-24T14:15:00Z',
      status: 'pending',
    },
    createdAt: '2026-09-15T09:30:00Z',
    updatedAt: '2026-09-24T14:15:00Z',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-1',
    productTitleAr: 'ساعة أورولوجيا جنيف كرونوغراف أوتوماتيك - إصدار الدرعية الملكي',
    productTitleEn: 'Horologia Genève Automatic Chronograph - Diriyah Royal Edition',
    userId: 'user-customer-1',
    userName: 'فيصل بن عبدالعزيز الراجحي',
    rating: 5,
    title: 'تحفة فنية سويسرية وتغليف ملكي يليق بالإهداء',
    comment:
      'وصلت الساعة خلال أقل من ٢٤ ساعة في الرياض داخل صندوق خشبي فاخر مع بطاقة الضمان الدولي المختومة. لون الميناء الأخضر الزمردي على الطبيعة أجمل بمراحل من الصور.',
    verifiedPurchase: true,
    verifiedOrderId: 'ord-98421',
    helpfulCount: 38,
    createdAt: '2026-09-23',
    status: 'approved',
  },
  {
    id: 'rev-2',
    productId: 'prod-5',
    productTitleAr: 'دهن عود كمبودي ملكي معتّق نادر - توله كاملة',
    productTitleEn: 'Rare Aged Royal Cambodian Oud Oil - Full Tola',
    userId: 'user-customer-1',
    userName: 'فيصل بن عبدالعزيز الراجحي',
    rating: 5,
    title: 'ثبات وفوحان يفوق الوصف.. دهن صافي ١٠٠٪',
    comment:
      'من أنقى أنواع الدهن الكمبودي المعتّق التي جربتها. رائحة سويتية بخورية فخمة جداً للمناسبات الرسمية وتثبت على الشماغ والبشت لأكثر من يومين.',
    verifiedPurchase: true,
    verifiedOrderId: 'ord-98421',
    helpfulCount: 54,
    createdAt: '2026-09-23',
    status: 'approved',
  },
  {
    id: 'rev-3',
    productId: 'prod-9',
    productTitleAr: 'هاتف آيفون ١٦ برو ماكس سعة ٥١٢ جيجابايت - تيتانيوم صحراوي',
    productTitleEn: 'iPhone 16 Pro Max 512GB - Desert Titanium',
    userId: 'user-customer-3',
    userName: 'فهد بن محمد الدوسري',
    rating: 5,
    title: 'نسخة الشرق الأوسط الرسمية وتوصيل سريع للخبر',
    comment:
      'الجهاز أصلي بضمان حاسبات العرب سنتين، واللون التيتانيوم الصحراوي فخم جداً. أشكر متجر آفاق التقنية على سرعة التجهيز والتغليف المحكم.',
    verifiedPurchase: true,
    helpfulCount: 29,
    createdAt: '2026-09-24',
    status: 'approved',
  },
  {
    id: 'rev-4',
    productId: 'prod-21',
    productTitleAr: 'ماكينة إسبريسو بريفيل أوراكل تاتش الاحترافية',
    productTitleEn: 'Breville Oracle Touch Dual Boiler Espresso Machine',
    userId: 'user-customer-2',
    userName: 'سارة بنت خالد العليان',
    rating: 5,
    title: 'حولت ركن القهوة في منزلي إلى كافيه مختص حقيقي',
    comment:
      'الطحن والكبس والتبخير الأوتوماتيكي دقيق جداً، والشاشة اللمسية سهلة الاستخدام. متجر رواق القهوة أرفق معها محصول بن إثيوبي مختص هدية.',
    verifiedPurchase: true,
    helpfulCount: 41,
    createdAt: '2026-09-19',
    status: 'approved',
  },
  {
    id: 'rev-5',
    productId: 'prod-29',
    productTitleAr: 'عباية كوتور نجدي من الحرير الياباني الطبيعي',
    productTitleEn: 'Najdi Couture Natural Japanese Silk Abaya',
    userId: 'user-customer-2',
    userName: 'سارة بنت خالد العليان',
    rating: 5,
    title: 'خامة الحرير والتطريز اليدوي قمة في الرقي',
    comment:
      'القصة انسيابية جداً والخياطة متقنة لأبعد حد. وصلت العباية معطرة ومغلفة في حافظة قماشية فاخرة مع طرحة مطابقة.',
    verifiedPurchase: true,
    verifiedOrderId: 'ord-98310',
    helpfulCount: 33,
    createdAt: '2026-09-19',
    status: 'approved',
  },
  {
    id: 'rev-6',
    productId: 'prod-33',
    productTitleAr: 'جهاز تصفيف الشعر دايسون إير راب ملتي ستايلر كومبليت لونج',
    productTitleEn: 'Dyson Airwrap Multi-Styler Complete Long',
    userId: 'user-customer-2',
    userName: 'سارة بنت خالد العليان',
    rating: 4,
    title: 'نتائج صالون في ١٥ دقيقة بدون حرارة عالية',
    comment:
      'النسخة أصلية بفيش ثلاثي سعودي وضمان سنتين. الملحقات الجديدة تختصر الوقت بشكل رائع.',
    verifiedPurchase: true,
    verifiedOrderId: 'ord-98310',
    helpfulCount: 19,
    createdAt: '2026-09-20',
    status: 'approved',
  },
  {
    id: 'rev-7',
    productId: 'prod-18',
    productTitleAr: 'جهاز أبل آيباد برو ١٣ إنش شريحة M4 شاشة OLED ألترا ريتينا',
    productTitleEn: 'Apple iPad Pro 13" M4 Ultra Retina XDR OLED',
    userId: 'user-customer-1',
    userName: 'فيصل بن عبدالعزيز الراجحي',
    rating: 5,
    title: 'شاشة OLED خيالية وأداء يتفوق على كثير من الحواسيب المحمولة',
    comment:
      'نحافة الجهاز مذهلة مع معالج M4 السريع جداً. وصلني من متجر آفاق التقنية مع فاتورة ضريبية رسمية وتغليف محكم خلال أقل من يوم.',
    verifiedPurchase: true,
    verifiedOrderId: 'ord-98395',
    helpfulCount: 24,
    createdAt: '2026-09-25',
    status: 'approved',
    sellerReplyAr: 'نتشرف بخدمتكم دائماً أستاذ فيصل في متجر آفاق التقنية المعتمدة، ونتمنى لكم تجربة استثنائية مع آيباد برو M4.',
    sellerReplyEn: 'Always honored to serve you at Afaq Tech Authorized Store! Enjoy your new iPad Pro M4.',
    sellerReplyAt: '2026-09-25',
  },
  {
    id: 'rev-8',
    productId: 'prod-13',
    productTitleAr: 'سماعة سوني اللاسلكية WH-1000XM5 العازلة للضجيج',
    productTitleEn: 'Sony WH-1000XM5 Wireless Noise Canceling Headphones',
    userId: 'user-customer-2',
    userName: 'سارة بنت خالد العليان',
    rating: 4,
    title: 'عزل الضجيج ممتاز جداً في رحلات الطيران الطويلة',
    comment:
      'السماعة مريحة جداً على الأذن لساعات طويلة وجودة الميكروفون في الاجتماعات واضحة، كنت أتمنى فقط لو كانت تطوى بالكامل مثل الجيل السابق.',
    verifiedPurchase: true,
    helpfulCount: 15,
    createdAt: '2026-09-26',
    status: 'approved',
  },
  {
    id: 'rev-9',
    productId: 'prod-25',
    productTitleAr: 'بشت ملكي حساوي صوف وبر طبيعي مطرز بزري ألماني مذهّب عيار ٢٤',
    productTitleEn: 'Royal Hasawi Bisht with 24K Gold-Plated German Zari Embroidery',
    userId: 'user-customer-1',
    userName: 'فيصل بن عبدالعزيز الراجحي',
    rating: 5,
    title: 'حياكة حساوية أصيلة وزري ملكي فاخر، ولكن أحتاج مقاساً أكبر',
    comment:
      'جودة الصوف والزري الألماني لا يعلى عليها ومطابقة تماماً للمواصفات الملكية، قمت بطلب استبدال المقاس إلى ٦٠ إنش.',
    verifiedPurchase: true,
    verifiedOrderId: 'ord-98275',
    helpfulCount: 8,
    createdAt: '2026-09-27',
    status: 'pending',
  },
];

export const INITIAL_QUESTIONS: ProductQuestion[] = [
  {
    id: 'qa-1',
    productId: 'prod-1',
    userName: 'عبدالعزيز السبيعي',
    questionAr: 'هل تأتي الساعة مع شهادة الضمان الدولي المختومة وصندوق الإهداء الرسمي؟',
    questionEn: 'Does the timepiece come with the stamped international warranty card and official presentation box?',
    answerAr:
      'أهلاً بك أستاذ عبدالعزيز، نعم بكل تأكيد. جميع ساعات قصر الساعات السويسرية تأتي في صندوقها الخشبي الأصلي مع بطاقة الضمان الدولي الفعالة لمدة ٥ سنوات وشهادة فحص الأصالة المعتمدة.',
    answerEn:
      'Yes, every timepiece from Swiss Horology Palace includes the original wooden presentation box, 5-year active international warranty card, and certificate of authenticity.',
    answeredByAr: 'قصر الساعات السويسرية (تاجر معتمد)',
    answeredByEn: 'Swiss Horology Palace (Verified Boutique)',
    createdAt: '2026-09-18',
  },
  {
    id: 'qa-2',
    productId: 'prod-9',
    userName: 'ماجد الحربي',
    questionAr: 'هل الجوال نسخة الشرق الأوسط الرسمية ويدعم فيس تايم وشريحتين (Nano + eSIM)؟',
    questionEn: 'Is this the official Middle East version supporting FaceTime and Dual SIM (Nano + eSIM)?',
    answerAr:
      'حياك الله أستاذ ماجد، نعم النسخة رسمية مخصصة للسوق السعودي (حاسبات العرب)، تدعم تطبيق فيس تايم بالكامل وتشغيل شريحة فعلية Nano-SIM بالإضافة إلى شريحة إلكترونية eSIM مع ضمان ٢٤ شهراً.',
    answerEn:
      'Yes, it is the official Saudi/ME version (Arab Computers warranty), fully supporting FaceTime, Nano-SIM + eSIM, and covered by a 24-month official warranty.',
    answeredByAr: 'آفاق التقنية المعتمدة',
    answeredByEn: 'Afaq Tech Authorized Store',
    createdAt: '2026-09-21',
  },
  {
    id: 'qa-3',
    productId: 'prod-5',
    userName: 'سلطان العجمي',
    questionAr: 'هل دهن العود صافي بيور ١٠٠٪ بدون أي إضافات أو تخفيف؟',
    questionEn: 'Is the Cambodian Oud oil 100% pure artisanal distillation without dilution?',
    answerAr:
      'نعم طال عمرك، دهن عود كمبودي بيور ١٠٠٪ تقطير قديم معتّق لأكثر من ٨ سنوات، خالٍ تماماً من أي إضافات أو مخلطات، ومشمول بالضمان الذهبي للاسترجاع لو لم يناسب ذائقتك.',
    answerEn:
      'Yes, it is 100% pure single-origin Cambodian agarwood oil aged over 8 years with zero additives, backed by our Golden Satisfaction Guarantee.',
    answeredByAr: 'دار العود والطيب الملكي',
    answeredByEn: 'Dar Al-Oud Royal Perfumery',
    createdAt: '2026-09-19',
  },
  {
    id: 'qa-4',
    productId: 'prod-17',
    userName: 'تركي بن فهد السديري',
    questionAr: 'هل لوحة المفاتيح في ماك بوك برو ١٦ إنش تأتي بحروف عربية وإنجليزية محفورة رسمياً من المصنع (لوحة مفاتيح الشرق الأوسط)؟',
    questionEn: 'Does the MacBook Pro 16" come with the factory-engraved Arabic/English bilingual keyboard (official Middle East layout)?',
    createdAt: '2026-09-27',
  },
  {
    id: 'qa-5',
    productId: 'prod-13',
    userName: 'ريم بنت عبدالله التميمي',
    questionAr: 'هل السماعة تدعم الاقتران بجهازين في نفس الوقت (Multipoint Bluetooth) بين الآيفون والماك بوك؟',
    questionEn: 'Does this headphone support Multipoint Bluetooth connection to pair with both iPhone and MacBook simultaneously?',
    createdAt: '2026-09-27',
  },
  {
    id: 'qa-6',
    productId: 'prod-6',
    userName: 'نواف بن خالد الشمري',
    questionAr: 'كم جرام وزن كسرات العود الموروكي السوبر في الصندوق الملكي وهل يناسب تبخير المجالس الكبيرة؟',
    questionEn: 'What is the exact weight in grams of the Super Moroccan Oud chips in the royal box, and is it suitable for large majlis halls?',
    createdAt: '2026-09-26',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'all',
    type: 'shipping',
    titleAr: 'الشحنة #ATH-98504 خرجت للتوصيل 🚚',
    titleEn: 'Order #ATH-98504 is Out for Delivery 🚚',
    messageAr: 'مندوب أرامكس بريميوم في طريقه إلى عنوانك في حي حطين - الرياض. كود الاستلام: 4829',
    messageEn: 'Aramex Premium courier is en route to your Hittin, Riyadh address. Delivery PIN: 4829',
    read: false,
    linkView: 'orders',
    createdAt: 'منذ ٢٠ دقيقة',
  },
  {
    id: 'notif-2',
    userId: 'all',
    type: 'promo',
    titleAr: 'عروض الفخامة الخاطفة بدأت الآن ⚡',
    titleEn: 'Luxury Flash Deals Are Live Now ⚡',
    messageAr: 'استخدم الكوبون ATHEEL15 للحصول على خصم إضافي ١٥٪ على الساعات والعطور والأجهزة الذكية.',
    messageEn: 'Use code ATHEEL15 for an extra 15% privilege on watches, royal oud, and flagship electronics.',
    read: false,
    linkView: 'search',
    createdAt: 'منذ ساعتين',
  },
  {
    id: 'notif-3',
    userId: 'all',
    type: 'order',
    titleAr: 'تمت إضافة ١,٨٥٠ نقطة ولاء إلى محفظتك ✨',
    titleEn: '1,850 Loyalty Points Credited to Your Account ✨',
    messageAr: 'شكراً لتسوقك في أثيل! يمكنك استبدال نقاطك برصيد فوري في طلباتك القادمة.',
    messageEn: 'Thank you for shopping at Atheel! Redeem your points for instant SAR credit on future orders.',
    read: true,
    linkView: 'account',
    createdAt: 'أمس',
  },
];

export const INITIAL_TICKETS: SupportTicket[] = [
  {
    id: 'tkt-1',
    ticketNumber: 'TKT-4091',
    userId: 'user-customer-1',
    userName: 'فيصل بن عبدالعزيز الراجحي',
    userEmail: 'customer@atheel.sa',
    categoryAr: 'استفسار عن الشحن السريع VIP',
    categoryEn: 'VIP Express Shipping Inquiry',
    subject: 'تحديد موعد توصيل مسائي للطلب ATH-98539',
    message: 'أرجو التنسيق مع شركة الشحن ليكون التوصيل بعد الساعة ٦ مساءً للعنوان المسجل.',
    orderNumber: 'ATH-98539',
    status: 'resolved',
    createdAt: '2026-09-26',
    replyAr: 'تم التنسيق مع شركة سمسا إكسبريس وتثبيت الفترة المسائية (٦:٠٠م - ٩:٠٠م) حسب رغبتكم.',
    replyEn: 'Coordinated with SMSA Express to confirm your evening delivery slot (6:00 PM - 9:00 PM).',
    repliedAt: '2026-09-26',
  },
  {
    id: 'tkt-2',
    ticketNumber: 'TKT-4105',
    userId: 'user-customer-2',
    userName: 'سارة بنت خالد العليان',
    userEmail: 'sara.olayan@example.sa',
    categoryAr: 'الفواتير الضريبية',
    categoryEn: 'Tax Invoices & VAT',
    subject: 'طلب نسخة PDF من الفاتورة الضريبية للطلب ATH-98310',
    message: 'أرغب بالحصول على الفاتورة الضريبية المتوافقة مع هيئة الزكاة والضريبة والجمارك ZATCA.',
    orderNumber: 'ATH-98310',
    status: 'open',
    createdAt: '2026-09-27',
  },
  {
    id: 'tkt-3',
    ticketNumber: 'PAY-8420',
    userId: 'user-seller-1',
    userName: 'سلمان بن عبدالعزيز العتيبي (آفاق التقنية المعتمدة)',
    userEmail: 'seller@atheel.sa',
    categoryAr: 'تسوية الأرباح والتحويلات البنكية (سار)',
    categoryEn: 'Merchant Payout Settlement (SARIE)',
    subject: 'طلب تحويل أرباح متجر (آفاق التقنية المعتمدة) بمبلغ 45,000 ر.س',
    message:
      'طلب تسوية رصيد متاح بقيمة 45,000 ر.س إلى الحساب البنكي المعتمد (SA89 **** **** **** **** 1234) عبر نظام سار للتحويلات الفورية.',
    sellerId: 'seller-2',
    payoutAmount: 45000,
    status: 'in_progress',
    createdAt: '2026-09-27',
  },
  {
    id: 'tkt-4',
    ticketNumber: 'RET-7190',
    userId: 'user-seller-1',
    userName: 'سلمان بن عبدالعزيز العتيبي (آفاق التقنية المعتمدة)',
    userEmail: 'seller@atheel.sa',
    categoryAr: 'توصية فحص مرتجعات التاجر',
    categoryEn: 'Merchant Return Inspection Report',
    subject: 'تقرير فحص مرتجع الطلب #ATH-98340 (approve_restock)',
    message:
      'تم التحقق من الرقم التسلسلي لسماعة AirPods Max وأن الغلاف المصنعي غير مفتوح؛ نوصي بالموافقة على الإرجاع وإعادة القطعة للمخزون.',
    orderNumber: 'ATH-98340',
    sellerId: 'seller-2',
    returnRecommendation: 'approve_restock',
    status: 'open',
    createdAt: '2026-09-27',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'log-1',
    actorName: 'نورة القحطاني (Admin)',
    actorRole: 'admin',
    actionAr: 'اعتماد وتوثيق السجل التجاري لمتجر «رواق القهوة والمنزل الفاخر» وتفعيل شارة التاجر الموثوق',
    actionEn: 'Verified CR & VAT registration for "Rawaq Specialty Coffee" and granted Verified Boutique badge',
    targetType: 'seller',
    targetId: 'seller-5',
    createdAt: '2026-09-27 11:40',
  },
  {
    id: 'log-2',
    actorName: 'نورة القحطاني (Admin)',
    actorRole: 'admin',
    actionAr: 'تفعيل حملة عروض الموسم الفاخرة وتحديث بنر الصفحة الرئيسية',
    actionEn: 'Activated Autumn Luxury Flash Campaign and updated Homepage Hero Banner',
    targetType: 'homepage',
    targetId: 'homepage-main',
    createdAt: '2026-09-27 09:15',
  },
  {
    id: 'log-3',
    actorName: 'سلمان العتيبي (Seller)',
    actorRole: 'seller',
    actionAr: 'تحديث مخزون منتج «هاتف آيفون ١٦ برو ماكس ٥١٢ جيجابايت» إلى ٤٢ قطعة وتحديث حالة الطلب #ATH-98504',
    actionEn: 'Updated stock for "iPhone 16 Pro Max 512GB" to 42 units and advanced Order #ATH-98504',
    targetType: 'product',
    targetId: 'prod-9',
    createdAt: '2026-09-26 18:20',
  },
  {
    id: 'log-4',
    actorName: 'نورة القحطاني (Admin)',
    actorRole: 'admin',
    actionAr: 'إصدار كوبون الخصم الموسمي RIYADH20 بنسبة ٢٠٪ لجميع العملاء',
    actionEn: 'Published seasonal discount coupon RIYADH20 (20% off orders 1,000+ SAR)',
    targetType: 'coupon',
    targetId: 'cpn-3',
    createdAt: '2026-09-25 14:00',
  },
];
