import { Product } from './types';

export const SEED_PRODUCTS_PART_A: Product[] = [
  // 1-4: WATCHES & ACCESSORIES (seller-3: قصر الساعات السويسرية)
  {
    id: 'prod-1',
    sku: 'ATH-WTC-001',
    titleAr: 'ساعة أورولوجيا جنيف كرونوغراف أوتوماتيك - إصدار الدرعية الملكي بميناء زمردي',
    titleEn: 'Horologia Genève Automatic Chronograph - Diriyah Royal Emerald Dial',
    descriptionAr:
      'ساعة سويسرية أوتوماتيكية فاخرة مصممة خصيصاً لإصدار الدرعية الملكي. تتميز بميناء أخضر زمردي مشع مع مؤشرات مطلية بالذهب عيار ١٨ قيراطاً، وزجاج ياقوتي (Sapphire) مقاوم للخدش، وحركة أوتوماتيكية سويسرية عالية الدقة باحتياطي طاقة ٧٢ ساعة.',
    descriptionEn:
      'Swiss-made luxury automatic chronograph crafted for the Diriyah Royal Edition. Features a sunray emerald dial with 18K gold-applied indices, scratch-resistant sapphire crystal, and a 72-hour power reserve caliber.',
    categoryId: 'watches',
    subcategoryAr: 'ساعات سويسرية فاخرة',
    subcategoryEn: 'Swiss Luxury Watches',
    brandId: 'brand-geneva',
    brandNameAr: 'أورولوجيا جنيف',
    brandNameEn: 'Horologia Genève',
    sellerId: 'seller-3',
    sellerNameAr: 'قصر الساعات السويسرية',
    sellerNameEn: 'Swiss Horology Palace',
    sellerRating: 4.95,
    sellerVerified: true,
    price: 6450,
    originalPrice: 7900,
    discountPercent: 18,
    stock: 9,
    lowStockThreshold: 3,
    status: 'active',
    rating: 4.9,
    reviewCount: 84,
    soldCount: 142,
    images: [
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'dial-color',
        nameAr: 'لون الميناء',
        nameEn: 'Dial Color',
        type: 'color',
        options: [
          { id: 'emr', labelAr: 'أخضر زمردي ملكي', labelEn: 'Royal Emerald', value: 'emerald', colorHex: '#0B4F3F', inStock: true },
          { id: 'obs', labelAr: 'أسود أوبسيديان', labelEn: 'Obsidian Black', value: 'black', colorHex: '#141413', inStock: true },
          { id: 'chm', labelAr: 'ذهبي شامبين', labelEn: 'Champagne Gold', value: 'gold', colorHex: '#C59B27', priceDelta: 350, inStock: true },
        ],
      },
      {
        id: 'case-size',
        nameAr: 'مقاس القطر',
        nameEn: 'Case Diameter',
        type: 'size',
        options: [
          { id: '41mm', labelAr: '41 مم (كلاسيك)', labelEn: '41 mm Classic', value: '41mm', inStock: true },
          { id: '43mm', labelAr: '43 مم (رويال)', labelEn: '43 mm Royal', value: '43mm', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'بلد الصنع', keyEn: 'Origin', valueAr: 'جنيف - سويسرا (Swiss Made)', valueEn: 'Geneva, Switzerland' },
      { keyAr: 'نوع الحركة', keyEn: 'Movement', valueAr: 'أوتوماتيكية سويسرية Calibre HG-88', valueEn: 'Swiss Automatic Calibre HG-88' },
      { keyAr: 'الزجاج', keyEn: 'Crystal', valueAr: 'ياقوت أزرق مقاوم للخدش والانعكاس', valueEn: 'Anti-reflective Sapphire Crystal' },
      { keyAr: 'مقاومة الماء', keyEn: 'Water Resistance', valueAr: '١٠٠ متر (10 ATM)', valueEn: '100 Meters (10 ATM)' },
    ],
    warrantyAr: 'ضمان دولي معتمد لمدة ٥ سنوات شامل الصيانة لدى قصر الساعات السويسرية',
    warrantyEn: '5-Year Certified International Warranty with complimentary boutique servicing',
    deliveryEstimateAr: 'توصيل VIP مؤمّن خلال ٢٤ ساعة في الرياض وجدة',
    deliveryEstimateEn: 'Insured VIP Courier within 24 hours in Riyadh & Jeddah',
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-05T23:59:59Z',
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    frequentlyBoughtWith: ['prod-2', 'prod-3'],
    createdAt: '2026-08-10',
  },
  {
    id: 'prod-2',
    sku: 'ATH-WTC-002',
    titleAr: 'ساعة نسائية مرصعة بالألماس الطبيعي والصدف اللؤلؤي - ذهب وردي عيار ١٨',
    titleEn: 'Lumière Genève Ladies Mother-of-Pearl & Natural Diamond Watch - 18K Rose Gold',
    descriptionAr:
      'تحفة أنثوية راقية تجمع بين إطار مرصع بـ ٣٦ ماسة طبيعية معتمدة وميناء من عرق اللؤلؤ الطبيعي. سوار ناعم من الفولاذ المصقول والذهب الوردي يناسب أرقى المناسبات والسهرات.',
    descriptionEn:
      'Exquisite feminine timepiece combining a bezel set with 36 certified natural diamonds and a genuine Mother-of-Pearl dial on a two-tone rose gold bracelet.',
    categoryId: 'watches',
    subcategoryAr: 'ساعات نسائية مرصعة',
    subcategoryEn: 'Women Diamond Watches',
    brandId: 'brand-geneva',
    brandNameAr: 'أورولوجيا جنيف',
    brandNameEn: 'Horologia Genève',
    sellerId: 'seller-3',
    sellerNameAr: 'قصر الساعات السويسرية',
    sellerNameEn: 'Swiss Horology Palace',
    sellerRating: 4.95,
    sellerVerified: true,
    price: 8900,
    originalPrice: 10500,
    discountPercent: 15,
    stock: 6,
    lowStockThreshold: 2,
    status: 'active',
    rating: 5.0,
    reviewCount: 47,
    soldCount: 68,
    images: [
      'https://images.unsplash.com/photo-1547996160-81dfa63595aa?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'size',
        nameAr: 'المقاس',
        nameEn: 'Case Size',
        type: 'size',
        options: [
          { id: '28mm', labelAr: '28 مم (ناعم)', labelEn: '28 mm Petite', value: '28mm', inStock: true },
          { id: '32mm', labelAr: '32 مم (كلاسيك)', labelEn: '32 mm Classic', value: '32mm', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'الأحجار الكريمة', keyEn: 'Gemstones', valueAr: '٣٦ ماسة طبيعية بنقاء VS1 (٠.٤٨ قيراط)', valueEn: '36 VS1 Natural Diamonds (0.48 ct)' },
      { keyAr: 'الميناء', keyEn: 'Dial', valueAr: 'صدف لؤلؤ طبيعي أبيض', valueEn: 'White Natural Mother-of-Pearl' },
      { keyAr: 'بلد الصنع', keyEn: 'Origin', valueAr: 'سويسرا', valueEn: 'Switzerland' },
    ],
    warrantyAr: 'ضمان دولي ٥ سنوات مع شهادة فحص الألماس المعتمدة',
    warrantyEn: '5-Year International Warranty with Diamond Certification',
    deliveryEstimateAr: 'توصيل VIP مجاني خلال ٢٤-٤٨ ساعة',
    deliveryEstimateEn: 'Complimentary VIP delivery in 24-48 hours',
    isFlashDeal: false,
    isFeatured: true,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: true,
    frequentlyBoughtWith: ['prod-1', 'prod-3'],
    createdAt: '2026-09-01',
  },
  {
    id: 'prod-3',
    sku: 'ATH-WTC-003',
    titleAr: 'طقم كبك وقلم ملكي مطلي بالروديوم وحجر الأونيكس الأسود الطبيعي',
    titleEn: 'Royal Rhodium-Plated Cufflinks & Rollerball Pen Set with Black Onyx',
    descriptionAr:
      'طقم إهداء رجالي فاخر يضم كبك ثوب رسمي مرصع بحجر الأونيكس الأسود المصقول وقلم توقيع انسيابي متوازن الوزن داخل علبة جلدية فاخرة.',
    descriptionEn:
      'Executive gift set featuring hand-polished black onyx cufflinks and a precision-balanced rollerball pen presented in a leather box.',
    categoryId: 'watches',
    subcategoryAr: 'كبكات وأقلام فاخرة',
    subcategoryEn: 'Luxury Cufflinks & Pens',
    brandId: 'brand-geneva',
    brandNameAr: 'أورولوجيا جنيف',
    brandNameEn: 'Horologia Genève',
    sellerId: 'seller-3',
    sellerNameAr: 'قصر الساعات السويسرية',
    sellerNameEn: 'Swiss Horology Palace',
    sellerRating: 4.95,
    sellerVerified: true,
    price: 1180,
    originalPrice: 1490,
    discountPercent: 21,
    stock: 24,
    lowStockThreshold: 5,
    status: 'active',
    rating: 4.8,
    reviewCount: 63,
    soldCount: 215,
    images: [
      'https://images.unsplash.com/photo-1585386959984-a4155224a1ad?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'finish',
        nameAr: 'اللون والمعدن',
        nameEn: 'Metal Finish',
        type: 'color',
        options: [
          { id: 'slv', labelAr: 'فضي روديوم وأونيكس أسود', labelEn: 'Silver Rhodium & Onyx', value: 'silver', colorHex: '#57534E', inStock: true },
          { id: 'gld', labelAr: 'ذهبي ملكي وأخضر ملكيت', labelEn: 'Royal Gold & Malachite', value: 'gold', colorHex: '#B8860B', priceDelta: 120, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'المادة', keyEn: 'Material', valueAr: 'فولاذ جراحي مطلي بالروديوم وأحجار طبيعية', valueEn: 'Rhodium-plated Steel & Natural Onyx' },
      { keyAr: 'علبة الإهداء', keyEn: 'Gift Box', valueAr: 'صندوق جلدي فاخر مع كيس إهداء رسمي', valueEn: 'Luxury Leather Box & Gift Bag' },
    ],
    warrantyAr: 'ضمان سنتين على اللون وآلية القلم',
    warrantyEn: '2-Year Warranty on plating and pen mechanism',
    deliveryEstimateAr: 'توصيل خلال ٢٤ ساعة في الرياض',
    deliveryEstimateEn: '24-hour delivery in Riyadh',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-08-18',
  },
  {
    id: 'prod-4',
    sku: 'ATH-WTC-004',
    titleAr: 'ساعة جارمن مارك أدفنتشرر الجيل الثاني من التيتانيوم الدمشقي والياقوت',
    titleEn: 'Garmin MARQ Adventurer (Gen 2) Damascus Steel & Titanium Luxury Tool Watch',
    descriptionAr:
      'ساعة المهام الفاخرة المصنوعة من التيتانيوم من الدرجة الخامسة مع حزام جلد هجين وشاشة AMOLED ساطعة وخرائط طبوغرافية كاملة للمملكة والصحاري.',
    descriptionEn:
      'Modern luxury tool watch forged from Grade-5 titanium with hybrid FKM leather strap, AMOLED display, and full KSA topographic navigation maps.',
    categoryId: 'watches',
    subcategoryAr: 'ساعات كرونوغراف رجالية',
    subcategoryEn: 'Men Chronograph Watches',
    brandId: 'brand-garmin',
    brandNameAr: 'جارمن',
    brandNameEn: 'Garmin',
    sellerId: 'seller-3',
    sellerNameAr: 'قصر الساعات السويسرية',
    sellerNameEn: 'Swiss Horology Palace',
    sellerRating: 4.95,
    sellerVerified: true,
    price: 8250,
    originalPrice: 8990,
    discountPercent: 8,
    stock: 7,
    lowStockThreshold: 2,
    status: 'active',
    rating: 4.9,
    reviewCount: 39,
    soldCount: 54,
    images: [
      'https://images.unsplash.com/photo-1524805444758-089113d48a6d?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'strap',
        nameAr: 'السوار',
        nameEn: 'Strap Edition',
        type: 'option',
        options: [
          { id: 'lth', labelAr: 'جلد بني إيطالي هجين', labelEn: 'chestnut Hybrid Leather', value: 'leather', inStock: true },
          { id: 'tit', labelAr: 'سوار تيتانيوم كامل', labelEn: 'Full Titanium Bracelet', value: 'titanium', priceDelta: 650, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'عمر البطارية', keyEn: 'Battery Life', valueAr: 'حتى ١٦ يوماً في وضع الساعة الذكية', valueEn: 'Up to 16 days in smartwatch mode' },
      { keyAr: 'الخرائط', keyEn: 'Maps', valueAr: 'خرائط الشرق الأوسط والبراري محملة مسبقاً', valueEn: 'Preloaded Middle East TopoActive Maps' },
    ],
    warrantyAr: 'ضمان الوكيل الرسمي دار موجة سنتين',
    warrantyEn: '2-Year Official KSA Distributor Warranty',
    deliveryEstimateAr: 'توصيل مجاني خلال ٢٤-٤٨ ساعة',
    deliveryEstimateEn: 'Free delivery in 24-48 hours',
    isFlashDeal: false,
    isFeatured: true,
    isTrending: true,
    isBestSeller: false,
    isNewArrival: true,
    createdAt: '2026-09-10',
  },

  // 5-8: PERFUMES & ROYAL OUD (seller-1: دار العود والطيب الملكي)
  {
    id: 'prod-5',
    sku: 'ATH-PRF-001',
    titleAr: 'دهن عود كمبودي ملكي معتّق نادر - توله كاملة في صندوق خشب الجوز المصقول',
    titleEn: 'Rare Aged Royal Cambodian Oud Oil - Full Tola (12ml) in Walnut Box',
    descriptionAr:
      'نخبة دهن العود الكمبودي القديم المعتّق لأكثر من ٨ سنوات. يتميز بنكهة بخورية سويتية دافئة وثبات استثنائي يدوم لأيام على الأشمغة والبشوت، خالٍ تماماً من أي إضافات.',
    descriptionEn:
      'Artisanal single-origin Cambodian agarwood oil aged over 8 years. Rich, sweet balsamic depth with extraordinary longevity on fine fabrics. 100% pure distillation.',
    categoryId: 'perfumes',
    subcategoryAr: 'دهن العود والخشب الطبيعي',
    subcategoryEn: 'Pure Oud Oil & Agarwood',
    brandId: 'brand-dar-oud',
    brandNameAr: 'دار الطيب الملكي',
    brandNameEn: 'Dar Al-Teeb Royal',
    sellerId: 'seller-1',
    sellerNameAr: 'دار العود والطيب الملكي',
    sellerNameEn: 'Dar Al-Oud Royal Perfumery',
    sellerRating: 4.9,
    sellerVerified: true,
    price: 1850,
    originalPrice: 2300,
    discountPercent: 20,
    stock: 15,
    lowStockThreshold: 4,
    status: 'active',
    rating: 4.95,
    reviewCount: 168,
    soldCount: 410,
    images: [
      'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'volume',
        nameAr: 'الحجم',
        nameEn: 'Volume',
        type: 'capacity',
        options: [
          { id: 'quarter', labelAr: 'ربع توله (3 مل)', labelEn: 'Quarter Tola (3ml)', value: '3ml', priceDelta: -1250, inStock: true },
          { id: 'half', labelAr: 'نصف توله (6 مل)', labelEn: 'Half Tola (6ml)', value: '6ml', priceDelta: -850, inStock: true },
          { id: 'full', labelAr: 'توله كاملة ملكية (12 مل)', labelEn: 'Full Royal Tola (12ml)', value: '12ml', priceDelta: 0, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'درجة النقاء', keyEn: 'Purity', valueAr: '١٠٠٪ دهن عود طبيعي بيور بدون إضافات', valueEn: '100% Pure Natural Agarwood Oil' },
      { keyAr: 'عمر التعتيق', keyEn: 'Aging Period', valueAr: 'معتّق لأكثر من ٨ سنوات', valueEn: 'Aged 8+ Years' },
      { keyAr: 'التغليف', keyEn: 'Packaging', valueAr: 'زجاجة كريستال محفورة بالذهب داخل صندوق خشب الجوز', valueEn: 'Gold-etched crystal flacon in walnut chest' },
    ],
    warrantyAr: 'الضمان الذهبي لاسترجاع كامل المبلغ خلال ١٤ يوماً في حال عدم الرضا',
    warrantyEn: '14-Day Golden Satisfaction Guarantee',
    deliveryEstimateAr: 'توصيل مبرد ومجاني خلال ٢٤ ساعة',
    deliveryEstimateEn: 'Temperature-controlled free 24h delivery',
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-03T23:59:59Z',
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    isSeasonal: true,
    frequentlyBoughtWith: ['prod-6', 'prod-7'],
    createdAt: '2026-07-15',
  },
  {
    id: 'prod-6',
    sku: 'ATH-PRF-002',
    titleAr: 'عطر ليالي العُلا إكستريت دي بارفيوم ١٠٠ مل - عنبر دخاني وزعفران ملكي',
    titleEn: 'AlUla Nights Extrait de Parfum 100ml - Smoky Amber & Royal Saffron',
    descriptionAr:
      'عطر نيش سعودي بتركيز إكستريت دي بارفيوم (٣٥٪ زيوت عطرية). يفتتح بنفحات الهيل السعودي والزعفران الأحمر، يتوسطه الورد الطائفي الدمشقي، ويستقر على قاعدة ساحرة من العنبر واللبان الحوجري والعود.',
    descriptionEn:
      'Haute perfumery Extrait de Parfum (35% concentration) opening with Saudi cardamom and saffron, blooming into Taif rose over a base of Omani frankincense and aged oud.',
    categoryId: 'perfumes',
    subcategoryAr: 'عطور النيش الفاخرة',
    subcategoryEn: 'Luxury Niche Perfumes',
    brandId: 'brand-dar-oud',
    brandNameAr: 'دار الطيب الملكي',
    brandNameEn: 'Dar Al-Teeb Royal',
    sellerId: 'seller-1',
    sellerNameAr: 'دار العود والطيب الملكي',
    sellerNameEn: 'Dar Al-Oud Royal Perfumery',
    sellerRating: 4.9,
    sellerVerified: true,
    price: 890,
    originalPrice: 1150,
    discountPercent: 23,
    stock: 38,
    lowStockThreshold: 8,
    status: 'active',
    rating: 4.9,
    reviewCount: 215,
    soldCount: 680,
    images: [
      'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'size',
        nameAr: 'الحجم',
        nameEn: 'Bottle Size',
        type: 'capacity',
        options: [
          { id: '100ml', labelAr: '100 مل + عينة تجربة مجانية', labelEn: '100ml + Free Trial Vial', value: '100ml', inStock: true },
          { id: '200ml', labelAr: '200 مل إصدار الكوليكتور', labelEn: '200ml Collector Edition', value: '200ml', priceDelta: 490, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'التركيز العطري', keyEn: 'Concentration', valueAr: 'Extrait de Parfum (٣٥٪)', valueEn: 'Extrait de Parfum (35%)' },
      { keyAr: 'المكونات العليا', keyEn: 'Top Notes', valueAr: 'زعفران، هيل أخضر، برغموت صقلي', valueEn: 'Saffron, Green Cardamom, Bergamot' },
      { keyAr: 'قلب العطر', keyEn: 'Heart Notes', valueAr: 'ورد طائفي، بخور، جلد مدبوغ', valueEn: 'Taif Rose, Incense, Suede Leather' },
    ],
    warrantyAr: 'مرفق عينة تجربة خارجية — يمكنك استرجاع العطر مجاناً قبل فتح العلبة الرئيسية',
    warrantyEn: 'Includes external trial sample — free return if main box remains sealed',
    deliveryEstimateAr: 'توصيل خلال ٢٤ ساعة في الرياض وجدة والدمام',
    deliveryEstimateEn: '24h delivery in Riyadh, Jeddah & Dammam',
    isFlashDeal: false,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    isSeasonal: true,
    createdAt: '2026-09-05',
  },
  {
    id: 'prod-7',
    sku: 'ATH-PRF-003',
    titleAr: 'عود مروكي طبيعي سوبر مرتفع للمناسبات والقصور - أوقتين (٥٦ جرام)',
    titleEn: 'Super Grade Natural Maroke Agarwood Chips - 2 Ounces (56g)',
    descriptionAr:
      'كسرات عود مروكي طبيعي منتقاة يدوياً ومشبعة بالدهن الكثيف، تزبد على الجمر وتنشر دخاناً عطرياً بارداً يملأ المجالس والقصور بعبق الأصالة.',
    descriptionEn:
      'Hand-selected wild Maroke agarwood chips rich in natural resin, producing a cool, long-lasting aromatic smoke ideal for majlis hospitality.',
    categoryId: 'perfumes',
    subcategoryAr: 'المبثوث والمعمول الملكي',
    subcategoryEn: 'Royal Bakhoor & Incense',
    brandId: 'brand-dar-oud',
    brandNameAr: 'دار الطيب الملكي',
    brandNameEn: 'Dar Al-Teeb Royal',
    sellerId: 'seller-1',
    sellerNameAr: 'دار العود والطيب الملكي',
    sellerNameEn: 'Dar Al-Oud Royal Perfumery',
    sellerRating: 4.9,
    sellerVerified: true,
    price: 1240,
    originalPrice: 1550,
    discountPercent: 20,
    stock: 22,
    lowStockThreshold: 5,
    status: 'active',
    rating: 4.85,
    reviewCount: 94,
    soldCount: 310,
    images: [
      'https://images.unsplash.com/photo-1615397349754-cfa2066a298e?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'weight',
        nameAr: 'الوزن',
        nameEn: 'Weight',
        type: 'capacity',
        options: [
          { id: '1oz', labelAr: 'أوقية واحدة (28 جرام)', labelEn: '1 Ounce (28g)', value: '28g', priceDelta: -580, inStock: true },
          { id: '2oz', labelAr: 'أوقتين ملكية (56 جرام)', labelEn: '2 Ounces (56g)', value: '56g', priceDelta: 0, inStock: true },
          { id: 'thmn', labelAr: 'ثمن كيلو (125 جرام)', labelEn: '125 Grams VIP', value: '125g', priceDelta: 1150, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'المصدر', keyEn: 'Source', valueAr: 'غابات آريان الأصلي - إندونيسيا', valueEn: 'Wild Irian Forest, Indonesia' },
      { keyAr: 'الدرجة', keyEn: 'Grade', valueAr: 'سوبر ودبل سوبر منقى من الغراء والرصاص', valueEn: 'Super & Double Super - 100% Clean' },
    ],
    warrantyAr: 'ضمان الاسترجاع المفتوح حتى استهلاك ٣ جرام للتجربة',
    warrantyEn: 'Open trial guarantee up to 3g testing allowance',
    deliveryEstimateAr: 'توصيل مجاني لجميع مدن المملكة',
    deliveryEstimateEn: 'Free KSA-wide delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    isSeasonal: true,
    createdAt: '2026-08-01',
  },
  {
    id: 'prod-8',
    sku: 'ATH-PRF-004',
    titleAr: 'صندوق المراسم الملكي للإهداء - عود هندي سيلاني + دهن ورد طائفي + عطر عنبر',
    titleEn: 'Royal Protocol VIP Gift Chest - Indian Oud, Taif Rose Oil & Amber Parfum',
    descriptionAr:
      'صندوق إهداء ملكي مكسو بالجلد النجدي الفاخر يضم أوقية عود هندي طبيعي، ربع توله دهن ورد طائفي عروس الهدا، وعطر عنبر الدرعية ١٠٠ مل مع مبخرة مذهّبة.',
    descriptionEn:
      'Bespoke leather-bound VIP presentation chest containing 28g Indian agarwood, quarter tola Al-Hada Taif Rose oil, 100ml Diriyah Amber parfum, and a gilded censer.',
    categoryId: 'perfumes',
    subcategoryAr: 'صناديق الإهداء الملكية',
    subcategoryEn: 'VIP Gift Boxes',
    brandId: 'brand-dar-oud',
    brandNameAr: 'دار الطيب الملكي',
    brandNameEn: 'Dar Al-Teeb Royal',
    sellerId: 'seller-1',
    sellerNameAr: 'دار العود والطيب الملكي',
    sellerNameEn: 'Dar Al-Oud Royal Perfumery',
    sellerRating: 4.9,
    sellerVerified: true,
    price: 2950,
    originalPrice: 3600,
    discountPercent: 18,
    stock: 11,
    lowStockThreshold: 3,
    status: 'active',
    rating: 5.0,
    reviewCount: 52,
    soldCount: 119,
    images: [
      'https://images.unsplash.com/photo-1588405748880-12d1d2a59f75?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'plate',
        nameAr: 'تخصيص الإهداء',
        nameEn: 'Gift Personalization',
        type: 'option',
        options: [
          { id: 'std', labelAr: 'شعار دار الطيب الملكي المذهّب', labelEn: 'Standard Royal Emblem', value: 'standard', inStock: true },
          { id: 'eng', labelAr: 'حفر الاسم بالليزر على لوحة نحاسية', labelEn: 'Custom Laser-Engraved Nameplate', value: 'custom', priceDelta: 100, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'محتويات الصندوق', keyEn: 'Contents', valueAr: '٤ قطع فاخرة + مبخرة + ملقط مذهّب + بطاقة إهداء', valueEn: '4 Luxury Pieces + Censer + Tongs + Gift Card' },
    ],
    warrantyAr: 'ضمان الأصالة والجودة من دار العود والطيب الملكي',
    warrantyEn: 'Authenticity & Quality Guarantee by Dar Al-Oud',
    deliveryEstimateAr: 'توصيل VIP خلال ٢٤ ساعة',
    deliveryEstimateEn: '24-hour VIP delivery',
    isFlashDeal: false,
    isFeatured: true,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: true,
    isSeasonal: true,
    createdAt: '2026-09-12',
  },

  // 9-12: SMARTPHONES & WEARABLES (seller-2: آفاق التقنية المعتمدة)
  {
    id: 'prod-9',
    sku: 'ATH-MOB-001',
    titleAr: 'هاتف آيفون ١٦ برو ماكس سعة ٥١٢ جيجابايت - تيتانيوم صحراوي (ضمان حاسبات العرب سنتين)',
    titleEn: 'Apple iPhone 16 Pro Max 512GB - Desert Titanium (2-Year Official KSA Warranty)',
    descriptionAr:
      'أقوى هواتف آبل بتصميم التيتانيوم الصحراوي الفاخر، شاشة Super Retina XDR مقاس ٦.٩ إنش، شريحة A18 Pro الخارقة، ونظام كاميرات احترافي بدقة ٤٨ ميجابكسل مع زر التحكم بالكاميرا ودعم كامل لتطبيق فيس تايم وشبكات 5G السعودية.',
    descriptionEn:
      'Apple flagship forged in Grade 5 Desert Titanium featuring a 6.9" Super Retina XDR display, A18 Pro chip, 48MP Fusion camera system, and official 2-year KSA Arab Computers warranty.',
    categoryId: 'smartphones',
    subcategoryAr: 'هواتف الفئة الرائدة',
    subcategoryEn: 'Flagship Smartphones',
    brandId: 'brand-apple',
    brandNameAr: 'آبل',
    brandNameEn: 'Apple',
    sellerId: 'seller-2',
    sellerNameAr: 'آفاق التقنية المعتمدة',
    sellerNameEn: 'Afaq Tech Authorized Store',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 5699,
    originalPrice: 6199,
    discountPercent: 8,
    stock: 42,
    lowStockThreshold: 10,
    status: 'active',
    rating: 4.95,
    reviewCount: 342,
    soldCount: 890,
    images: [
      'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1592750475338-74b7b21085ab?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Color',
        type: 'color',
        options: [
          { id: 'des', labelAr: 'تيتانيوم صحراوي', labelEn: 'Desert Titanium', value: 'desert', colorHex: '#C5A880', inStock: true },
          { id: 'nat', labelAr: 'تيتانيوم طبيعي', labelEn: 'Natural Titanium', value: 'natural', colorHex: '#9A9690', inStock: true },
          { id: 'blk', labelAr: 'تيتانيوم أسود', labelEn: 'Black Titanium', value: 'black', colorHex: '#232324', inStock: true },
        ],
      },
      {
        id: 'storage',
        nameAr: 'السعة التخزينية',
        nameEn: 'Storage Capacity',
        type: 'capacity',
        options: [
          { id: '256', labelAr: '256 جيجابايت', labelEn: '256 GB', value: '256GB', priceDelta: -500, inStock: true },
          { id: '512', labelAr: '512 جيجابايت', labelEn: '512 GB', value: '512GB', priceDelta: 0, inStock: true },
          { id: '1tb', labelAr: '1 تيرابايت', labelEn: '1 TB', value: '1TB', priceDelta: 900, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'المعالج', keyEn: 'Processor', valueAr: 'شريحة Apple A18 Pro بمعمارية ٣ نانومتر', valueEn: 'Apple A18 Pro (3nm)' },
      { keyAr: 'الشاشة', keyEn: 'Display', valueAr: '6.9" Super Retina XDR ProMotion 120Hz', valueEn: '6.9" Super Retina XDR ProMotion 120Hz' },
      { keyAr: 'نسخة الجهاز', keyEn: 'Region Model', valueAr: 'نسخة الشرق الأوسط الرسمية (فيس تايم مفعّل)', valueEn: 'Official KSA Middle East Version (FaceTime Enabled)' },
    ],
    warrantyAr: 'ضمان الوكيل الرسمي حاسبات العرب لمدة ٢٤ شهراً',
    warrantyEn: '24-Month Official Arab Computers KSA Warranty',
    deliveryEstimateAr: 'توصيل فوري في نفس اليوم بالرياض وجدة',
    deliveryEstimateEn: 'Same-day express delivery in Riyadh & Jeddah',
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-02T23:59:59Z',
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    frequentlyBoughtWith: ['prod-11', 'prod-13'],
    createdAt: '2026-09-15',
  },
  {
    id: 'prod-10',
    sku: 'ATH-MOB-002',
    titleAr: 'هاتف سامسونج جالاكسي S24 ألترا 5G سعة ٥١٢ جيجابايت مع القلم الذكي - رمادي تيتانيوم',
    titleEn: 'Samsung Galaxy S24 Ultra 5G 512GB with S-Pen - Titanium Gray',
    descriptionAr:
      'قمة الابتكار مع مزايا الذكاء الاصطناعي Galaxy AI، هيكل من التيتانيوم المتين، كاميرا ٢٠٠ ميجابكسل، وشاشة مسطحة مضادة للانعكاس مع قلم S-Pen المدمج.',
    descriptionEn:
      'Ultimate Android flagship with Galaxy AI, titanium exterior frame, 200MP quad-telephoto camera system, and integrated S-Pen.',
    categoryId: 'smartphones',
    subcategoryAr: 'هواتف الفئة الرائدة',
    subcategoryEn: 'Flagship Smartphones',
    brandId: 'brand-samsung',
    brandNameAr: 'سامسونج',
    brandNameEn: 'Samsung',
    sellerId: 'seller-2',
    sellerNameAr: 'آفاق التقنية المعتمدة',
    sellerNameEn: 'Afaq Tech Authorized Store',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 4599,
    originalPrice: 5399,
    discountPercent: 15,
    stock: 28,
    lowStockThreshold: 6,
    status: 'active',
    rating: 4.9,
    reviewCount: 198,
    soldCount: 530,
    images: [
      'https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Color',
        type: 'color',
        options: [
          { id: 'gry', labelAr: 'رمادي تيتانيوم', labelEn: 'Titanium Gray', value: 'gray', colorHex: '#7D7B78', inStock: true },
          { id: 'blk', labelAr: 'أسود تيتانيوم', labelEn: 'Titanium Black', value: 'black', colorHex: '#1C1C1C', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'الشاشة', keyEn: 'Display', valueAr: '6.8" Dynamic AMOLED 2X QHD+ 120Hz', valueEn: '6.8" Dynamic AMOLED 2X QHD+ 120Hz' },
      { keyAr: 'الذاكرة', keyEn: 'Memory', valueAr: '12GB RAM + 512GB Storage', valueEn: '12GB RAM + 512GB Storage' },
    ],
    warrantyAr: 'ضمان الوكيل الرسمي سامسونج السعودية سنتين',
    warrantyEn: '2-Year Official Samsung KSA Warranty',
    deliveryEstimateAr: 'توصيل سريع خلال ٢٤ ساعة',
    deliveryEstimateEn: 'Express 24-hour delivery',
    isFlashDeal: false,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-08-05',
  },
  {
    id: 'prod-11',
    sku: 'ATH-MOB-003',
    titleAr: 'ساعة آبل ووتش ألترا ٢ مقاس ٤٩ مم تيتانيوم أسود مع سوار ميلانيز تيتانيوم',
    titleEn: 'Apple Watch Ultra 2 (49mm) Black Titanium with Titanium Milanese Loop',
    descriptionAr:
      'الساعة الرياضية والفاخرة الأكثر صلابة وتطوراً من آبل، الآن بلمسة التيتانيوم الأسود الفاخر مع سوار ميلانيز منسوج من التيتانيوم الفضائي ومقاومة غوص حتى ٤٠ متراً.',
    descriptionEn:
      'The most rugged and capable Apple Watch in satin Black Titanium paired with the aerospace-grade Titanium Milanese Loop.',
    categoryId: 'smartphones',
    subcategoryAr: 'الساعات الذكية المتقدمة',
    subcategoryEn: 'Advanced Smartwatches',
    brandId: 'brand-apple',
    brandNameAr: 'آبل',
    brandNameEn: 'Apple',
    sellerId: 'seller-2',
    sellerNameAr: 'آفاق التقنية المعتمدة',
    sellerNameEn: 'Afaq Tech Authorized Store',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 3699,
    originalPrice: 3999,
    discountPercent: 8,
    stock: 19,
    lowStockThreshold: 5,
    status: 'active',
    rating: 4.9,
    reviewCount: 87,
    soldCount: 240,
    images: [
      'https://images.unsplash.com/photo-1546868871-7041f2a55e12?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'finish',
        nameAr: 'لون الهيكل',
        nameEn: 'Case Finish',
        type: 'color',
        options: [
          { id: 'blk', labelAr: 'تيتانيوم أسود', labelEn: 'Black Titanium', value: 'black', colorHex: '#1F1F1F', inStock: true },
          { id: 'nat', labelAr: 'تيتانيوم طبيعي', labelEn: 'Natural Titanium', value: 'natural', colorHex: '#A39E93', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'الاتصال', keyEn: 'Connectivity', valueAr: 'GPS + Cellular (دعم شريحة eSIM السعودية)', valueEn: 'GPS + Cellular (Supports KSA eSIM)' },
      { keyAr: 'السطوع', keyEn: 'Brightness', valueAr: '٣٠٠٠ شمعة لوضوح فائق تحت شمس الظهيرة', valueEn: '3000 nits peak outdoor brightness' },
    ],
    warrantyAr: 'ضمان حاسبات العرب سنتين',
    warrantyEn: '2-Year Arab Computers Warranty',
    deliveryEstimateAr: 'توصيل مجاني خلال ٢٤ ساعة',
    deliveryEstimateEn: 'Free 24-hour delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    createdAt: '2026-09-16',
  },
  {
    id: 'prod-12',
    sku: 'ATH-MOB-004',
    titleAr: 'هاتف سامسونج جالاكسي Z فولد ٦ القابل للطي ٥١٢ جيجابايت - كحلي ملكي',
    titleEn: 'Samsung Galaxy Z Fold 6 5G 512GB Foldable Smartphone - Crafted Navy',
    descriptionAr:
      'إنتاجية حاسوب لوحي في جيبك مع شاشة داخلية قابلة للطي مقاس ٧.٦ إنش فائقة السطوع، تصميم أنحف وأخف وزناً، ومترجم فوري بالذكاء الاصطناعي للاجتماعات والسفر.',
    descriptionEn:
      'Unfold PC-like productivity with a 7.6" Dynamic AMOLED 2X main screen, ultra-slim Armor Aluminum hinge, and live AI interpreter.',
    categoryId: 'smartphones',
    subcategoryAr: 'الهواتف القابلة للطي',
    subcategoryEn: 'Foldable Phones',
    brandId: 'brand-samsung',
    brandNameAr: 'سامسونج',
    brandNameEn: 'Samsung',
    sellerId: 'seller-2',
    sellerNameAr: 'آفاق التقنية المعتمدة',
    sellerNameEn: 'Afaq Tech Authorized Store',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 6299,
    originalPrice: 7299,
    discountPercent: 14,
    stock: 14,
    lowStockThreshold: 4,
    status: 'active',
    rating: 4.85,
    reviewCount: 64,
    soldCount: 150,
    images: [
      'https://images.unsplash.com/photo-1580910051074-3eb694886505?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Color',
        type: 'color',
        options: [
          { id: 'nvy', labelAr: 'كحلي ملكي', labelEn: 'Crafted Navy', value: 'navy', colorHex: '#1D2939', inStock: true },
          { id: 'slv', labelAr: 'فضي شادو', labelEn: 'Silver Shadow', value: 'silver', colorHex: '#8E9297', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'الشاشة الداخلية', keyEn: 'Main Display', valueAr: '7.6" QXGA+ Foldable Dynamic AMOLED 2X', valueEn: '7.6" QXGA+ Foldable Dynamic AMOLED 2X' },
    ],
    warrantyAr: 'ضمان سنتين شامل سنة تأمين على الشاشة الداخلية',
    warrantyEn: '2-Year Warranty + 1-Year Samsung Care+ Screen Protection',
    deliveryEstimateAr: 'توصيل VIP خلال ٢٤ ساعة',
    deliveryEstimateEn: '24-hour VIP delivery',
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-04T23:59:59Z',
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    isNewArrival: true,
    createdAt: '2026-09-02',
  },

  // 13-16: ELECTRONICS & AUDIO (seller-2: آفاق التقنية المعتمدة)
  {
    id: 'prod-13',
    sku: 'ATH-AUD-001',
    titleAr: 'سماعة سوني اللاسلكية WH-1000XM5 العازلة للضجيج - إصدار البلاتين الفاخر',
    titleEn: 'Sony WH-1000XM5 Wireless Industry-Leading Noise Canceling Headphones',
    descriptionAr:
      'أفضل تقنية عزل ضجيج في العالم بفضل ٨ ميكروفونات ومعالجين ذكيين، مثالية لرحلات الطيران الطويلة ودرجة الأعمال، مع بطارية تدوم ٣٠ ساعة وصوت عالي الدقة Hi-Res Audio.',
    descriptionEn:
      'Industry-leading noise cancellation powered by 8 microphones and dual processors, 30-hour battery life, and ultra-plush soft fit leather.',
    categoryId: 'electronics',
    subcategoryAr: 'سماعات وأنظمة صوتية',
    subcategoryEn: 'Headphones & Hi-Fi Audio',
    brandId: 'brand-sony',
    brandNameAr: 'سوني',
    brandNameEn: 'Sony',
    sellerId: 'seller-2',
    sellerNameAr: 'آفاق التقنية المعتمدة',
    sellerNameEn: 'Afaq Tech Authorized Store',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 1299,
    originalPrice: 1649,
    discountPercent: 21,
    stock: 35,
    lowStockThreshold: 8,
    status: 'active',
    rating: 4.9,
    reviewCount: 276,
    soldCount: 740,
    images: [
      'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Color',
        type: 'color',
        options: [
          { id: 'plt', labelAr: 'فضي بلاتيني', labelEn: 'Platinum Silver', value: 'silver', colorHex: '#D6D3CD', inStock: true },
          { id: 'blk', labelAr: 'أسود مطفي', labelEn: 'Midnight Black', value: 'black', colorHex: '#18181B', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'عمر البطارية', keyEn: 'Battery Life', valueAr: '٣٠ ساعة مع تفعيل عزل الضجيج (شحن ٣ دقائق يمنح ٣ ساعات)', valueEn: '30 Hours with ANC (3-min quick charge = 3 hours)' },
      { keyAr: 'الوزن', keyEn: 'Weight', valueAr: '٢٥٠ جرام خفيفة ومريحة للأذن', valueEn: '250g Ultra-lightweight' },
    ],
    warrantyAr: 'ضمان الوكيل الحديث للإلكترونيات سنتين',
    warrantyEn: '2-Year Official Sony KSA Warranty',
    deliveryEstimateAr: 'توصيل خلال ٢٤ ساعة',
    deliveryEstimateEn: '24-hour delivery',
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-05T23:59:59Z',
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-07-20',
  },
  {
    id: 'prod-14',
    sku: 'ATH-ELC-002',
    titleAr: 'تلفاز سوني برافيا ٧٧ إنش XR OLED 4K Ultra HD سينمائي ذكي Google TV',
    titleEn: 'Sony BRAVIA 77" XR OLED 4K HDR Smart Home Cinema Google TV',
    descriptionAr:
      'تجربة سينمائية مذهلة للمجالس والصالات الفاخرة مع شاشة OLED عملاقة مقاس ٧٧ بوصة، معالج Cognitive Processor XR، وصوت يخرج مباشرة من الشاشة Acoustic Surface Audio+.',
    descriptionEn:
      'Master Series 77-inch 4K OLED television powered by Cognitive Processor XR with pure blacks, Dolby Vision, and Acoustic Surface Audio+.',
    categoryId: 'electronics',
    subcategoryAr: 'شاشات التلفاز الذكية OLED',
    subcategoryEn: 'OLED Smart TVs',
    brandId: 'brand-sony',
    brandNameAr: 'سوني',
    brandNameEn: 'Sony',
    sellerId: 'seller-2',
    sellerNameAr: 'آفاق التقنية المعتمدة',
    sellerNameEn: 'Afaq Tech Authorized Store',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 11499,
    originalPrice: 13999,
    discountPercent: 18,
    stock: 3,
    lowStockThreshold: 4,
    status: 'active',
    rating: 4.95,
    reviewCount: 44,
    soldCount: 92,
    images: [
      'https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'size',
        nameAr: 'المقاس',
        nameEn: 'Screen Size',
        type: 'size',
        options: [
          { id: '65', labelAr: '65 بوصة OLED', labelEn: '65-Inch OLED', value: '65', priceDelta: -3200, inStock: true },
          { id: '77', labelAr: '77 بوصة سينمائي OLED', labelEn: '77-Inch Cinema OLED', value: '77', priceDelta: 0, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'معدل التحديث', keyEn: 'Refresh Rate', valueAr: '120Hz مثالي للبلايستيشن ٥ والرياضة', valueEn: '120Hz Native with HDMI 2.1' },
      { keyAr: 'التركيب الجداري', keyEn: 'Installation', valueAr: 'يشمل التوصيل والتركيب الجداري المجاني في المدن الرئيسية', valueEn: 'Includes Free Wall Mounting in Major Cities' },
    ],
    warrantyAr: 'ضمان سنتين شامل الزيارة المنزلية',
    warrantyEn: '2-Year On-Site Home Warranty',
    deliveryEstimateAr: 'توصيل وتركيب خلال ٤٨ ساعة',
    deliveryEstimateEn: 'Delivery & installation within 48 hours',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-08-11',
  },
  {
    id: 'prod-15',
    sku: 'ATH-ELC-003',
    titleAr: 'كاميرا سوني الاحترافية Alpha A7 IV بدون مرآة كامل الإطار مع عدسة 28-70mm',
    titleEn: 'Sony Alpha A7 IV Full-Frame Mirrorless Camera Kit with 28-70mm Lens',
    descriptionAr:
      'المعيار الذهبي لصناع المحتوى والمصورين المحترفين: مستشعر Exmor R كامل الإطار بدقة ٣٣ ميجابكسل، تصوير فيديو سينمائي 4K 60p 10-bit، وتركيز بؤري فوري بالذكاء الاصطناعي.',
    descriptionEn:
      'Hybrid full-frame powerhouse featuring a 33MP Exmor R sensor, 10-bit 4K 60p video recording, and real-time Eye AF tracking.',
    categoryId: 'electronics',
    subcategoryAr: 'كاميرات التصوير الاحترافية',
    subcategoryEn: 'Professional Cameras',
    brandId: 'brand-sony',
    brandNameAr: 'سوني',
    brandNameEn: 'Sony',
    sellerId: 'seller-2',
    sellerNameAr: 'آفاق التقنية المعتمدة',
    sellerNameEn: 'Afaq Tech Authorized Store',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 9850,
    originalPrice: 11200,
    discountPercent: 12,
    stock: 10,
    lowStockThreshold: 3,
    status: 'active',
    rating: 4.9,
    reviewCount: 59,
    soldCount: 115,
    images: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'kit',
        nameAr: 'الخيار',
        nameEn: 'Kit Option',
        type: 'option',
        options: [
          { id: 'body', labelAr: 'الكاميرا فقط (Body Only)', labelEn: 'Body Only', value: 'body', priceDelta: -950, inStock: true },
          { id: 'lens', labelAr: 'مع عدسة 28-70mm FE', labelEn: 'With 28-70mm Lens', value: 'kit', priceDelta: 0, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'دقة المستشعر', keyEn: 'Sensor Resolution', valueAr: '33 MP Full-Frame Exmor R CMOS', valueEn: '33 MP Full-Frame Exmor R CMOS' },
    ],
    warrantyAr: 'ضمان الوكيل سنتين',
    warrantyEn: '2-Year Authorized Warranty',
    deliveryEstimateAr: 'توصيل خلال ٢٤-٤٨ ساعة',
    deliveryEstimateEn: '24-48h delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    isNewArrival: false,
    createdAt: '2026-08-22',
  },
  {
    id: 'prod-16',
    sku: 'ATH-ELC-004',
    titleAr: 'سماعة أبل إيربودز ماكس اللاسلكية بمنفذ USB-C - لون سماء الليل (Midnight)',
    titleEn: 'Apple AirPods Max Wireless Over-Ear Headphones (USB-C) - Midnight',
    descriptionAr:
      'تصميم أيقوني من الألمنيوم المؤكسد والوسائد الشبكية المريحة مع صوت مكاني مخصص وعزل ضجيج احترافي ومنفذ شحن USB-C الجديد.',
    descriptionEn:
      'Anodized aluminum cups, breathable knit mesh canopy, pro-level Active Noise Cancellation, Personalized Spatial Audio, and USB-C charging.',
    categoryId: 'electronics',
    subcategoryAr: 'سماعات وأنظمة صوتية',
    subcategoryEn: 'Headphones & Hi-Fi Audio',
    brandId: 'brand-apple',
    brandNameAr: 'آبل',
    brandNameEn: 'Apple',
    sellerId: 'seller-2',
    sellerNameAr: 'آفاق التقنية المعتمدة',
    sellerNameEn: 'Afaq Tech Authorized Store',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 2399,
    originalPrice: 2599,
    discountPercent: 8,
    stock: 21,
    lowStockThreshold: 5,
    status: 'active',
    rating: 4.85,
    reviewCount: 112,
    soldCount: 320,
    images: [
      'https://images.unsplash.com/photo-1546435770-a3e426bf472b?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Color',
        type: 'color',
        options: [
          { id: 'mid', labelAr: 'سماء الليل (Midnight)', labelEn: 'Midnight', value: 'midnight', colorHex: '#1E242B', inStock: true },
          { id: 'str', labelAr: 'ضوء النجوم (Starlight)', labelEn: 'Starlight', value: 'starlight', colorHex: '#E5DFD3', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'الشريحة', keyEn: 'Chip', valueAr: 'Apple H1 في كل جهة', valueEn: 'Dual Apple H1 Headphone Chips' },
    ],
    warrantyAr: 'ضمان حاسبات العرب سنتين',
    warrantyEn: '2-Year Arab Computers Warranty',
    deliveryEstimateAr: 'توصيل خلال ٢٤ ساعة',
    deliveryEstimateEn: '24-hour delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    createdAt: '2026-09-18',
  },

  // 17-20: COMPUTERS & WORKSTATIONS (seller-2: آفاق التقنية المعتمدة)
  {
    id: 'prod-17',
    sku: 'ATH-CMP-001',
    titleAr: 'حاسوب أبل ماك بوك برو ١٦ إنش شريحة M3 Max بذاكرة ٤٨ جيجابايت وسعة ١ تيرابايت - أسود فلكي',
    titleEn: 'Apple MacBook Pro 16" M3 Max (48GB RAM / 1TB SSD) - Space Black',
    descriptionAr:
      'محطة عمل متنقلة خارقة للمديرين التنفيذيين والمصممين والمهندسين. شاشة Liquid Retina XDR مذهلة، لوحة مفاتيح عربية/إنجليزية أصلية، وبطارية تدوم حتى ٢٢ ساعة.',
    descriptionEn:
      'Ultimate pro laptop with M3 Max 16-core CPU, 40-core GPU, 48GB unified memory, Liquid Retina XDR display, and official Arabic/English keyboard.',
    categoryId: 'computers',
    subcategoryAr: 'أجهزة لابتوب للأعمال والمبدعين',
    subcategoryEn: 'Pro Creator Laptops',
    brandId: 'brand-apple',
    brandNameAr: 'آبل',
    brandNameEn: 'Apple',
    sellerId: 'seller-2',
    sellerNameAr: 'آفاق التقنية المعتمدة',
    sellerNameEn: 'Afaq Tech Authorized Store',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 14999,
    originalPrice: 16499,
    discountPercent: 9,
    stock: 11,
    lowStockThreshold: 3,
    status: 'active',
    rating: 4.95,
    reviewCount: 78,
    soldCount: 164,
    images: [
      'https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'spec',
        nameAr: 'المواصفات',
        nameEn: 'Configuration',
        type: 'capacity',
        options: [
          { id: '36-1tb', labelAr: '36GB RAM / 1TB SSD', labelEn: '36GB RAM / 1TB SSD', value: '36GB', priceDelta: -1500, inStock: true },
          { id: '48-1tb', labelAr: '48GB RAM / 1TB SSD', labelEn: '48GB RAM / 1TB SSD', value: '48GB', priceDelta: 0, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'لوحة المفاتيح', keyEn: 'Keyboard', valueAr: 'عربي / إنجليزي أصلي مضاء Magic Keyboard مع Touch ID', valueEn: 'Official Backlit Arabic/English Magic Keyboard' },
      { keyAr: 'الشاشة', keyEn: 'Display', valueAr: '16.2" Liquid Retina XDR (3456 x 2234)', valueEn: '16.2" Liquid Retina XDR' },
    ],
    warrantyAr: 'ضمان حاسبات العرب سنتين',
    warrantyEn: '2-Year Official Arab Computers Warranty',
    deliveryEstimateAr: 'توصيل VIP مؤمّن خلال ٢٤ ساعة',
    deliveryEstimateEn: 'Insured 24h VIP delivery',
    isFlashDeal: false,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-08-14',
  },
  {
    id: 'prod-18',
    sku: 'ATH-CMP-002',
    titleAr: 'جهاز آيباد برو ١٣ إنش شريحة M4 شاشة Ultra Retina XDR OLED سعة ٥١٢ جيجابايت Wi-Fi + 5G',
    titleEn: 'Apple iPad Pro 13" M4 Chip Ultra Retina XDR Tandem OLED 512GB Wi-Fi + Cellular',
    descriptionAr:
      'أنحف منتج من آبل على الإطلاق مع شاشة Tandem OLED الخارقة وشريحة M4 ودعم الجيل الخامس 5G وقلم Apple Pencil Pro.',
    descriptionEn:
      ' impossibly thin design featuring breakthrough Tandem OLED Ultra Retina XDR display, M4 chip, and 5G cellular connectivity.',
    categoryId: 'computers',
    subcategoryAr: 'الأجهزة اللوحية الاحترافية',
    subcategoryEn: 'Pro Tablets & Stylus',
    brandId: 'brand-apple',
    brandNameAr: 'آبل',
    brandNameEn: 'Apple',
    sellerId: 'seller-2',
    sellerNameAr: 'آفاق التقنية المعتمدة',
    sellerNameEn: 'Afaq Tech Authorized Store',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 6899,
    originalPrice: 7499,
    discountPercent: 8,
    stock: 18,
    lowStockThreshold: 4,
    status: 'active',
    rating: 4.9,
    reviewCount: 92,
    soldCount: 230,
    images: [
      'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Color',
        type: 'color',
        options: [
          { id: 'blk', labelAr: 'أسود فلكي', labelEn: 'Space Black', value: 'black', colorHex: '#252526', inStock: true },
          { id: 'slv', labelAr: 'فضي', labelEn: 'Silver', value: 'silver', colorHex: '#D9DADB', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'السماكة', keyEn: 'Thickness', valueAr: '٥.١ ملم فقط', valueEn: 'Ultra-thin 5.1 mm profile' },
    ],
    warrantyAr: 'ضمان سنتين حاسبات العرب',
    warrantyEn: '2-Year Official KSA Warranty',
    deliveryEstimateAr: 'توصيل خلال ٢٤ ساعة',
    deliveryEstimateEn: '24-hour delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    createdAt: '2026-09-04',
  },
  {
    id: 'prod-19',
    sku: 'ATH-CMP-003',
    titleAr: 'شاشة أبل ستوديو ديسبلاي ٢٧ إنش بدقة 5K Retina مع كاميرا 12MP Center Stage',
    titleEn: 'Apple Studio Display 27-Inch 5K Retina Monitor with Tilt-Adjustable Stand',
    descriptionAr:
      'شاشة 5K مذهلة تضم ١٤.٧ مليون بكسل وسطوع ٦٠٠ شمعة ونظام صوتي من ٦ مكبرات صوت مع Dolby Atmos.',
    descriptionEn:
      '27-inch 5K Retina display with 600 nits brightness, P3 wide color, 12MP Ultra Wide camera with Center Stage, and studio-quality mics.',
    categoryId: 'computers',
    subcategoryAr: 'شاشات 4K و 5K الاحترافية',
    subcategoryEn: '4K & 5K Studio Monitors',
    brandId: 'brand-apple',
    brandNameAr: 'آبل',
    brandNameEn: 'Apple',
    sellerId: 'seller-2',
    sellerNameAr: 'آفاق التقنية المعتمدة',
    sellerNameEn: 'Afaq Tech Authorized Store',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 6999,
    originalPrice: 7699,
    discountPercent: 9,
    stock: 9,
    lowStockThreshold: 3,
    status: 'active',
    rating: 4.85,
    reviewCount: 41,
    soldCount: 85,
    images: [
      'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'glass',
        nameAr: 'نوع الزجاج',
        nameEn: 'Glass Option',
        type: 'option',
        options: [
          { id: 'std', labelAr: 'زجاج قياسي', labelEn: 'Standard Glass', value: 'standard', inStock: true },
          { id: 'nano', labelAr: 'زجاج Nano-texture مضاد للانعكاس', labelEn: 'Nano-texture Glass', value: 'nano', priceDelta: 1300, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'الدقة', keyEn: 'Resolution', valueAr: '5120 x 2880 (5K Retina) عند 218 بكسل لكل إنش', valueEn: '5120 x 2880 5K Retina (218 ppi)' },
    ],
    warrantyAr: 'ضمان سنتين حاسبات العرب',
    warrantyEn: '2-Year Official Warranty',
    deliveryEstimateAr: 'توصيل خلال ٢٤-٤٨ ساعة',
    deliveryEstimateEn: '24-48h delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: false,
    createdAt: '2026-08-01',
  },
  {
    id: 'prod-20',
    sku: 'ATH-CMP-004',
    titleAr: 'حاسوب ماك بوك إير ١٥ إنش شريحة M3 سعة ٥١٢ جيجابايت وذاكرة ١٦ جيجابايت - ضوء النجوم',
    titleEn: 'Apple MacBook Air 15" M3 Chip (16GB RAM / 512GB SSD) - Starlight',
    descriptionAr:
      'نحافة مذهلة وشاشة ١٥.٣ إنش واسعة مع شريحة M3 السريعة وذاكرة موحدة ١٦ جيجابايت لأداء يومي فائق السلاسة بدون ضجيج مراوح.',
    descriptionEn:
      'Supercharged by the M3 chip in a thin, fanless 15.3-inch Liquid Retina design with 18-hour battery life.',
    categoryId: 'computers',
    subcategoryAr: 'أجهزة لابتوب للأعمال والمبدعين',
    subcategoryEn: 'Pro Creator Laptops',
    brandId: 'brand-apple',
    brandNameAr: 'آبل',
    brandNameEn: 'Apple',
    sellerId: 'seller-2',
    sellerNameAr: 'آفاق التقنية المعتمدة',
    sellerNameEn: 'Afaq Tech Authorized Store',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 6499,
    originalPrice: 7199,
    discountPercent: 10,
    stock: 25,
    lowStockThreshold: 5,
    status: 'active',
    rating: 4.9,
    reviewCount: 118,
    soldCount: 340,
    images: [
      'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Color',
        type: 'color',
        options: [
          { id: 'str', labelAr: 'ضوء النجوم (Starlight)', labelEn: 'Starlight', value: 'starlight', colorHex: '#E5DFD3', inStock: true },
          { id: 'mid', labelAr: 'سماء الليل (Midnight)', labelEn: 'Midnight', value: 'midnight', colorHex: '#1E242B', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'الوزن', keyEn: 'Weight', valueAr: '١.٥١ كجم خفيف ومثالي للتنقل', valueEn: '1.51 kg lightweight chassis' },
    ],
    warrantyAr: 'ضمان سنتين حاسبات العرب',
    warrantyEn: '2-Year Official Warranty',
    deliveryEstimateAr: 'توصيل خلال ٢٤ ساعة',
    deliveryEstimateEn: '24-hour delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-08-19',
  },

  // 21-24: HOME, KITCHEN & ESPRESSO (seller-5: رواق القهوة والمنزل الفاخر)
  {
    id: 'prod-21',
    sku: 'ATH-HOM-001',
    titleAr: 'ماكينة إسبريسو بريفيل أوراكل تاتش الاحترافية مع مطحنة مدمجة - ستانلس ستيل مصقول',
    titleEn: 'Breville the Oracle Touch Dual Boiler Espresso Machine - Brushed Stainless Steel',
    descriptionAr:
      'ماكينة القهوة المختصة الأوتوماتيكية بالكامل بنظام غلاية مزدوجة (Dual Boiler). تقوم بالطحن، المعايرة، الكبس، واستخلاص الإسبريسو وتبخير الحليب الحريري للاتيه آرت بلمسة واحدة على الشاشة الملونة.',
    descriptionEn:
      'Automated dual-boiler specialty espresso machine with integrated conical burr grinder, auto-tamping, PID temperature control, and microfoam steam wand.',
    categoryId: 'home-kitchen',
    subcategoryAr: 'مكائن القهوة المختصة والإسبريسو',
    subcategoryEn: 'Specialty Espresso Machines',
    brandId: 'brand-breville',
    brandNameAr: 'بريفيل ولامارزوكو',
    brandNameEn: 'La Marzocco & Breville',
    sellerId: 'seller-5',
    sellerNameAr: 'رواق القهوة والمنزل الفاخر',
    sellerNameEn: 'Rawaq Specialty Coffee & Living',
    sellerRating: 4.9,
    sellerVerified: true,
    price: 8490,
    originalPrice: 9990,
    discountPercent: 15,
    stock: 12,
    lowStockThreshold: 3,
    status: 'active',
    rating: 4.95,
    reviewCount: 134,
    soldCount: 290,
    images: [
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Finish',
        type: 'color',
        options: [
          { id: 'stl', labelAr: 'ستانلس ستيل مصقول', labelEn: 'Brushed Stainless Steel', value: 'steel', colorHex: '#B8BCC0', inStock: true },
          { id: 'trf', labelAr: 'أسود ترافل مطفي', labelEn: 'Black Truffle Matte', value: 'black', colorHex: '#1F1E1D', priceDelta: 200, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'نظام الغلايات', keyEn: 'Boiler System', valueAr: 'غلاية مزدوجة من الفولاذ (استخلاص وتبخير في آن واحد)', valueEn: 'Dual Stainless Steel Boilers with PID' },
      { keyAr: 'بورتافلتر', keyEn: 'Portafilter', valueAr: 'مقاس احترافي ٥٨ مم من الفولاذ المقاوم للصدأ', valueEn: 'Commercial 58mm Stainless Steel Portafilter' },
      { keyAr: 'الجهد الكهربائي', keyEn: 'Voltage', valueAr: '٢٢٠-٢٤٠ فولت (فيش ثلاثي مطابق للمواصفات السعودية SASO)', valueEn: '220-240V SASO Certified UK/KSA Plug' },
    ],
    warrantyAr: 'ضمان الوكيل المعتمد سنتين مع جلسة معايرة مجانية للقهوة',
    warrantyEn: '2-Year Authorized Warranty + Free Barista Calibration Session',
    deliveryEstimateAr: 'توصيل مجاني خلال ٢٤-٤٨ ساعة لجميع مناطق المملكة',
    deliveryEstimateEn: 'Free KSA-wide delivery in 24-48 hours',
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-04T23:59:59Z',
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    isSeasonal: true,
    frequentlyBoughtWith: ['prod-22', 'prod-45'],
    createdAt: '2026-08-03',
  },
  {
    id: 'prod-22',
    sku: 'ATH-HOM-002',
    titleAr: 'طقم ضيافة سعودي ملكي (دلة قهوة عربية + ترمس شاي + فناجين البورسلان المذهّب بعيار ٢٤)',
    titleEn: 'Royal Saudi Hospitality Set (Gilded Arabic Coffee Dallah, Tea Flask & 12 Porcelain Cups)',
    descriptionAr:
      'طقم ضيافة فاخر مستوحى من النقوش النجدية الأصيلة، مطلي بماء الذهب عيار ٢٤ قيراطاً مع عزل حراري يحفظ حرارة القهوة السعودية والشاي لأكثر من ١٨ ساعة.',
    descriptionEn:
      'Heirloom Saudi hospitality ensemble adorned with 24K gold Najdi motifs, keeping Arabic coffee and tea piping hot for up to 18 hours.',
    categoryId: 'home-kitchen',
    subcategoryAr: 'دلال وأطقم الضيافة السعودية',
    subcategoryEn: 'Saudi Dallah & Hospitality Sets',
    brandId: 'brand-najd',
    brandNameAr: 'أتيليه نجد الملكي',
    brandNameEn: 'Najd Royal Atelier',
    sellerId: 'seller-5',
    sellerNameAr: 'رواق القهوة والمنزل الفاخر',
    sellerNameEn: 'Rawaq Specialty Coffee & Living',
    sellerRating: 4.9,
    sellerVerified: true,
    price: 1650,
    originalPrice: 2100,
    discountPercent: 21,
    stock: 26,
    lowStockThreshold: 5,
    status: 'active',
    rating: 4.9,
    reviewCount: 156,
    soldCount: 470,
    images: [
      'https://images.unsplash.com/photo-1578632767115-351597cf2477?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'لون الطقم',
        nameEn: 'Set Color',
        type: 'color',
        options: [
          { id: 'emr', labelAr: 'أخضر درعية وذهبي', labelEn: 'Diriyah Emerald & Gold', value: 'emerald', colorHex: '#0B4F3F', inStock: true },
          { id: 'crm', labelAr: 'عاجي ملكي وذهبي', labelEn: 'Royal Ivory & Gold', value: 'ivory', colorHex: '#F3EFEA', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'عدد القطع', keyEn: 'Set Pieces', valueAr: '٢٨ قطعة شاملة الدلة، الترمس، ١٢ فنجان قهوة، ١٢ بيالة شاي، وسكرية', valueEn: '28-Piece Complete Set (Dallah, Flask, 12 Finjans, 12 Tea Glasses)' },
    ],
    warrantyAr: 'ضمان ٣ سنوات على حفظ الحرارة وثبات اللون الذهبي',
    warrantyEn: '3-Year Thermal & Gold-Plating Guarantee',
    deliveryEstimateAr: 'توصيل آمن ضد الكسر خلال ٢٤-٤٨ ساعة',
    deliveryEstimateEn: 'Breakage-insured delivery in 24-48h',
    isFlashDeal: false,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    isSeasonal: true,
    createdAt: '2026-09-01',
  },
  {
    id: 'prod-23',
    sku: 'ATH-HOM-003',
    titleAr: 'مكنسة دايسون اللاسلكية الذكية V15 Detect Absolute بالليزر الكاشف للغبار الدقيق',
    titleEn: 'Dyson V15 Detect Absolute Cordless Vacuum with Fluffy Optic Laser',
    descriptionAr:
      'أقوى مكنسة لاسلكية ذكية من دايسون تكشف الغبار غير المرئي على الأرضيات الرخامية والباركيه بفضل إضاءة Fluffy Optic وتقيس حجم الذرات تلقائياً.',
    descriptionEn:
      'Dyson’s most powerful, intelligent cordless vacuum with Fluffy Optic illumination that reveals 2x more microscopic dust on marble and hard floors.',
    categoryId: 'home-kitchen',
    subcategoryAr: 'أجهزة تنقية الهواء والعناية بالمنزل',
    subcategoryEn: 'Air Purifiers & Vacuums',
    brandId: 'brand-dyson',
    brandNameAr: 'دايسون',
    brandNameEn: 'Dyson',
    sellerId: 'seller-5',
    sellerNameAr: 'رواق القهوة والمنزل الفاخر',
    sellerNameEn: 'Rawaq Specialty Coffee & Living',
    sellerRating: 4.9,
    sellerVerified: true,
    price: 2799,
    originalPrice: 3299,
    discountPercent: 15,
    stock: 19,
    lowStockThreshold: 5,
    status: 'active',
    rating: 4.85,
    reviewCount: 142,
    soldCount: 380,
    images: [
      'https://images.unsplash.com/photo-1558317374-067fb5f30001?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'edition',
        nameAr: 'الإصدار',
        nameEn: 'Edition',
        type: 'option',
        options: [
          { id: 'abs', labelAr: 'إصدار Absolute الذهبي الكامل', labelEn: 'Absolute Gold Complete', value: 'absolute', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'مدة التشغيل', keyEn: 'Run Time', valueAr: 'حتى ٦٠ دقيقة متواصلة', valueEn: 'Up to 60 minutes fade-free power' },
    ],
    warrantyAr: 'ضمان الوكيل سنتين',
    warrantyEn: '2-Year Official Dyson KSA Warranty',
    deliveryEstimateAr: 'توصيل خلال ٢٤-٤٨ ساعة',
    deliveryEstimateEn: '24-48h delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-08-12',
  },
  {
    id: 'prod-24',
    sku: 'ATH-HOM-004',
    titleAr: 'ماكينة إسبريسو لامارزوكو لينيا ميني الإيطالية الاحترافية للمنزل الفاخر - أبيض كلاسيك',
    titleEn: 'La Marzocco Linea Mini Commercial-Grade Home Espresso Machine - Classic White',
    descriptionAr:
      'الأيقونة الإيطالية المصنوعة يدوياً في فلورنسا، إيطاليا. تمنحك أداء المقاهي العالمية في منزلك مع غلاية مزدوجة ومضخة دورانية احترافية واتصال بتطبيق الهاتف.',
    descriptionEn:
      'Handcrafted in Florence, Italy. The Linea Mini brings commercial La Marzocco dual-boiler performance and rotary pump precision to your luxury kitchen.',
    categoryId: 'home-kitchen',
    subcategoryAr: 'مكائن القهوة المختصة والإسبريسو',
    subcategoryEn: 'Specialty Espresso Machines',
    brandId: 'brand-breville',
    brandNameAr: 'بريفيل ولامارزوكو',
    brandNameEn: 'La Marzocco & Breville',
    sellerId: 'seller-5',
    sellerNameAr: 'رواق القهوة والمنزل الفاخر',
    sellerNameEn: 'Rawaq Specialty Coffee & Living',
    sellerRating: 4.9,
    sellerVerified: true,
    price: 19800,
    originalPrice: 21500,
    discountPercent: 8,
    stock: 4,
    lowStockThreshold: 2,
    status: 'active',
    rating: 5.0,
    reviewCount: 28,
    soldCount: 41,
    images: [
      'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Color',
        type: 'color',
        options: [
          { id: 'wht', labelAr: 'أبيض فلورنسا كلاسيك', labelEn: 'Classic White', value: 'white', colorHex: '#FAF8F5', inStock: true },
          { id: 'blk', labelAr: 'أسود مطفي مع لمسات خشب الجوز', labelEn: 'Matte Black & Walnut', value: 'black', colorHex: '#141413', priceDelta: 1200, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'بلد الصنع', keyEn: 'Origin', valueAr: 'صناعة يدوية في فلورنسا - إيطاليا', valueEn: 'Handbuilt in Florence, Italy' },
    ],
    warrantyAr: 'ضمان سنتين شامل التركيب والبرمجة المنزلية',
    warrantyEn: '2-Year White-Glove Home Installation & Warranty',
    deliveryEstimateAr: 'توصيل وتركيب خاص خلال ٤٨ ساعة',
    deliveryEstimateEn: 'White-glove installation within 48 hours',
    isFlashDeal: false,
    isFeatured: true,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: true,
    createdAt: '2026-09-09',
  },

  // 25-28: MEN'S LUXURY FASHION (seller-4: أتيليه نجد للأزياء والعبايات)
  {
    id: 'prod-25',
    sku: 'ATH-MEN-001',
    titleAr: 'بشت ملكي حساوي صوف وبر طبيعي مطرز بزري ألماني مذهّب عيار ٢٤ - صناعة يدوية',
    titleEn: 'Royal Hasawi Bisht in Fine Wool with 24K Gold-Plated German Zari - Handwoven',
    descriptionAr:
      'بشت ملكي فاخر محاك يدوياً على الطريقة الحساوية العريقة (تركيب ملكي متقن) باستخدام أنعم خيوط الوبر الطبيعي وزري ألماني أصلي مطلي بالذهب الخالص لا يتغير لونه مع السنين.',
    descriptionEn:
      'Masterpiece royal Hasawi Bisht tailored from breathable fine natural wool and hand-embroidered with tarnish-free 24K gold-plated German Zari.',
    categoryId: 'mens-fashion',
    subcategoryAr: 'البشوت الملكية الحساوية',
    subcategoryEn: 'Royal Hasawi Bishts',
    brandId: 'brand-najd',
    brandNameAr: 'أتيليه نجد الملكي',
    brandNameEn: 'Najd Royal Atelier',
    sellerId: 'seller-4',
    sellerNameAr: 'أتيليه نجد للأزياء والعبايات',
    sellerNameEn: 'Najd Couture & Royal Attire',
    sellerRating: 4.85,
    sellerVerified: true,
    price: 3850,
    originalPrice: 4600,
    discountPercent: 16,
    stock: 14,
    lowStockThreshold: 3,
    status: 'active',
    rating: 4.95,
    reviewCount: 91,
    soldCount: 185,
    images: [
      'https://images.unsplash.com/photo-1617137984095-74e4e5e3613f?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'لون البشت',
        nameEn: 'Bisht Color',
        type: 'color',
        options: [
          { id: 'blk', labelAr: 'أسود ملكي', labelEn: 'Royal Black', value: 'black', colorHex: '#141413', inStock: true },
          { id: 'bge', labelAr: 'أشقر نجدي (بيج ذهبي)', labelEn: 'Najdi Blonde Beige', value: 'beige', colorHex: '#D2B48C', inStock: true },
          { id: 'brn', labelAr: 'عودي محروق', labelEn: 'Deep Agarwood Brown', value: 'brown', colorHex: '#4A2C2A', inStock: true },
        ],
      },
      {
        id: 'size',
        nameAr: 'المقاس (الطول بالإنش)',
        nameEn: 'Length Size',
        type: 'size',
        options: [
          { id: '56', labelAr: '56 إنش', labelEn: '56 Inches', value: '56', inStock: true },
          { id: '58', labelAr: '58 إنش', labelEn: '58 Inches', value: '58', inStock: true },
          { id: '60', labelAr: '60 إنش', labelEn: '60 Inches', value: '60', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'نوع الزري', keyEn: 'Zari Thread', valueAr: 'زري ألماني حر مطلي بذهب عيار ٢٤ بضمان ١٠ سنوات', valueEn: '24K Gold-Plated German Zari (10-Year Guarantee)' },
      { keyAr: 'خدمة الخبن', keyEn: 'Custom Tailoring', valueAr: 'يشمل خبن مجاني حسب طول العميل وتبخير بالعود الملكي', valueEn: 'Includes complimentary custom hemming & royal oud scenting' },
    ],
    warrantyAr: 'ضمان ١٠ سنوات على ثبات ولمعان الزري الألماني',
    warrantyEn: '10-Year Guarantee on German Zari brilliance',
    deliveryEstimateAr: 'توصيل خلال ٢٤-٤٨ ساعة في صندوق إهداء فاخر',
    deliveryEstimateEn: '24-48h delivery in luxury presentation chest',
    isFlashDeal: false,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    isSeasonal: true,
    createdAt: '2026-08-08',
  },
  {
    id: 'prod-26',
    sku: 'ATH-MEN-002',
    titleAr: 'شماغ سويسري ملكي قطن جيزان المصري ١٠٠٪ - إصدار النخبة الخاص ٢٠٢٦',
    titleEn: 'Royal Swiss-Woven Shemagh in 100% Giza Sea-Island Cotton - 2026 Elite Edition',
    descriptionAr:
      'شماغ فاخر منسوج في سويسرا من أجود خيوط القطن الطبيعي الطويل التيلة، يتميز بتطابق تام للأطراف وثبات المرزام ونقشة حمراء ملكية كلاسيكية.',
    descriptionEn:
      'Woven in Switzerland from 100% long-staple Sea-Island cotton with symmetrical edge alignment and crisp structure.',
    categoryId: 'mens-fashion',
    subcategoryAr: 'الأشمغة والغتر الفاخرة',
    subcategoryEn: 'Luxury Shemaghs & Ghutras',
    brandId: 'brand-najd',
    brandNameAr: 'أتيليه نجد الملكي',
    brandNameEn: 'Najd Royal Atelier',
    sellerId: 'seller-4',
    sellerNameAr: 'أتيليه نجد للأزياء والعبايات',
    sellerNameEn: 'Najd Couture & Royal Attire',
    sellerRating: 4.85,
    sellerVerified: true,
    price: 490,
    originalPrice: 620,
    discountPercent: 21,
    stock: 60,
    lowStockThreshold: 12,
    status: 'active',
    rating: 4.9,
    reviewCount: 210,
    soldCount: 950,
    images: [
      'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'size',
        nameAr: 'المقاس',
        nameEn: 'Size',
        type: 'size',
        options: [
          { id: '55', labelAr: '55', labelEn: 'Size 55', value: '55', inStock: true },
          { id: '58', labelAr: '58', labelEn: 'Size 58', value: '58', inStock: true },
          { id: '60', labelAr: '60', labelEn: 'Size 60', value: '60', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'الخامة', keyEn: 'Material', valueAr: '١٠٠٪ قطن طبيعي نقي بمعيار حياكة سويسري', valueEn: '100% Pure Long-Staple Cotton (Swiss Loom)' },
    ],
    warrantyAr: 'ضمان تطابق الأطراف وثبات اللون بعد الغسيل',
    warrantyEn: 'Edge Alignment & Colorfastness Guarantee',
    deliveryEstimateAr: 'توصيل خلال ٢٤ ساعة',
    deliveryEstimateEn: '24-hour delivery',
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-03T23:59:59Z',
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    createdAt: '2026-09-03',
  },
  {
    id: 'prod-27',
    sku: 'ATH-MEN-003',
    titleAr: 'حذاء شرقي إيطالي مصنوع يدوياً من جلد النعام الطبيعي المبطن - بني كوجاك',
    titleEn: 'Handcrafted Italian Oriental Sandals in Genuine Ostrich Leather - Cognac Brown',
    descriptionAr:
      'حذاء شرقي فاخر مصنوع يدوياً في إيطاليا من جلد النعام الطبيعي ١٠٠٪ مع بطانة طبية مريحة للمشي الطويل ونعل مانع للانزلاق.',
    descriptionEn:
      'Artisanal oriental footwear handcrafted in Italy from genuine full-quill ostrich leather with orthopedic memory-foam footbed.',
    categoryId: 'mens-fashion',
    subcategoryAr: 'الأحذية الجلدية الإيطالية',
    subcategoryEn: 'Italian Leather Shoes',
    brandId: 'brand-najd',
    brandNameAr: 'أتيليه نجد الملكي',
    brandNameEn: 'Najd Royal Atelier',
    sellerId: 'seller-4',
    sellerNameAr: 'أتيليه نجد للأزياء والعبايات',
    sellerNameEn: 'Najd Couture & Royal Attire',
    sellerRating: 4.85,
    sellerVerified: true,
    price: 1390,
    originalPrice: 1750,
    discountPercent: 21,
    stock: 22,
    lowStockThreshold: 5,
    status: 'active',
    rating: 4.85,
    reviewCount: 74,
    soldCount: 210,
    images: [
      'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'size',
        nameAr: 'المقاس الأوروبي',
        nameEn: 'EU Shoe Size',
        type: 'size',
        options: [
          { id: '41', labelAr: '41 EU', labelEn: '41 EU', value: '41', inStock: true },
          { id: '42', labelAr: '42 EU', labelEn: '42 EU', value: '42', inStock: true },
          { id: '43', labelAr: '43 EU', labelEn: '43 EU', value: '43', inStock: true },
          { id: '44', labelAr: '44 EU', labelEn: '44 EU', value: '44', inStock: true },
          { id: '45', labelAr: '45 EU', labelEn: '45 EU', value: '45', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'نوع الجلد', keyEn: 'Leather Type', valueAr: 'جلد نعام طبيعي ١٠٠٪ مدبوغ في توسكانا - إيطاليا', valueEn: '100% Genuine Tuscan Ostrich Leather' },
    ],
    warrantyAr: 'استبدال المقاس مجاناً خلال ١٤ يوماً',
    warrantyEn: 'Free 14-day size exchange',
    deliveryEstimateAr: 'توصيل خلال ٢٤-٤٨ ساعة',
    deliveryEstimateEn: '24-48h delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-08-20',
  },
  {
    id: 'prod-28',
    sku: 'ATH-MEN-004',
    titleAr: 'حقيبة أعمال ومحفظة بطاقات من الجلد الإيطالي الفاخر مع حماية RFID - أسود كافيار',
    titleEn: 'Executive Italian Full-Grain Leather Briefcase & RFID Cardholder Set - Caviar Black',
    descriptionAr:
      'طقم رجال الأعمال التنفيذي المكون من حقيبة لابتوب ١٦ إنش ومحفظة بطاقات نحيفة من الجلد الإيطالي الفاخر المقاوم للخدوش.',
    descriptionEn:
      'Executive matching set including a 16-inch full-grain leather document briefcase and an RFID-shielded slim cardholder.',
    categoryId: 'mens-fashion',
    subcategoryAr: 'المحافظ والحقائب الجلدية',
    subcategoryEn: 'Leather Wallets & Briefcases',
    brandId: 'brand-najd',
    brandNameAr: 'أتيليه نجد الملكي',
    brandNameEn: 'Najd Royal Atelier',
    sellerId: 'seller-4',
    sellerNameAr: 'أتيليه نجد للأزياء والعبايات',
    sellerNameEn: 'Najd Couture & Royal Attire',
    sellerRating: 4.85,
    sellerVerified: true,
    price: 1580,
    originalPrice: 1950,
    discountPercent: 19,
    stock: 15,
    lowStockThreshold: 4,
    status: 'active',
    rating: 4.8,
    reviewCount: 36,
    soldCount: 98,
    images: [
      'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Color',
        type: 'color',
        options: [
          { id: 'blk', labelAr: 'أسود كافيار', labelEn: 'Caviar Black', value: 'black', colorHex: '#141413', inStock: true },
          { id: 'esp', labelAr: 'بني إسبريسو', labelEn: 'Espresso Brown', value: 'brown', colorHex: '#3E2723', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'السعة', keyEn: 'Capacity', valueAr: 'يتسع لحاسوب ١٦ بوصة ومستندات A4 مع قفل رقمي', valueEn: 'Fits 16" MacBook Pro & A4 Documents' },
    ],
    warrantyAr: 'ضمان ٣ سنوات على الجلد والسحابات المعدنية',
    warrantyEn: '3-Year Leather & Hardware Warranty',
    deliveryEstimateAr: 'توصيل خلال ٢٤-٤٨ ساعة',
    deliveryEstimateEn: '24-48h delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: true,
    createdAt: '2026-09-08',
  },

  // 29-32: WOMEN'S COUTURE & ABAYAS (seller-4: أتيليه نجد للأزياء والعبايات)
  {
    id: 'prod-29',
    sku: 'ATH-WOM-001',
    titleAr: 'عباية كوتور نجدي من الحرير الياباني الطبيعي مع تطريز يدوي بخيوط القصب الذهبي',
    titleEn: 'Najdi Couture Natural Japanese Silk Abaya with Hand-Spun Gold Embroidery',
    descriptionAr:
      'عباية مناسبات فاخرة مصممة بقصة بشت انسيابية من قماش الحرير الياباني المغسول، مزينة بتطريز يدوي مستوحى من أبواب الدرعية التراثية مع طرحة شيفون حرير مطابقة.',
    descriptionEn:
      'Haute couture bisht-cut abaya tailored from breathable Japanese washed silk, featuring hand-embroidered Diriyah geometric gold motifs and matching silk shayla.',
    categoryId: 'womens-fashion',
    subcategoryAr: 'عبايات الكوتور والحرير',
    subcategoryEn: 'Couture & Silk Abayas',
    brandId: 'brand-najd',
    brandNameAr: 'أتيليه نجد الملكي',
    brandNameEn: 'Najd Royal Atelier',
    sellerId: 'seller-4',
    sellerNameAr: 'أتيليه نجد للأزياء والعبايات',
    sellerNameEn: 'Najd Couture & Royal Attire',
    sellerRating: 4.85,
    sellerVerified: true,
    price: 2450,
    originalPrice: 2950,
    discountPercent: 17,
    stock: 16,
    lowStockThreshold: 4,
    status: 'active',
    rating: 4.95,
    reviewCount: 128,
    soldCount: 340,
    images: [
      'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=1000&q=85',
      'https://images.unsplash.com/photo-1591561954557-26941169b49e?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'size',
        nameAr: 'المقاس',
        nameEn: 'Abaya Size',
        type: 'size',
        options: [
          { id: '52', labelAr: '52', labelEn: 'Size 52', value: '52', inStock: true },
          { id: '54', labelAr: '54', labelEn: 'Size 54', value: '54', inStock: true },
          { id: '56', labelAr: '56', labelEn: 'Size 56', value: '56', inStock: true },
          { id: '58', labelAr: '58', labelEn: 'Size 58', value: '58', inStock: true },
        ],
      },
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Color',
        type: 'color',
        options: [
          { id: 'blk', labelAr: 'أسود ملكي مطرز بالذهب', labelEn: 'Royal Black & Gold', value: 'black', colorHex: '#141413', inStock: true },
          { id: 'emr', labelAr: 'زيتي عميق مطرز بالذهب', labelEn: 'Deep Olive Emerald & Gold', value: 'emerald', colorHex: '#1E3A2F', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'القماش', keyEn: 'Fabric', valueAr: 'حرير ياباني طبيعي بارد ومقاوم للتجعد', valueEn: 'Wrinkle-resistant Japanese Natural Silk' },
      { keyAr: 'الملحقات', keyEn: 'Included', valueAr: 'طرحة حرير مطرزة + حافظة عباية للسفر + عطر القماش الخاص', valueEn: 'Embroidered Silk Shayla + Garment Bag + Linen Mist' },
    ],
    warrantyAr: 'تعديل الطول مجاناً واستبدال فوري خلال ١٤ يوماً',
    warrantyEn: 'Complimentary length alteration & 14-day exchange',
    deliveryEstimateAr: 'توصيل خلال ٢٤-٤٨ ساعة في علبة كوتور فاخرة',
    deliveryEstimateEn: '24-48h delivery in signature couture box',
    isFlashDeal: false,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    isSeasonal: true,
    frequentlyBoughtWith: ['prod-30', 'prod-33'],
    createdAt: '2026-09-02',
  },
  {
    id: 'prod-30',
    sku: 'ATH-WOM-002',
    titleAr: 'حقيبة يد نسائية من الجلد الطبيعي المبطن بقفل مطلي بالذهب عيار ١٨ - أخضر زمردي',
    titleEn: 'Quilted Calfskin Leather Top-Handle Handbag with 18K Gold Clasp - Royal Emerald',
    descriptionAr:
      'حقيبة سهرة وإطلالات يومية راقية مصنوعة من جلد العجل الناعم المبطن مع سلسلة كتف قابلة للإزالة وقفل معدني مصقول مطلي بالذهب.',
    descriptionEn:
      'Structured top-handle handbag crafted in diamond-quilted calfskin leather with 18K gold-plated hardware and detachable chain.',
    categoryId: 'womens-fashion',
    subcategoryAr: 'الحقائب الجلدية الفاخرة',
    subcategoryEn: 'Luxury Leather Handbags',
    brandId: 'brand-najd',
    brandNameAr: 'أتيليه نجد الملكي',
    brandNameEn: 'Najd Royal Atelier',
    sellerId: 'seller-4',
    sellerNameAr: 'أتيليه نجد للأزياء والعبايات',
    sellerNameEn: 'Najd Couture & Royal Attire',
    sellerRating: 4.85,
    sellerVerified: true,
    price: 3150,
    originalPrice: 3800,
    discountPercent: 17,
    stock: 9,
    lowStockThreshold: 2,
    status: 'active',
    rating: 4.9,
    reviewCount: 67,
    soldCount: 145,
    images: [
      'https://images.unsplash.com/photo-1591561954557-26941169b49e?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Color',
        type: 'color',
        options: [
          { id: 'emr', labelAr: 'أخضر زمردي', labelEn: 'Royal Emerald', value: 'emerald', colorHex: '#0B4F3F', inStock: true },
          { id: 'tup', labelAr: 'بيج توب دافئ', labelEn: 'Warm Taupe', value: 'taupe', colorHex: '#B5A695', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'الأبعاد', keyEn: 'Dimensions', valueAr: '٢٤ × ١٦ × ٨ سم', valueEn: '24 x 16 x 8 cm' },
    ],
    warrantyAr: 'شهادة أصالة وضمان سنتين لدى أتيليه نجد',
    warrantyEn: 'Authenticity Card & 2-Year Boutique Warranty',
    deliveryEstimateAr: 'توصيل VIP خلال ٢٤ ساعة',
    deliveryEstimateEn: '24-hour VIP delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    createdAt: '2026-09-07',
  },
  {
    id: 'prod-31',
    sku: 'ATH-WOM-003',
    titleAr: 'عقد وأقراط من الذهب الأصفر عيار ١٨ قيراطاً مرصعة باللؤلؤ الطبيعي وحجر الزمرد',
    titleEn: '18K Solid Yellow Gold Necklace & Earrings Set with Natural Pearl & Emerald',
    descriptionAr:
      'طقم مجوهرات ناعم من الذهب الخالص عيار ١٨ قيراطاً بوزن ١١.٤ جرام، مرصع بحجر زمرد أخضر طبيعي ولؤلؤ زراعي ناصع مع فاتورة رسمية مختومة.',
    descriptionEn:
      'Fine jewelry set crafted in solid 18K yellow gold (11.4g) set with natural emerald and freshwater pearls.',
    categoryId: 'womens-fashion',
    subcategoryAr: 'المجوهرات والحلي الذهبية',
    subcategoryEn: 'Fine Jewelry & Gold',
    brandId: 'brand-najd',
    brandNameAr: 'أتيليه نجد الملكي',
    brandNameEn: 'Najd Royal Atelier',
    sellerId: 'seller-4',
    sellerNameAr: 'أتيليه نجد للأزياء والعبايات',
    sellerNameEn: 'Najd Couture & Royal Attire',
    sellerRating: 4.85,
    sellerVerified: true,
    price: 4680,
    originalPrice: 5200,
    discountPercent: 10,
    stock: 7,
    lowStockThreshold: 2,
    status: 'active',
    rating: 5.0,
    reviewCount: 42,
    soldCount: 79,
    images: [
      'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'stone',
        nameAr: 'الحجر الكريم',
        nameEn: 'Gemstone',
        type: 'option',
        options: [
          { id: 'emr', labelAr: 'زمرد أخضر ولؤلؤ', labelEn: 'Emerald & Pearl', value: 'emerald', inStock: true },
          { id: 'rby', labelAr: 'ياقوت أحمر ولؤلؤ', labelEn: 'Ruby & Pearl', value: 'ruby', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'العيار والوزن', keyEn: 'Gold Karat & Weight', valueAr: 'ذهب عيار ١٨ مدموغ رسمياً - ١١.٤ جرام', valueEn: 'Hallmarked 18K Solid Gold - 11.4g' },
    ],
    warrantyAr: 'مرفق فاتورة الذهب الرسمية المختومة وشهادة الأحجار الكريمة',
    warrantyEn: 'Includes Official Stamped Gold Invoice & Gem Certificate',
    deliveryEstimateAr: 'شحن مؤمّن بالكامل خلال ٢٤ ساعة',
    deliveryEstimateEn: 'Fully insured 24h courier',
    isFlashDeal: false,
    isFeatured: true,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: true,
    createdAt: '2026-09-11',
  },
  {
    id: 'prod-32',
    sku: 'ATH-WOM-004',
    titleAr: 'شال كشميري باشمينا طبيعي ١٠٠٪ مطرز يدوياً - بيج رملي دافئ',
    titleEn: '100% Pure Hand-Loomed Kashmiri Pashmina Shawl - Warm Desert Sand',
    descriptionAr:
      'شال باشمينا كشميري أصلي فائق النعومة والدفء، منسوج ومطرز يدوياً على مدار ٣ أشهر ليمنحك إطلالة شتوية ملكية.',
    descriptionEn:
      'Authentic hand-loomed Kashmiri Pashmina shawl featuring intricate Sozni needlework embroidery in a versatile desert sand hue.',
    categoryId: 'womens-fashion',
    subcategoryAr: 'الطرح والشالات الحريرية',
    subcategoryEn: 'Silk Scarves & Shawls',
    brandId: 'brand-najd',
    brandNameAr: 'أتيليه نجد الملكي',
    brandNameEn: 'Najd Royal Atelier',
    sellerId: 'seller-4',
    sellerNameAr: 'أتيليه نجد للأزياء والعبايات',
    sellerNameEn: 'Najd Couture & Royal Attire',
    sellerRating: 4.85,
    sellerVerified: true,
    price: 1450,
    originalPrice: 1850,
    discountPercent: 22,
    stock: 18,
    lowStockThreshold: 4,
    status: 'active',
    rating: 4.9,
    reviewCount: 53,
    soldCount: 132,
    images: [
      'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Color',
        type: 'color',
        options: [
          { id: 'snd', labelAr: 'بيج رملي دافئ', labelEn: 'Desert Sand', value: 'sand', colorHex: '#D8C8B8', inStock: true },
          { id: 'ivr', labelAr: 'أبيض عاجي', labelEn: 'Royal Ivory', value: 'ivory', colorHex: '#FAF8F5', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'المقاس', keyEn: 'Dimensions', valueAr: '٢٠٠ × ٧٠ سم', valueEn: '200 x 70 cm' },
    ],
    warrantyAr: 'شهادة فحص صوف الكشمير الطبيعي ١٠٠٪',
    warrantyEn: '100% Pure Cashmere Authenticity Certificate',
    deliveryEstimateAr: 'توصيل خلال ٢٤-٤٨ ساعة',
    deliveryEstimateEn: '24-48h delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: true,
    isSeasonal: true,
    createdAt: '2026-09-14',
  },
];
