import { Product } from './types';

export const SEED_PRODUCTS_PART_B: Product[] = [
  // 33-36: BEAUTY & LUXURY SKINCARE (seller-6: واحة الجمال والعناية)
  {
    id: 'prod-33',
    sku: 'ATH-BTY-001',
    titleAr: 'جهاز تصفيف الشعر دايسون إير راب ملتي ستايلر كومبليت لونج - إصدار أزرق بروسيا والنحاس',
    titleEn: 'Dyson Airwrap Multi-Styler Complete Long - Prussian Blue & Rich Copper',
    descriptionAr:
      'جهاز تصفيف الشعر الأشهر عالمياً بتقنية تدفق الهواء Coanda لتجعيد وتمويج وتنعيم الشعر بدون حرارة مفرطة، مع ٦ ملحقات متكاملة وصندوق تخزين مخملي فاخر.',
    descriptionEn:
      'Engineered for chest-length or longer hair utilizing the Coanda airflow effect to curl, shape, and smooth flyaways with no extreme heat.',
    categoryId: 'beauty',
    subcategoryAr: 'أجهزة تصفيف الشعر الاحترافية',
    subcategoryEn: 'Pro Hair Styling Devices',
    brandId: 'brand-dyson',
    brandNameAr: 'دايسون',
    brandNameEn: 'Dyson',
    sellerId: 'seller-6',
    sellerNameAr: 'واحة الجمال والعناية',
    sellerNameEn: 'Beauty Oasis Luxury Care',
    sellerRating: 4.75,
    sellerVerified: true,
    price: 2399,
    originalPrice: 2749,
    discountPercent: 13,
    stock: 31,
    lowStockThreshold: 6,
    status: 'active',
    rating: 4.9,
    reviewCount: 245,
    soldCount: 690,
    images: [
      'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Color Edition',
        type: 'color',
        options: [
          { id: 'blu', labelAr: 'أزرق بروسيا ونحاسي', labelEn: 'Prussian Blue & Copper', value: 'blue', colorHex: '#1B365D', inStock: true },
          { id: 'pnk', labelAr: 'وردي سيراميك وروز جولد', labelEn: 'Ceramic Pink & Rose Gold', value: 'pink', colorHex: '#E8B4B8', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'الجهد الكهربائي', keyEn: 'Voltage', valueAr: '٢٢٠-٢٤٠ فولت (فيش ثلاثي سعودي SASO)', valueEn: '220-240V Official Saudi 3-Pin Plug' },
      { keyAr: 'الملحقات', keyEn: 'Attachments', valueAr: '٦ ملحقات كاملة + حقيبة تخزين صلبة', valueEn: '6 Complete Attachments + Presentation Case' },
    ],
    warrantyAr: 'ضمان الوكيل الرسمي دايسون السعودية سنتين',
    warrantyEn: '2-Year Official Dyson KSA Warranty',
    deliveryEstimateAr: 'توصيل خلال ٢٤ ساعة في الرياض وجدة',
    deliveryEstimateEn: '24-hour delivery in Riyadh & Jeddah',
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-05T23:59:59Z',
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-08-04',
  },
  {
    id: 'prod-34',
    sku: 'ATH-BTY-002',
    titleAr: 'جهاز فرد وتجفيف الشعر دايسون إير ستريت بالهواء الرطب والجاف بدون ألواح ساخنة',
    titleEn: 'Dyson Airstrait Wet-to-Dry Hair Straightener - Nickel & Rich Copper',
    descriptionAr:
      'تقنية ثورية لفرد الشعر من المبلل إلى الجاف مباشرة باستخدام الهواء المتدفق عالي الضغط بدون ألواح تسخين تقليدية، لحماية لمعان وقوة الشعر الطبيعي.',
    descriptionEn:
      'Wet to dry straightening with air. No hot plates. No heat damage. directional airflow smooths and aligns hair effortlessly.',
    categoryId: 'beauty',
    subcategoryAr: 'أجهزة تصفيف الشعر الاحترافية',
    subcategoryEn: 'Pro Hair Styling Devices',
    brandId: 'brand-dyson',
    brandNameAr: 'دايسون',
    brandNameEn: 'Dyson',
    sellerId: 'seller-6',
    sellerNameAr: 'واحة الجمال والعناية',
    sellerNameEn: 'Beauty Oasis Luxury Care',
    sellerRating: 4.75,
    sellerVerified: true,
    price: 1999,
    originalPrice: 2299,
    discountPercent: 13,
    stock: 20,
    lowStockThreshold: 5,
    status: 'active',
    rating: 4.85,
    reviewCount: 112,
    soldCount: 340,
    images: [
      'https://images.unsplash.com/photo-1596462502278-27bfdc403348?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Color',
        type: 'color',
        options: [
          { id: 'nck', labelAr: 'نيكل ونحاسي', labelEn: 'Nickel & Copper', value: 'copper', colorHex: '#B87333', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'أوضاع الحرارة', keyEn: 'Heat Modes', valueAr: 'وضع رطب (٨٠°، ١١٠°، ١٤٠°) ووضع جاف (١٢٠°، ١٤٠°)', valueEn: 'Wet & Dry Precision Modes' },
    ],
    warrantyAr: 'ضمان سنتين دايسون السعودية',
    warrantyEn: '2-Year Official Warranty',
    deliveryEstimateAr: 'توصيل خلال ٢٤ ساعة',
    deliveryEstimateEn: '24-hour delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    createdAt: '2026-09-06',
  },
  {
    id: 'prod-35',
    sku: 'ATH-BTY-003',
    titleAr: 'مجموعة العناية الملكية لتجديد البشرة بالكافيار السويسري والذهب الخالص - ٤ مستحضرات',
    titleEn: 'Swiss Cellular Caviar & 24K Gold Rejuvenating Skincare Ritual - 4-Piece Luxury Set',
    descriptionAr:
      'مجموعة متكاملة للعناية الفائقة بالبشرة تضم سيروم الكافيار المشدود، كريم الليل المجدد، كريم محيط العينين، وتونر الإشراق الفوري.',
    descriptionEn:
      'Complete Swiss cellular skincare regimen including Caviar Firming Serum, Night Repair Cream, Eye Contour Elixir, and Radiance Essence.',
    categoryId: 'beauty',
    subcategoryAr: 'مجموعات العناية الفائقة بالبشرة',
    subcategoryEn: 'Luxury Skincare Sets',
    brandId: 'brand-geneva',
    brandNameAr: 'أورولوجيا جنيف',
    brandNameEn: 'Horologia Genève',
    sellerId: 'seller-6',
    sellerNameAr: 'واحة الجمال والعناية',
    sellerNameEn: 'Beauty Oasis Luxury Care',
    sellerRating: 4.75,
    sellerVerified: true,
    price: 1750,
    originalPrice: 2200,
    discountPercent: 20,
    stock: 15,
    lowStockThreshold: 4,
    status: 'active',
    rating: 4.9,
    reviewCount: 64,
    soldCount: 150,
    images: [
      'https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'skin',
        nameAr: 'نوع البشرة',
        nameEn: 'Skin Type',
        type: 'option',
        options: [
          { id: 'all', labelAr: 'جميع أنواع البشرة', labelEn: 'All Skin Types', value: 'all', inStock: true },
          { id: 'dry', labelAr: 'البشرة الجافة والحساسة', labelEn: 'Dry & Sensitive Skin', value: 'dry', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'بلد المنشأ', keyEn: 'Origin', valueAr: 'مونترو - سويسرا (مرخص من هيئة الغذاء والدواء SFDA)', valueEn: 'Montreux, Switzerland (SFDA Approved)' },
    ],
    warrantyAr: 'منتج أصلي مسجل في هيئة الغذاء والدواء السعودية',
    warrantyEn: 'SFDA Registered Authentic Product',
    deliveryEstimateAr: 'توصيل مبرد خلال ٢٤-٤٨ ساعة',
    deliveryEstimateEn: 'Chilled 24-48h delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: true,
    createdAt: '2026-09-10',
  },
  {
    id: 'prod-36',
    sku: 'ATH-BTY-004',
    titleAr: 'قناع العلاج الضوئي للوجه LED الاحترافي بتقنية الأشعة تحت الحمراء لتحفيز الكولاجين',
    titleEn: 'Clinical Pro LED & Near-Infrared Light Therapy Facial Mask for Collagen Boost',
    descriptionAr:
      'قناع سيليكون طبي مرن يستخدم ٤ أطوال موجية ضوئية (أحمر، تحت أحمر، أزرق، كهرماني) لتقليل الخطوط الدقيقة وتوحيد لون البشرة خلال ١٠ دقائق يومياً.',
    descriptionEn:
      'Medical-grade flexible silicone LED mask utilizing 4 clinical wavelengths to stimulate collagen and calm inflammation in 10 minutes a day.',
    categoryId: 'beauty',
    subcategoryAr: 'مجموعات العناية الفائقة بالبشرة',
    subcategoryEn: 'Luxury Skincare Sets',
    brandId: 'brand-dyson',
    brandNameAr: 'دايسون',
    brandNameEn: 'Dyson',
    sellerId: 'seller-6',
    sellerNameAr: 'واحة الجمال والعناية',
    sellerNameEn: 'Beauty Oasis Luxury Care',
    sellerRating: 4.75,
    sellerVerified: true,
    price: 1590,
    originalPrice: 1950,
    discountPercent: 18,
    stock: 17,
    lowStockThreshold: 4,
    status: 'active',
    rating: 4.8,
    reviewCount: 49,
    soldCount: 128,
    images: [
      'https://images.unsplash.com/photo-1512290923902-8a9f81dc236c?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'version',
        nameAr: 'الإصدار',
        nameEn: 'Edition',
        type: 'option',
        options: [
          { id: 'face', labelAr: 'قناع الوجه الكامل', labelEn: 'Full Face Mask', value: 'face', inStock: true },
          { id: 'neck', labelAr: 'قناع الوجه + الرقبة', labelEn: 'Face + Neck Bundle', value: 'bundle', priceDelta: 550, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'عدد مصابيح LED', keyEn: 'LED Count', valueAr: '١٣٢ مصباح طبي مزدوج الطيف', valueEn: '132 Medical-Grade Dual-Core LEDs' },
    ],
    warrantyAr: 'ضمان سنتين شامل الاستبدال الفوري',
    warrantyEn: '2-Year Replacement Warranty',
    deliveryEstimateAr: 'توصيل خلال ٢٤-٤٨ ساعة',
    deliveryEstimateEn: '24-48h delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    isNewArrival: true,
    createdAt: '2026-09-12',
  },

  // 37-40: KIDS & BABY LUXURY (seller-6: واحة الجمال والعناية)
  {
    id: 'prod-37',
    sku: 'ATH-KID-001',
    titleAr: 'عربة أطفال للسفر والطيران بلمسة واحدة مع مهد مواليد ومقعد سيارة آيزوفكس - بيج رملي',
    titleEn: 'First-Class Cabin-Approved Baby Stroller & ISOFIX Car Seat Travel System - Sand Beige',
    descriptionAr:
      'نظام تنقل متكامل للمواليد والأطفال، يطوى بيد واحدة خلال ثانية ليدخل مقصورة الطائرة، مع أقمشة عضوية مضادة للحساسية ومظلة واقية من الشمس UPF 50+.',
    descriptionEn:
      'Complete 3-in-1 luxury travel system featuring a one-hand fold cabin stroller, bassinet, and ADAC-tested ISOFIX infant car seat.',
    categoryId: 'kids',
    subcategoryAr: 'عربات الأطفال ومقاعد السيارات',
    subcategoryEn: 'Strollers & Car Seats',
    brandId: 'brand-najd',
    brandNameAr: 'أتيليه نجد الملكي',
    brandNameEn: 'Najd Royal Atelier',
    sellerId: 'seller-6',
    sellerNameAr: 'واحة الجمال والعناية',
    sellerNameEn: 'Beauty Oasis Luxury Care',
    sellerRating: 4.75,
    sellerVerified: true,
    price: 3490,
    originalPrice: 4200,
    discountPercent: 17,
    stock: 10,
    lowStockThreshold: 3,
    status: 'active',
    rating: 4.9,
    reviewCount: 73,
    soldCount: 165,
    images: [
      'https://images.unsplash.com/photo-1515488042361-ee00e0ddd4e4?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Color',
        type: 'color',
        options: [
          { id: 'snd', labelAr: 'بيج رملي وهيكل روز جولد', labelEn: 'Desert Sand & Rose Gold Frame', value: 'sand', colorHex: '#D6C7B2', inStock: true },
          { id: 'blk', labelAr: 'أسود أونيكس وهيكل كروم', labelEn: 'Onyx Black & Chrome Frame', value: 'black', colorHex: '#1F1F1F', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'الوزن', keyEn: 'Stroller Weight', valueAr: '٦.٢ كجم معتمدة في مقصورة الخطوط السعودية والعالمية', valueEn: '6.2 kg Cabin Approved' },
    ],
    warrantyAr: 'ضمان ٣ سنوات شامل قطع الغيار',
    warrantyEn: '3-Year Comprehensive Warranty',
    deliveryEstimateAr: 'توصيل مجاني خلال ٢٤-٤٨ ساعة',
    deliveryEstimateEn: 'Free 24-48h delivery',
    isFlashDeal: false,
    isFeatured: true,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-08-15',
  },
  {
    id: 'prod-38',
    sku: 'ATH-KID-002',
    titleAr: 'حقيبة البرمجة والروبوتات التعليمية الذكية للأطفال STEM (٨ - ١٤ سنة)',
    titleEn: 'Interactive AI Robotics & STEM Coding Master Kit for Kids (Ages 8-14)',
    descriptionAr:
      'مجموعة تعليمية تفاعلية تتيح للطفل بناء وبرمجة ٥ روبوتات ذكية باستخدام تطبيق عربي/إنجليزي مبسط لتنمية مهارات التفكير الهندسي والذكاء الاصطناعي.',
    descriptionEn:
      'Hands-on STEM robotics kit enabling children to build and code 5 modular smart robots with bilingual Arabic/English app tutorials.',
    categoryId: 'kids',
    subcategoryAr: 'الألعاب التعليمية والتركيب',
    subcategoryEn: 'STEM & Building Sets',
    brandId: 'brand-sony',
    brandNameAr: 'سوني',
    brandNameEn: 'Sony',
    sellerId: 'seller-6',
    sellerNameAr: 'واحة الجمال والعناية',
    sellerNameEn: 'Beauty Oasis Luxury Care',
    sellerRating: 4.75,
    sellerVerified: true,
    price: 680,
    originalPrice: 850,
    discountPercent: 20,
    stock: 34,
    lowStockThreshold: 6,
    status: 'active',
    rating: 4.85,
    reviewCount: 82,
    soldCount: 270,
    images: [
      'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'pack',
        nameAr: 'الحزمة',
        nameEn: 'Kit Edition',
        type: 'option',
        options: [
          { id: 'std', labelAr: 'الحزمة القياسية (5 روبوتات)', labelEn: 'Standard Kit (5 Robots)', value: 'std', inStock: true },
          { id: 'pro', labelAr: 'حزمة المبتكر الصغير (10 روبوتات)', labelEn: 'Pro Inventor Kit (10 Robots)', value: 'pro', priceDelta: 220, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'الفئة العمرية', keyEn: 'Age Range', valueAr: '٨ إلى ١٤ سنة', valueEn: '8 to 14 Years' },
    ],
    warrantyAr: 'ضمان سنة كاملة',
    warrantyEn: '1-Year Warranty',
    deliveryEstimateAr: 'توصيل خلال ٢٤-٤٨ ساعة',
    deliveryEstimateEn: '24-48h delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    createdAt: '2026-09-05',
  },
  {
    id: 'prod-39',
    sku: 'ATH-KID-003',
    titleAr: 'جهاز مراقبة الطفل الذكي بكاميرا 2K ليلي وتتبع التنفس ودرجة حرارة الغرفة',
    titleEn: 'Smart 2K HD Baby Monitor with Breathing Motion Tracking & Cry Detection',
    descriptionAr:
      'كاميرا مراقبة ذكية للمواليد بدقة 2K ورؤية ليلية فائقة الوضوح، تتابع تنفس الطفل وحرارة ورطوبة الغرفة مع شاشة مخصصة ٥ إنش وتطبيق للهاتف.',
    descriptionEn:
      'Crystal-clear 2K baby monitor with sensor-free breathing motion tracking, room climate alerts, 5" parent unit, and encrypted phone app.',
    categoryId: 'kids',
    subcategoryAr: 'أجهزة مراقبة وغرف المواليد',
    subcategoryEn: 'Baby Monitors & Nursery',
    brandId: 'brand-apple',
    brandNameAr: 'آبل',
    brandNameEn: 'Apple',
    sellerId: 'seller-6',
    sellerNameAr: 'واحة الجمال والعناية',
    sellerNameEn: 'Beauty Oasis Luxury Care',
    sellerRating: 4.75,
    sellerVerified: true,
    price: 1150,
    originalPrice: 1390,
    discountPercent: 17,
    stock: 19,
    lowStockThreshold: 4,
    status: 'active',
    rating: 4.9,
    reviewCount: 47,
    soldCount: 130,
    images: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'mount',
        nameAr: 'حامل التثبيت',
        nameEn: 'Mount Type',
        type: 'option',
        options: [
          { id: 'wall', labelAr: 'حامل جداري + مكتبي', labelEn: 'Wall + Desk Stand', value: 'wall', inStock: true },
          { id: 'flr', labelAr: 'مع حامل أرضي مرتفع للسرير', labelEn: 'With Floor Crib Stand', value: 'floor', priceDelta: 190, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'الأمان والخصوصية', keyEn: 'Security', valueAr: 'تشفير AES 256-bit مزدوج لحماية الخصوصية', valueEn: '256-bit AES Encrypted Streaming' },
    ],
    warrantyAr: 'ضمان سنتين',
    warrantyEn: '2-Year Warranty',
    deliveryEstimateAr: 'توصيل خلال ٢٤-٤٨ ساعة',
    deliveryEstimateEn: '24-48h delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: false,
    createdAt: '2026-08-25',
  },
  {
    id: 'prod-40',
    sku: 'ATH-KID-004',
    titleAr: 'مقعد سيارة للأطفال دوار ٣٦٠ درجة بنظام ISOFIX وحماية جانبية متقدمة (٠ - ١٢ سنة)',
    titleEn: '360° Swivel All-Stage ISOFIX Convertible Child Car Seat (0 to 12 Years)',
    descriptionAr:
      'مقعد أمان للسيارة ينمو مع طفلك منذ الولادة حتى ١٢ سنة، يتميز بدوران ٣٦٠ درجة لسهولة إركاب الطفل وأقمشة الخيزران الباردة المناسبة لأجواء الصيف.',
    descriptionEn:
      'One-hand 360-degree rotational ISOFIX car seat engineered with side-impact air cushions and breathable bamboo fabric.',
    categoryId: 'kids',
    subcategoryAr: 'عربات الأطفال ومقاعد السيارات',
    subcategoryEn: 'Strollers & Car Seats',
    brandId: 'brand-najd',
    brandNameAr: 'أتيليه نجد الملكي',
    brandNameEn: 'Najd Royal Atelier',
    sellerId: 'seller-6',
    sellerNameAr: 'واحة الجمال والعناية',
    sellerNameEn: 'Beauty Oasis Luxury Care',
    sellerRating: 4.75,
    sellerVerified: true,
    price: 1690,
    originalPrice: 2050,
    discountPercent: 18,
    stock: 14,
    lowStockThreshold: 3,
    status: 'active',
    rating: 4.85,
    reviewCount: 55,
    soldCount: 140,
    images: [
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Color',
        type: 'color',
        options: [
          { id: 'gry', labelAr: 'رمادي فحمي', labelEn: 'Charcoal Grey', value: 'grey', colorHex: '#3F3F46', inStock: true },
          { id: 'tau', labelAr: 'بيج رملي', labelEn: 'Warm Sand', value: 'sand', colorHex: '#C5B8A5', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'شهادة الأمان', keyEn: 'Safety Standard', valueAr: 'معتمد وفق المعيار الأوروبي الأحدث ECE R129 (i-Size)', valueEn: 'Certified European i-Size ECE R129' },
    ],
    warrantyAr: 'ضمان ٣ سنوات واستبدال مجاني في حال الحوادث',
    warrantyEn: '3-Year Warranty & Crash Exchange Guarantee',
    deliveryEstimateAr: 'توصيل خلال ٢٤-٤٨ ساعة',
    deliveryEstimateEn: '24-48h delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-08-29',
  },

  // 41-44: GOURMET & FINE PANTRY (seller-8: تمور وخيرات القصيم الملكية & seller-5)
  {
    id: 'prod-41',
    sku: 'ATH-GRM-001',
    titleAr: 'صندوق تمور المجدول والسكري الملكي الفاخر محشو بالمكسرات والطحينة السائلة - ٣ كجم',
    titleEn: 'Royal Qassim Majdool & Sukkari Dates VIP Hospitality Chest - 3 kg Assortment',
    descriptionAr:
      'تشكيلة ضيافة ملكية منتقاة حبة بحبة من مزارع القصيم العضوية، تشمل مجدول جامبو ملكي، سكري مفتل فاخر، وتمور محشوة بالبيكان والفستق واللوز المحمص.',
    descriptionEn:
      'Hand-picked jumbo Qassim Majdool and golden Sukkari dates paired with artisan pecan, pistachio, and tahini-filled assortments.',
    categoryId: 'supermarket',
    subcategoryAr: 'التمور الملكية وصناديق الضيافة',
    subcategoryEn: 'Royal Dates & Gift Boxes',
    brandId: 'brand-qassim',
    brandNameAr: 'خيرات القصيم الملكية',
    brandNameEn: 'Qassim Royal Harvest',
    sellerId: 'seller-5',
    sellerNameAr: 'رواق القهوة والمنزل الفاخر',
    sellerNameEn: 'Rawaq Specialty Coffee & Living',
    sellerRating: 4.9,
    sellerVerified: true,
    price: 390,
    originalPrice: 480,
    discountPercent: 19,
    stock: 75,
    lowStockThreshold: 15,
    status: 'active',
    rating: 4.95,
    reviewCount: 312,
    soldCount: 1420,
    images: [
      'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'weight',
        nameAr: 'الحجم',
        nameEn: 'Box Weight',
        type: 'capacity',
        options: [
          { id: '1.5kg', labelAr: 'صندوق ضيافة (1.5 كجم)', labelEn: 'Hospitality Box (1.5 kg)', value: '1.5kg', priceDelta: -160, inStock: true },
          { id: '3kg', labelAr: 'صندوق المراسم الملكي (3 كجم)', labelEn: 'Royal VIP Chest (3 kg)', value: '3kg', priceDelta: 0, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'المصدر', keyEn: 'Origin', valueAr: 'مزارع القصيم العضوية المعتمدة - محصول الموسم الجديد', valueEn: 'Certified Organic Qassim Farms - Fresh Harvest' },
    ],
    warrantyAr: 'شحن مبرد ومضمون الطزاجة ١٠٠٪',
    warrantyEn: '100% Freshness Guarantee via Chilled Courier',
    deliveryEstimateAr: 'توصيل مبرد خلال ٢٤ ساعة',
    deliveryEstimateEn: 'Chilled 24-hour delivery',
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-03T23:59:59Z',
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    isSeasonal: true,
    createdAt: '2026-08-10',
  },
  {
    id: 'prod-42',
    sku: 'ATH-GRM-002',
    titleAr: 'عسل سدر جبلي ملكي حر من مناحل رجال ألمع وعسير مع شهادة فحص المختبر - ١ كجم',
    titleEn: 'Pure Wild Mountain Sidr Honey from Rijal Almaa & Asir Apiaries - 1 kg Lab Certified',
    descriptionAr:
      'عسل سدر جبلي طبيعي ١٠٠٪ خام وغير مبستر من أودية رجال ألمع ومنطقة عسير، غني بالإنزيمات الحيوية ومرفق بشهادة فحص مختبر جودة العسل المعتمدة.',
    descriptionEn:
      '100% raw, unpasteurized wild mountain Sidr honey harvested from Rijal Almaa in Asir, accompanied by an official laboratory purity certificate.',
    categoryId: 'supermarket',
    subcategoryAr: 'العسل الطبيعي والزعفران الفاخر',
    subcategoryEn: 'Pure Honey & Saffron',
    brandId: 'brand-qassim',
    brandNameAr: 'خيرات القصيم الملكية',
    brandNameEn: 'Qassim Royal Harvest',
    sellerId: 'seller-5',
    sellerNameAr: 'رواق القهوة والمنزل الفاخر',
    sellerNameEn: 'Rawaq Specialty Coffee & Living',
    sellerRating: 4.9,
    sellerVerified: true,
    price: 540,
    originalPrice: 680,
    discountPercent: 21,
    stock: 48,
    lowStockThreshold: 10,
    status: 'active',
    rating: 4.95,
    reviewCount: 184,
    soldCount: 620,
    images: [
      'https://images.unsplash.com/photo-1587049352847-4a222e784d38?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'weight',
        nameAr: 'الوزن',
        nameEn: 'Weight',
        type: 'capacity',
        options: [
          { id: '500g', labelAr: 'نصف كيلو (500 جرام)', labelEn: '500 Grams', value: '500g', priceDelta: -250, inStock: true },
          { id: '1kg', labelAr: 'كيلو كامل (1000 جرام)', labelEn: '1 Kilogram', value: '1kg', priceDelta: 0, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'فحص المختبر', keyEn: 'Lab Test', valueAr: 'نسبة السكروز أقل من ١.٢٪ (خام طبيعي ١٠٠٪)', valueEn: 'Sucrose < 1.2% (100% Raw & Pure)' },
    ],
    warrantyAr: 'الضمان الذهبي لاسترجاع أضعاف القيمة إذا ثبت غير طبيعي',
    warrantyEn: 'Full Lab Purity & Money-Back Guarantee',
    deliveryEstimateAr: 'توصيل مبرد خلال ٢٤ ساعة',
    deliveryEstimateEn: 'Chilled 24h delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    isSeasonal: true,
    createdAt: '2026-08-14',
  },
  {
    id: 'prod-43',
    sku: 'ATH-GRM-003',
    titleAr: 'زعفران سوبر نقيل ملكي درجة أولى في علبة كريستال ومطحنة نحاسية - ٢٥ جرام',
    titleEn: 'Royal Super Negin Grade-A Saffron Threads in Crystal Jar with Brass Grinder - 25g',
    descriptionAr:
      'خيوط زعفران سوبر نقيل حمراء نقية ١٠٠٪ ذات قوة صبغ ورائحة عطرية فائقة للقهوة السعودية والضيافة الفاخرة، تأتي مع مطحنة زعفران نحاسية تقليدية.',
    descriptionEn:
      'All-red Super Negin saffron filaments with maximum crocin coloring and safranal aroma for authentic Saudi coffee.',
    categoryId: 'supermarket',
    subcategoryAr: 'العسل الطبيعي والزعفران الفاخر',
    subcategoryEn: 'Pure Honey & Saffron',
    brandId: 'brand-qassim',
    brandNameAr: 'خيرات القصيم الملكية',
    brandNameEn: 'Qassim Royal Harvest',
    sellerId: 'seller-5',
    sellerNameAr: 'رواق القهوة والمنزل الفاخر',
    sellerNameEn: 'Rawaq Specialty Coffee & Living',
    sellerRating: 4.9,
    sellerVerified: true,
    price: 420,
    originalPrice: 520,
    discountPercent: 19,
    stock: 55,
    lowStockThreshold: 10,
    status: 'active',
    rating: 4.9,
    reviewCount: 140,
    soldCount: 510,
    images: [
      'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'weight',
        nameAr: 'الوزن',
        nameEn: 'Weight',
        type: 'capacity',
        options: [
          { id: '10g', labelAr: '10 جرام', labelEn: '10 Grams', value: '10g', priceDelta: -220, inStock: true },
          { id: '25g', labelAr: '25 جرام ملكي + مطحنة نحاسية', labelEn: '25g Royal + Brass Grinder', value: '25g', priceDelta: 0, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'درجة الجودة', keyEn: 'ISO Grade', valueAr: 'الدرجة الأولى ISO 3632 (قوة تلوين > 270)', valueEn: 'ISO 3632 Category I (Crocin > 270)' },
    ],
    warrantyAr: 'ضمان الجودة والنقاء ١٠٠٪',
    warrantyEn: '100% Purity Guarantee',
    deliveryEstimateAr: 'توصيل خلال ٢٤ ساعة',
    deliveryEstimateEn: '24-hour delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-08-21',
  },
  {
    id: 'prod-44',
    sku: 'ATH-GRM-004',
    titleAr: 'صندوق محاصيل القهوة المختصة والبن الخولاني السعودي الفاخر - ٤ محاصيل (١ كجم)',
    titleEn: 'Specialty Coffee & Saudi Jazan Khawlani Beans Tasting Box - 4 Single Origins (1 kg)',
    descriptionAr:
      'بوكس التذوق الفاخر لعشاق القهوة المختصة والقهوة السعودية، يضم بن خولاني جبلي من جازان، إثيوبيا ييرغاشيف، كولومبيا سوبريمو، وكوستاريكا ترازو محمصة طازجة.',
    descriptionEn:
      'Curated roaster box featuring authentic Saudi Jazan Khawlani beans alongside Ethiopian Yirgacheffe, Colombian, and Costa Rican single origins.',
    categoryId: 'supermarket',
    subcategoryAr: 'محاصيل القهوة المختصة والهيل',
    subcategoryEn: 'Specialty Coffee & Cardamom',
    brandId: 'brand-breville',
    brandNameAr: 'بريفيل ولامارزوكو',
    brandNameEn: 'La Marzocco & Breville',
    sellerId: 'seller-5',
    sellerNameAr: 'رواق القهوة والمنزل الفاخر',
    sellerNameEn: 'Rawaq Specialty Coffee & Living',
    sellerRating: 4.9,
    sellerVerified: true,
    price: 265,
    originalPrice: 320,
    discountPercent: 17,
    stock: 90,
    lowStockThreshold: 15,
    status: 'active',
    rating: 4.9,
    reviewCount: 228,
    soldCount: 890,
    images: [
      'https://images.unsplash.com/photo-1559056199-641a0ac8b55e?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'grind',
        nameAr: 'درجة الطحن',
        nameEn: 'Grind Option',
        type: 'option',
        options: [
          { id: 'whl', labelAr: 'حبوب كاملة (Whole Bean)', labelEn: 'Whole Beans', value: 'whole', inStock: true },
          { id: 'v60', labelAr: 'مطحون للتقطير V60', labelEn: 'Filter / V60 Grind', value: 'v60', inStock: true },
          { id: 'esp', labelAr: 'مطحون للإسبريسو', labelEn: 'Espresso Grind', value: 'espresso', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'تاريخ التحميص', keyEn: 'Roast Date', valueAr: 'تحميص أسبوعي طازج في محمصة رواق بالخبر', valueEn: 'Freshly roasted weekly in Al Khobar' },
    ],
    warrantyAr: 'ضمان التحميص الطازج',
    warrantyEn: 'Fresh Roast Guarantee',
    deliveryEstimateAr: 'توصيل خلال ٢٤ ساعة',
    deliveryEstimateEn: '24-hour delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    createdAt: '2026-09-14',
  },

  // 45-48: SPORTS & SMART FITNESS (seller-7: صحارى للرحلات والرياضة)
  {
    id: 'prod-45',
    sku: 'ATH-SPT-001',
    titleAr: 'مضرب بادل احترافي كاربون فايبر 18K مع حقيبة حرارية مبطنة وكرات بطولة',
    titleEn: 'Pro Tour 18K Carbon Fiber Padel Racket with Thermal Bag & Tournament Balls',
    descriptionAr:
      'مضرب بادل احترافي مصمم للاعبين المتقدمين والمحترفين، مصنوع من ألياف الكربون 18K وقلب EVA عالي الكثافة لتحقيق أقصى قوة في الضربات الساحقة مع تحكم فائق.',
    descriptionEn:
      'Tour-level 18K aluminized carbon fiber Padel racket with high-memory EVA core, rough 3D spin surface, and insulated thermo racket bag.',
    categoryId: 'sports',
    subcategoryAr: 'مضارب ومعدات البادل الاحترافية',
    subcategoryEn: 'Pro Padel Rackets & Gear',
    brandId: 'brand-ecoflow',
    brandNameAr: 'إيكو فلو وصحارى',
    brandNameEn: 'EcoFlow & Sahara',
    sellerId: 'seller-7',
    sellerNameAr: 'صحارى للرحلات والرياضة',
    sellerNameEn: 'Sahara Overland & Pro Sports',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 1380,
    originalPrice: 1750,
    discountPercent: 21,
    stock: 29,
    lowStockThreshold: 6,
    status: 'active',
    rating: 4.9,
    reviewCount: 116,
    soldCount: 380,
    images: [
      'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'shape',
        nameAr: 'شكل المضرب والتوازن',
        nameEn: 'Racket Balance',
        type: 'option',
        options: [
          { id: 'dmd', labelAr: 'ماسي (قوة هجومية Power)', labelEn: 'Diamond (Attack Power)', value: 'diamond', inStock: true },
          { id: 'trd', labelAr: 'دمعة (متوازن هجوم ودفاع)', labelEn: 'Teardrop (All-Round)', value: 'teardrop', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'الوزن', keyEn: 'Weight', valueAr: '٣٦٠ - ٣٧٠ جرام متوازن بدقة', valueEn: '360 - 370g Precision Balanced' },
    ],
    warrantyAr: 'ضمان سنة ضد عيوب التصنيع',
    warrantyEn: '1-Year Manufacturer Warranty',
    deliveryEstimateAr: 'توصيل خلال ٢٤ ساعة في الرياض وجدة والشرقية',
    deliveryEstimateEn: '24h delivery in Riyadh, Jeddah & Eastern Province',
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-04T23:59:59Z',
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    createdAt: '2026-09-01',
  },
  {
    id: 'prod-46',
    sku: 'ATH-SPT-002',
    titleAr: 'طقم دامبلز قابلة للتعديل الفوري من ٢ إلى ٣٢ كجم مع حامل معدني مدمج للنادي المنزلي',
    titleEn: 'Quick-Select Adjustable Dumbbells Pair (2kg to 32kg Each) with Ergonomic Rack Stand',
    descriptionAr:
      'استبدل ١٦ زوجاً من الأوزان بطقم واحد ذكي يوفر المساحة في منزلك، يتغير الوزن خلال ثانية واحدة بلف المقبض بزيادات دقيقة ٢ كجم.',
    descriptionEn:
      'Replace 16 pairs of free weights with one precision CNC-machined adjustable dumbbell system with single-twist 2kg increments and heavy-duty stand.',
    categoryId: 'sports',
    subcategoryAr: 'أجهزة اللياقة المنزلية الذكية',
    subcategoryEn: 'Smart Home Gym Equipment',
    brandId: 'brand-ecoflow',
    brandNameAr: 'إيكو فلو وصحارى',
    brandNameEn: 'EcoFlow & Sahara',
    sellerId: 'seller-7',
    sellerNameAr: 'صحارى للرحلات والرياضة',
    sellerNameEn: 'Sahara Overland & Pro Sports',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 2650,
    originalPrice: 3200,
    discountPercent: 17,
    stock: 14,
    lowStockThreshold: 3,
    status: 'active',
    rating: 4.9,
    reviewCount: 78,
    soldCount: 195,
    images: [
      'https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'stand',
        nameAr: 'الحامل',
        nameEn: 'Stand Option',
        type: 'option',
        options: [
          { id: 'with', labelAr: 'طقم كامل مع الحامل المعدني', labelEn: 'Pair with Ergonomic Stand', value: 'with-stand', inStock: true },
          { id: 'no', labelAr: 'الدامبلز فقط (زوج 32 كجم)', labelEn: 'Dumbbells Pair Only', value: 'no-stand', priceDelta: -450, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'إجمالي الوزن', keyEn: 'Total Weight', valueAr: '٦٤ كجم للزوج (٣٢ كجم لكل يد)', valueEn: '64 kg Total (32 kg per hand)' },
    ],
    warrantyAr: 'ضمان سنتين شامل آلية القفل الفولاذية',
    warrantyEn: '2-Year Steel Mechanism Warranty',
    deliveryEstimateAr: 'توصيل وتركيب خلال ٤٨ ساعة',
    deliveryEstimateEn: '48-hour delivery & assembly',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-08-17',
  },
  {
    id: 'prod-47',
    sku: 'ATH-SPT-003',
    titleAr: 'جهاز المساج والاستشفاء العضلي الاحترافي بالتسخين الحراري وشاشة OLED',
    titleEn: 'Pro Percussion Muscle Recovery Massage Gun with Heated Tip & OLED Screen',
    descriptionAr:
      'جهاز تدليك نقري عميق للرياضيين يصل إلى عمق ١٦ مم في الأنسجة العضلية مع رأس تسخين حراري فوري لتخفيف الشد العضلي بعد التمارين أو مباريات البادل.',
    descriptionEn:
      'Deep-tissue 16mm amplitude percussion massager with heated therapy attachment, quiet brushless motor, and smart pressure sensor.',
    categoryId: 'sports',
    subcategoryAr: 'أجهزة المساج والاستشفاء العضلي',
    subcategoryEn: 'Percussion Recovery Devices',
    brandId: 'brand-garmin',
    brandNameAr: 'جارمن',
    brandNameEn: 'Garmin',
    sellerId: 'seller-7',
    sellerNameAr: 'صحارى للرحلات والرياضة',
    sellerNameEn: 'Sahara Overland & Pro Sports',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 980,
    originalPrice: 1290,
    discountPercent: 24,
    stock: 32,
    lowStockThreshold: 6,
    status: 'active',
    rating: 4.85,
    reviewCount: 95,
    soldCount: 310,
    images: [
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Color',
        type: 'color',
        options: [
          { id: 'blk', labelAr: 'أسود كربوني', labelEn: 'Carbon Black', value: 'black', colorHex: '#18181B', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'عدد الرؤوس', keyEn: 'Attachments', valueAr: '٦ رؤوس علاجية شاملة رأس التسخين والتبريد', valueEn: '6 Pro Tips including Hot/Cold Therapy Head' },
    ],
    warrantyAr: 'ضمان سنتين',
    warrantyEn: '2-Year Warranty',
    deliveryEstimateAr: 'توصيل خلال ٢٤ ساعة',
    deliveryEstimateEn: '24-hour delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: false,
    createdAt: '2026-08-22',
  },
  {
    id: 'prod-48',
    sku: 'ATH-SPT-004',
    titleAr: 'جهاز تجديف مائي ذكي من خشب الجوز الطبيعي مع شاشة تدريب تفاعلية',
    titleEn: 'Handcrafted American Walnut Water Rower with Interactive HD Training Monitor',
    descriptionAr:
      'جهاز تجديف مائي يجمع بين جمال الأثاث الفاخر من خشب الجوز الطبيعي وصوت الماء المريح مع تمرين متكامل يحرق السعرات ويشغل ٨٦٪ من عضلات الجسم.',
    descriptionEn:
      'Sculpted from solid American black walnut, combining natural water resistance physics with an interactive HD coaching console.',
    categoryId: 'sports',
    subcategoryAr: 'أجهزة اللياقة المنزلية الذكية',
    subcategoryEn: 'Smart Home Gym Equipment',
    brandId: 'brand-ecoflow',
    brandNameAr: 'إيكو فلو وصحارى',
    brandNameEn: 'EcoFlow & Sahara',
    sellerId: 'seller-7',
    sellerNameAr: 'صحارى للرحلات والرياضة',
    sellerNameEn: 'Sahara Overland & Pro Sports',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 5400,
    originalPrice: 6300,
    discountPercent: 14,
    stock: 6,
    lowStockThreshold: 2,
    status: 'active',
    rating: 4.95,
    reviewCount: 29,
    soldCount: 64,
    images: [
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'wood',
        nameAr: 'نوع الخشب',
        nameEn: 'Wood Finish',
        type: 'option',
        options: [
          { id: 'wln', labelAr: 'خشب الجوز الأمريكي الداكن', labelEn: 'American Black Walnut', value: 'walnut', inStock: true },
          { id: 'oak', labelAr: 'خشب البلوط الطبيعي', labelEn: 'Natural Oak', value: 'oak', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'التخزين', keyEn: 'Storage', valueAr: 'يقف عمودياً ولا يشغل مساحة أكثر من كرسي صغير', valueEn: 'Stores vertically in compact footprint' },
    ],
    warrantyAr: 'ضمان ٣ سنوات على الهيكل الخشبي ونظام المقاومة',
    warrantyEn: '3-Year Structural & Water Tank Warranty',
    deliveryEstimateAr: 'توصيل وتركيب مجاني خلال ٤٨ ساعة',
    deliveryEstimateEn: 'Free delivery & setup within 48h',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: true,
    createdAt: '2026-09-11',
  },

  // 49-52: AUTOMOTIVE & DESERT GLAMPING (seller-7: صحارى للرحلات والرياضة)
  {
    id: 'prod-49',
    sku: 'ATH-AUT-001',
    titleAr: 'محطة طاقة محمولة إيكو فلو دلتا ٢ ماكس سعة ٢٠٤٨ واط/ساعة للرحلات البرية والمخيمات',
    titleEn: 'EcoFlow DELTA 2 Max Portable Power Station 2048Wh LiFePO4 for Desert Glamping',
    descriptionAr:
      'الرفيق المثالي للكشتات والرحلات البرية الشتوية في المملكة. تشغّل مكائن القهوة، الثلاجات، الإضاءة، وأجهزة الشحن بقدرة ٢٤٠٠ واط وشحن فائق السرعة خلال ٨٠ دقيقة.',
    descriptionEn:
      'Ultimate desert glamping power station with 2048Wh LiFePO4 battery (3,000+ cycles), 2400W AC output for espresso machines & fridges, and 80-minute rapid recharge.',
    categoryId: 'automotive',
    subcategoryAr: 'محطات الطاقة وثلاجات الرحلات',
    subcategoryEn: 'Power Stations & Car Fridges',
    brandId: 'brand-ecoflow',
    brandNameAr: 'إيكو فلو وصحارى',
    brandNameEn: 'EcoFlow & Sahara',
    sellerId: 'seller-7',
    sellerNameAr: 'صحارى للرحلات والرياضة',
    sellerNameEn: 'Sahara Overland & Pro Sports',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 5890,
    originalPrice: 6990,
    discountPercent: 16,
    stock: 15,
    lowStockThreshold: 4,
    status: 'active',
    rating: 4.95,
    reviewCount: 148,
    soldCount: 390,
    images: [
      'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'solar',
        nameAr: 'الألواح الشمسية',
        nameEn: 'Solar Panel Bundle',
        type: 'option',
        options: [
          { id: 'unit', labelAr: 'محطة الطاقة فقط (2048Wh)', labelEn: 'Power Station Only (2048Wh)', value: 'station', inStock: true },
          { id: 'slr', labelAr: 'مع لوح طاقة شمسية قابل للطي 220W', labelEn: 'With 220W Bifacial Solar Panel', value: 'solar', priceDelta: 1450, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'نوع البطارية', keyEn: 'Battery Chemistry', valueAr: 'فوسفات الحديد والليثيوم الآمنة LiFePO4 (عمر ١٠ سنوات)', valueEn: 'Safe LiFePO4 (10-Year Lifespan / 3000 Cycles)' },
      { keyAr: 'المقابس', keyEn: 'Outlets', valueAr: '٤ مقابس ثلاثية سعودية ٢٢٠ فولت + منافذ USB-C 100W', valueEn: '4x UK/KSA 220V AC Outlets + Dual 100W USB-C' },
    ],
    warrantyAr: 'ضمان الوكيل المعتمد ٥ سنوات',
    warrantyEn: '5-Year Official Authorized Warranty',
    deliveryEstimateAr: 'توصيل مجاني خلال ٢٤-٤٨ ساعة',
    deliveryEstimateEn: 'Free 24-48h delivery',
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-05T23:59:59Z',
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    isSeasonal: true,
    createdAt: '2026-08-09',
  },
  {
    id: 'prod-50',
    sku: 'ATH-AUT-002',
    titleAr: 'ثلاجة وفريزر سيارات ورحلات صحارى سعة ٥٥ لتر مزدوجة التبريد مع صانع ثلج وبطارية مدمجة',
    titleEn: 'Sahara Overland 55L Dual-Zone Car Fridge & Freezer with Built-in Ice Maker',
    descriptionAr:
      'ثلاجة رحلات احترافية بكمبرسر ألماني تعمل على ولاعة السيارة ١٢ فولت أو البطارية المدمجة أو الطاقة الشمسية، مع قسمين مستقلين للتبريد والتجميد حتى -٢٠ درجة مئوية.',
    descriptionEn:
      'Heavy-duty 4x4 dual-zone fridge/freezer (-20°C) with integrated rapid ice maker, removable battery pack, and Bluetooth app control.',
    categoryId: 'automotive',
    subcategoryAr: 'محطات الطاقة وثلاجات الرحلات',
    subcategoryEn: 'Power Stations & Car Fridges',
    brandId: 'brand-ecoflow',
    brandNameAr: 'إيكو فلو وصحارى',
    brandNameEn: 'EcoFlow & Sahara',
    sellerId: 'seller-7',
    sellerNameAr: 'صحارى للرحلات والرياضة',
    sellerNameEn: 'Sahara Overland & Pro Sports',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 2890,
    originalPrice: 3450,
    discountPercent: 16,
    stock: 21,
    lowStockThreshold: 5,
    status: 'active',
    rating: 4.9,
    reviewCount: 112,
    soldCount: 280,
    images: [
      'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'capacity',
        nameAr: 'السعة',
        nameEn: 'Capacity',
        type: 'capacity',
        options: [
          { id: '45l', labelAr: '45 لتر', labelEn: '45 Liters', value: '45L', priceDelta: -350, inStock: true },
          { id: '55l', labelAr: '55 لتر + بطارية قابلة للفصل', labelEn: '55L + Detachable Battery', value: '55L', priceDelta: 0, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'نطاق التبريد', keyEn: 'Cooling Range', valueAr: 'من +٢٠° إلى -٢٠° درجة مئوية خلال ١٥ دقيقة', valueEn: '+20°C down to -20°C in 15 mins' },
    ],
    warrantyAr: 'ضمان ٣ سنوات على الكمبرسر',
    warrantyEn: '3-Year Compressor Warranty',
    deliveryEstimateAr: 'توصيل خلال ٢٤-٤٨ ساعة',
    deliveryEstimateEn: '24-48h delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    isSeasonal: true,
    createdAt: '2026-09-03',
  },
  {
    id: 'prod-51',
    sku: 'ATH-AUT-003',
    titleAr: 'كاميرا سيارة داش كام 4K أمامية وخلفية بمكثف حراري مقاوم لشمس الصيف ورادار وقوف ٢٤ ساعة',
    titleEn: '4K Ultra HD Front & Rear Smart Dashcam with Supercapacitor for Extreme Saudi Summer Heat',
    descriptionAr:
      'مصممة خصيصاً لتحمل درجات الحرارة المرتفعة في صيف المملكة حتى ٧٥ درجة مئوية بفضل المكثف الحراري (Supercapacitor) ومستشعر Sony STARVIS 2 الليلي.',
    descriptionEn:
      'Engineered with a heat-resistant supercapacitor rated up to 75°C for Saudi summers, dual Sony STARVIS 2 4K sensors, GPS, and 24/7 parking mode.',
    categoryId: 'automotive',
    subcategoryAr: 'كاميرات السيارات الذكية Dashcam',
    subcategoryEn: '4K Smart Dashcams',
    brandId: 'brand-sony',
    brandNameAr: 'سوني',
    brandNameEn: 'Sony',
    sellerId: 'seller-7',
    sellerNameAr: 'صحارى للرحلات والرياضة',
    sellerNameEn: 'Sahara Overland & Pro Sports',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 940,
    originalPrice: 1190,
    discountPercent: 21,
    stock: 44,
    lowStockThreshold: 8,
    status: 'active',
    rating: 4.85,
    reviewCount: 164,
    soldCount: 540,
    images: [
      'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'bundle',
        nameAr: 'الحزمة',
        nameEn: 'Package',
        type: 'option',
        options: [
          { id: 'std', labelAr: 'أمامية 4K + خلفية + ذاكرة 128GB', labelEn: 'Front 4K + Rear + 128GB Card', value: '128gb', inStock: true },
          { id: 'obd', labelAr: 'مع كيبل الفيوزات للوقوف 24 ساعة + 256GB', labelEn: 'With 24h Parking Cable + 256GB', value: '256gb', priceDelta: 150, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'تحمل الحرارة', keyEn: 'Heat Resistance', valueAr: 'مكثف حراري بدون بطارية ليثيوم (يتحمل حتى ٧٥° مئوية)', valueEn: 'Battery-free Supercapacitor (Up to 75°C)' },
    ],
    warrantyAr: 'ضمان سنتين شامل الاستبدال الفوري',
    warrantyEn: '2-Year Instant Replacement Warranty',
    deliveryEstimateAr: 'توصيل خلال ٢٤ ساعة',
    deliveryEstimateEn: '24-hour delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-08-15',
  },
  {
    id: 'prod-52',
    sku: 'ATH-AUT-004',
    titleAr: 'جهاز اشتراك بطارية ومنفاخ إطارات رقمي مزدوج البستم لسيارات الدفع الرباعي والبر',
    titleEn: 'Heavy-Duty 4x4 Jump Starter (3000A) & Dual-Cylinder Digital Tire Inflator Kit',
    descriptionAr:
      'حقيبة الطوارئ والبر الأساسية لكل سيارة: منفاخ هواء سريع يملأ إطارات الجيب بعد التطعيس في دقيقتين، مع شاحن اشتراك بقوة ٣٠٠٠ أمبير وكشاف LED.',
    descriptionEn:
      'All-in-one desert recovery kit combining a 3000A peak jump starter for V8/Diesel engines and a high-flow compressor for airing up after sand dunes.',
    categoryId: 'automotive',
    subcategoryAr: 'مضخات الهواء ومعدات الطوارئ',
    subcategoryEn: 'Tire Inflators & Jump Starters',
    brandId: 'brand-ecoflow',
    brandNameAr: 'إيكو فلو وصحارى',
    brandNameEn: 'EcoFlow & Sahara',
    sellerId: 'seller-7',
    sellerNameAr: 'صحارى للرحلات والرياضة',
    sellerNameEn: 'Sahara Overland & Pro Sports',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 690,
    originalPrice: 880,
    discountPercent: 22,
    stock: 39,
    lowStockThreshold: 8,
    status: 'active',
    rating: 4.9,
    reviewCount: 127,
    soldCount: 460,
    images: [
      'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'edition',
        nameAr: 'الإصدار',
        nameEn: 'Edition',
        type: 'option',
        options: [
          { id: 'pro', labelAr: 'إصدار الدفع الرباعي 3000A مع حقيبة مدرعة', labelEn: '4x4 Pro 3000A with Hard Case', value: 'pro', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'تدفق الهواء', keyEn: 'Airflow', valueAr: '٧٥ لتر في الدقيقة مع فصل أوتوماتيكي عند الضغط المحدد', valueEn: '75 L/min with Auto-Shutoff PSI' },
    ],
    warrantyAr: 'ضمان سنتين',
    warrantyEn: '2-Year Warranty',
    deliveryEstimateAr: 'توصيل خلال ٢٤ ساعة',
    deliveryEstimateEn: '24-hour delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-08-27',
  },

  // 53-56: GAMING & NEXT-GEN CONSOLES (seller-2: آفاق التقنية المعتمدة)
  {
    id: 'prod-53',
    sku: 'ATH-GAM-001',
    titleAr: 'جهاز سوني بلايستيشن ٥ برو (PS5 Pro) سعة ٢ تيرابايت مع يد تحكم DualSense إضافية',
    titleEn: 'Sony PlayStation 5 Pro (PS5 Pro) 2TB Console Bundle with Extra DualSense Controller',
    descriptionAr:
      'الجيل الأحدث والأقوى من منصة بلايستيشن مع سعة تخزين ٢ تيرابايت SSD فائقة السرعة، تتبع أشعة متقدم، ودقة 4K بمعدل ١٢٠ إطاراً بالثانية.',
    descriptionEn:
      'Next-level console gaming featuring upgraded GPU ray tracing, PlayStation Spectral Super Resolution (PSSR), and 2TB ultra-high-speed SSD.',
    categoryId: 'gaming',
    subcategoryAr: 'أجهزة الكونسول والمنصات المحمولة',
    subcategoryEn: 'Consoles & Handhelds',
    brandId: 'brand-sony',
    brandNameAr: 'سوني',
    brandNameEn: 'Sony',
    sellerId: 'seller-2',
    sellerNameAr: 'آفاق التقنية المعتمدة',
    sellerNameEn: 'Afaq Tech Authorized Store',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 3399,
    originalPrice: 3749,
    discountPercent: 9,
    stock: 23,
    lowStockThreshold: 5,
    status: 'active',
    rating: 4.95,
    reviewCount: 185,
    soldCount: 520,
    images: [
      'https://images.unsplash.com/photo-1606144042614-b2417e99c4e3?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'bundle',
        nameAr: 'الحزمة',
        nameEn: 'Bundle',
        type: 'option',
        options: [
          { id: 'one', labelAr: 'الجهاز مع يد تحكم واحدة', labelEn: 'Console with 1 Controller', value: '1-ctrl', priceDelta: -280, inStock: true },
          { id: 'two', labelAr: 'الجهاز مع يدين تحكم DualSense', labelEn: 'Console with 2 Controllers', value: '2-ctrl', priceDelta: 0, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'السعة التخزينية', keyEn: 'SSD Storage', valueAr: '2 TB NVMe SSD مدمجة', valueEn: '2 TB Custom NVMe SSD' },
    ],
    warrantyAr: 'ضمان الوكيل الرسمي سوني السعودية سنتين',
    warrantyEn: '2-Year Official Sony KSA Warranty',
    deliveryEstimateAr: 'توصيل فوري في نفس اليوم بالرياض',
    deliveryEstimateEn: 'Same-day delivery in Riyadh',
    isFlashDeal: true,
    flashDealEndsAt: '2026-10-04T23:59:59Z',
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    createdAt: '2026-09-10',
  },
  {
    id: 'prod-54',
    sku: 'ATH-GAM-002',
    titleAr: 'نظارة الواقع الافتراضي والمختلط أبل فيجن برو سعة ٥١٢ جيجابايت مع حقيبة السفر الرسمية',
    titleEn: 'Apple Vision Pro Spatial Computer 512GB with Official Travel Case',
    descriptionAr:
      'حاسوب مكاني ثوري يدمج المحتوى الرقمي بسلاسة مع عالمك الحقيقي، بشاشات micro-OLED تفوق دقة 4K لكل عين وتحكم بديهي بحركة العين واليدين.',
    descriptionEn:
      'Breakthrough spatial computer featuring ultra-high-resolution micro-OLED displays (23 million pixels) and dual-chip R1 + M2 performance.',
    categoryId: 'gaming',
    subcategoryAr: 'نظارات الواقع الافتراضي والمحاكاة',
    subcategoryEn: 'VR Headsets & Racing Sims',
    brandId: 'brand-apple',
    brandNameAr: 'آبل',
    brandNameEn: 'Apple',
    sellerId: 'seller-2',
    sellerNameAr: 'آفاق التقنية المعتمدة',
    sellerNameEn: 'Afaq Tech Authorized Store',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 15499,
    originalPrice: 16999,
    discountPercent: 9,
    stock: 1,
    lowStockThreshold: 3,
    status: 'active',
    rating: 4.9,
    reviewCount: 27,
    soldCount: 48,
    images: [
      'https://images.unsplash.com/photo-1622979135225-d2ba269cf1ac?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'storage',
        nameAr: 'السعة',
        nameEn: 'Storage',
        type: 'capacity',
        options: [
          { id: '512', labelAr: '512 جيجابايت + حقيبة السفر', labelEn: '512GB + Travel Case', value: '512GB', inStock: true },
          { id: '1tb', labelAr: '1 تيرابايت + حقيبة السفر', labelEn: '1TB + Travel Case', value: '1TB', priceDelta: 900, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'الشاشات', keyEn: 'Displays', valueAr: '٢٣ مليون بكسل Micro-OLED مع صوت مكاني', valueEn: '23M-pixel Micro-OLED + Spatial Audio' },
    ],
    warrantyAr: 'ضمان سنتين آفاق التقنية',
    warrantyEn: '2-Year Warranty',
    deliveryEstimateAr: 'توصيل VIP خلال ٢٤ ساعة',
    deliveryEstimateEn: '24-hour VIP delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    isNewArrival: true,
    createdAt: '2026-09-07',
  },
  {
    id: 'prod-55',
    sku: 'ATH-GAM-003',
    titleAr: 'يد تحكم بلايستيشن ٥ الاحترافية DualSense Edge القابلة للتخصيص مع حافظة صلبة',
    titleEn: 'Sony PlayStation 5 DualSense Edge Wireless Pro Controller',
    descriptionAr:
      'صُممت لتحقيق التفوق التنافسي مع أزرار خلفية قابلة للبرمجة، عصي تحكم قابلة للاستبدال، وتعديل مسافة ضغط الأزرار الخلفية.',
    descriptionEn:
      'Built for high performance and personalization with remappable back buttons, replaceable stick modules, and adjustable trigger lengths.',
    categoryId: 'gaming',
    subcategoryAr: 'إكسسوارات وكراسي الألعاب',
    subcategoryEn: 'Pro Controllers & Chairs',
    brandId: 'brand-sony',
    brandNameAr: 'سوني',
    brandNameEn: 'Sony',
    sellerId: 'seller-2',
    sellerNameAr: 'آفاق التقنية المعتمدة',
    sellerNameEn: 'Afaq Tech Authorized Store',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 899,
    originalPrice: 1049,
    discountPercent: 14,
    stock: 30,
    lowStockThreshold: 6,
    status: 'active',
    rating: 4.85,
    reviewCount: 74,
    soldCount: 210,
    images: [
      'https://images.unsplash.com/photo-1592840496694-26d035b52b48?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Color',
        type: 'color',
        options: [
          { id: 'wht', labelAr: 'أبيض وأسود كلاسيك', labelEn: 'Classic White & Black', value: 'white', colorHex: '#F4F4F5', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'الملحقات', keyEn: 'Included', valueAr: 'حافظة صلبة + كيبل مضفر بطول ٢.٨ متر + ٤ أزرار خلفية', valueEn: 'Hard Case + Braided USB-C + 4 Back Paddles' },
    ],
    warrantyAr: 'ضمان سنتين الوكيل الرسمي',
    warrantyEn: '2-Year Official Warranty',
    deliveryEstimateAr: 'توصيل خلال ٢٤ ساعة',
    deliveryEstimateEn: '24-hour delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-08-19',
  },
  {
    id: 'prod-56',
    sku: 'ATH-GAM-004',
    titleAr: 'كرسي ألعاب ومكتب تنفيذي إرجونوميك من جلد النابا الطبيعي ودعم القطنية رباعي الاتجاهات',
    titleEn: 'Executive Ergonomic Gaming & Office Chair in Nappa Leather with 4D Lumbar Support',
    descriptionAr:
      'كرسي احترافي يجمع بين راحة المقاعد الرياضية الفاخرة ودعم العمود الفقري الطبي لساعات العمل واللعب الطويلة، مكسو بجلد النابا الفاخر المسامي.',
    descriptionEn:
      'Crafted in breathable Nappa leather with integrated 4-way adaptive lumbar support, magnetic memory-foam head pillow, and full-metal 4D armrests.',
    categoryId: 'gaming',
    subcategoryAr: 'إكسسوارات وكراسي الألعاب',
    subcategoryEn: 'Pro Controllers & Chairs',
    brandId: 'brand-ecoflow',
    brandNameAr: 'إيكو فلو وصحارى',
    brandNameEn: 'EcoFlow & Sahara',
    sellerId: 'seller-2',
    sellerNameAr: 'آفاق التقنية المعتمدة',
    sellerNameEn: 'Afaq Tech Authorized Store',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 2150,
    originalPrice: 2650,
    discountPercent: 19,
    stock: 13,
    lowStockThreshold: 3,
    status: 'active',
    rating: 4.9,
    reviewCount: 62,
    soldCount: 145,
    images: [
      'https://images.unsplash.com/photo-1580480055273-228ff5388ef8?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Color',
        type: 'color',
        options: [
          { id: 'blk', labelAr: 'أسود أوبسيديان وتطريز ذهبي', labelEn: 'Obsidian Black & Gold Stitch', value: 'black', colorHex: '#18181B', inStock: true },
          { id: 'tan', labelAr: 'جملي هافان كلاسيك', labelEn: 'Classic Havana Tan', value: 'tan', colorHex: '#9A6B4C', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'التحمل', keyEn: 'Max Load', valueAr: 'حتى ١٥٠ كجم بقاعدة ألمنيوم مقواة', valueEn: 'Up to 150 kg Reinforced Aluminum Base' },
    ],
    warrantyAr: 'ضمان ٥ سنوات على الهيكل والهيدروليك',
    warrantyEn: '5-Year Frame & Hydraulic Warranty',
    deliveryEstimateAr: 'توصيل وتركيب خلال ٤٨ ساعة',
    deliveryEstimateEn: '48h delivery & assembly',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: true,
    createdAt: '2026-09-09',
  },

  // 57-60: BOOKS & SAUDI CULTURE (seller-4: أتيليه نجد للأزياء والعبايات)
  {
    id: 'prod-57',
    sku: 'ATH-BOK-001',
    titleAr: 'مجلد العُلا والدرعية الفاخر لطاولات الضيافة (إصدار الحرير المحدود من دار أسولين)',
    titleEn: 'AlUla & Diriyah Silk Hardcover Coffee Table Collector Volume - Assouline Luxury Edition',
    descriptionAr:
      'مجلد فني ضخم مغلف بالحرير المنسوج يدوياً، يوثق روائع العمارة النجدية في الدرعية وتشكيلات العُلا الصخرية بعدسة أشهر المصورين العالميين، مثالي لتزيين المجالس الفاخرة.',
    descriptionEn:
      'Oversized silk-bound collector coffee table book celebrating the architectural heritage of Diriyah and the monumental landscapes of AlUla.',
    categoryId: 'books',
    subcategoryAr: 'مجلدات الفنون والتراث السعودي',
    subcategoryEn: 'Saudi Heritage Coffee Table Books',
    brandId: 'brand-assouline',
    brandNameAr: 'دار أسولين للنشر',
    brandNameEn: 'Assouline Editions',
    sellerId: 'seller-4',
    sellerNameAr: 'أتيليه نجد للأزياء والعبايات',
    sellerNameEn: 'Najd Couture & Royal Attire',
    sellerRating: 4.85,
    sellerVerified: true,
    price: 980,
    originalPrice: 1200,
    discountPercent: 18,
    stock: 19,
    lowStockThreshold: 4,
    status: 'active',
    rating: 4.95,
    reviewCount: 68,
    soldCount: 190,
    images: [
      'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'edition',
        nameAr: 'الإصدار',
        nameEn: 'Edition',
        type: 'option',
        options: [
          { id: 'clsc', labelAr: 'مجلد الغلاف الحريري الفاخر', labelEn: 'Silk Hardcover Edition', value: 'silk', inStock: true },
          { id: 'ult', labelAr: 'إصدار Ultimate داخل صندوق Clamshell مع حامل أكريليك', labelEn: 'Ultimate Clamshell + Acrylic Stand', value: 'ultimate', priceDelta: 1400, inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'الأبعاد والصفحات', keyEn: 'Dimensions', valueAr: '٣٣ × ٢٥ سم • ٣١٢ صفحة ورق فني مصقول', valueEn: '33 x 25 cm • 312 Art-Grade Pages' },
    ],
    warrantyAr: 'تغليف إهداء فاخر مجاني',
    warrantyEn: 'Complimentary Luxury Gift Wrapping',
    deliveryEstimateAr: 'توصيل خلال ٢٤ ساعة في الرياض وجدة',
    deliveryEstimateEn: '24h delivery in Riyadh & Jeddah',
    isFlashDeal: false,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    isSeasonal: true,
    createdAt: '2026-08-15',
  },
  {
    id: 'prod-58',
    sku: 'ATH-BOK-002',
    titleAr: 'مجلد الخيل العربية الأصيلة: إرث الفروسية في الجزيرة العربية (نسخة مذهّبة)',
    titleEn: 'Purebred Arabian Horses: Equestrian Heritage of Arabia (Gold-Leaf Collector Tome)',
    descriptionAr:
      'موسوعة بصرية وتاريخية نادرة تستعرض سلالات الخيل العربية الأصيلة ومرابطها التاريخية في المملكة، بحواف صفحات مذهّبة وغلاف جلدي فاخر.',
    descriptionEn:
      'Museum-grade collector volume chronicling the noble bloodlines of purebred Arabian horses in Saudi Arabia with gilded page edges.',
    categoryId: 'books',
    subcategoryAr: 'مجلدات الفنون والتراث السعودي',
    subcategoryEn: 'Saudi Heritage Coffee Table Books',
    brandId: 'brand-assouline',
    brandNameAr: 'دار أسولين للنشر',
    brandNameEn: 'Assouline Editions',
    sellerId: 'seller-4',
    sellerNameAr: 'أتيليه نجد للأزياء والعبايات',
    sellerNameEn: 'Najd Couture & Royal Attire',
    sellerRating: 4.85,
    sellerVerified: true,
    price: 1150,
    originalPrice: 1400,
    discountPercent: 18,
    stock: 14,
    lowStockThreshold: 3,
    status: 'active',
    rating: 4.9,
    reviewCount: 41,
    soldCount: 110,
    images: [
      'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'lang',
        nameAr: 'اللغة',
        nameEn: 'Language Edition',
        type: 'option',
        options: [
          { id: 'bi', labelAr: 'طبعة ثنائية اللغة (عربي / إنجليزي)', labelEn: 'Bilingual Edition (AR / EN)', value: 'bilingual', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'التجليد', keyEn: 'Binding', valueAr: 'جلد طبيعي مطعم بالذهب عيار ٢٢', valueEn: 'Genuine Leather with Gold Foil Stamping' },
    ],
    warrantyAr: 'نسخة مرقمة أصلية',
    warrantyEn: 'Numbered Collector Edition',
    deliveryEstimateAr: 'توصيل خلال ٢٤-٤٨ ساعة',
    deliveryEstimateEn: '24-48h delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: true,
    createdAt: '2026-09-05',
  },
  {
    id: 'prod-59',
    sku: 'ATH-BOK-003',
    titleAr: 'مجموعة مكتبة القائد التنفيذي: ٥ مجلدات في الاستراتيجية، الاستثمار، والحوكمة الحديثة',
    titleEn: 'The Executive Leader Library: 5 Hardcover Volumes on Strategy, Venture Capital & Governance',
    descriptionAr:
      'تشكيلة منتقاة بعناية للمكاتب التنفيذية تضم أهم ٥ مؤلفات عالمية وعربية في بناء الشركات الكبرى، التحول المؤسسي، وإدارة الثروات في طبعات فاخرة.',
    descriptionEn:
      'Curated 5-volume hardcover boxset covering corporate strategy, institutional transformation, and sovereign investment leadership.',
    categoryId: 'books',
    subcategoryAr: 'كتب الإدارة والاقتصاد والريادة',
    subcategoryEn: 'Leadership & Strategy Books',
    brandId: 'brand-assouline',
    brandNameAr: 'دار أسولين للنشر',
    brandNameEn: 'Assouline Editions',
    sellerId: 'seller-4',
    sellerNameAr: 'أتيليه نجد للأزياء والعبايات',
    sellerNameEn: 'Najd Couture & Royal Attire',
    sellerRating: 4.85,
    sellerVerified: true,
    price: 590,
    originalPrice: 740,
    discountPercent: 20,
    stock: 27,
    lowStockThreshold: 5,
    status: 'active',
    rating: 4.85,
    reviewCount: 53,
    soldCount: 175,
    images: [
      'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'lang',
        nameAr: 'اللغة',
        nameEn: 'Language',
        type: 'option',
        options: [
          { id: 'ar', labelAr: 'الطبعة العربية المترجمة الفاخرة', labelEn: 'Arabic Hardcover Edition', value: 'ar', inStock: true },
          { id: 'en', labelAr: 'الطبعة الإنجليزية الأصلية', labelEn: 'Original English Hardcover', value: 'en', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'عدد الكتب', keyEn: 'Volumes', valueAr: '٥ مجلدات بغلاف مقوى داخل حافظة مكتبية', valueEn: '5 Hardcover Volumes in Slipcase' },
    ],
    warrantyAr: 'طبعات أصلية ١٠٠٪',
    warrantyEn: '100% Authentic Publisher Editions',
    deliveryEstimateAr: 'توصيل خلال ٢٤ ساعة',
    deliveryEstimateEn: '24-hour delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: false,
    isBestSeller: false,
    isNewArrival: false,
    createdAt: '2026-08-24',
  },
  {
    id: 'prod-60',
    sku: 'ATH-BOK-004',
    titleAr: 'مجلد البحر الأحمر ونيوم: مستقبل السياحة المتجددة والعمارة المستدامة',
    titleEn: 'The Red Sea & NEOM: Future of Regenerative Luxury & Architectural Marvels',
    descriptionAr:
      'إصدار بصري ساحر يستعرض الجزر البكر في البحر الأحمر والمشاريع المعمارية المستقبلية في المملكة بصور جوية عالية الدقة.',
    descriptionEn:
      'Spectacular visual monograph documenting the pristine coral archipelagos of the Red Sea and visionary sustainable architecture.',
    categoryId: 'books',
    subcategoryAr: 'مجلدات الفنون والتراث السعودي',
    subcategoryEn: 'Saudi Heritage Coffee Table Books',
    brandId: 'brand-assouline',
    brandNameAr: 'دار أسولين للنشر',
    brandNameEn: 'Assouline Editions',
    sellerId: 'seller-4',
    sellerNameAr: 'أتيليه نجد للأزياء والعبايات',
    sellerNameEn: 'Najd Couture & Royal Attire',
    sellerRating: 4.85,
    sellerVerified: true,
    price: 920,
    originalPrice: 1100,
    discountPercent: 16,
    stock: 20,
    lowStockThreshold: 4,
    status: 'active',
    rating: 4.9,
    reviewCount: 34,
    soldCount: 95,
    images: [
      'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'cover',
        nameAr: 'الغلاف',
        nameEn: 'Cover',
        type: 'option',
        options: [
          { id: 'lin', labelAr: 'كتان فيروزي فاخر', labelEn: 'Turquoise Linen Hardcover', value: 'linen', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'عدد الصفحات', keyEn: 'Pages', valueAr: '٢٨٠ صفحة ملونة بالكامل', valueEn: '280 Full-Color Plates' },
    ],
    warrantyAr: 'تغليف هدايا فاخر',
    warrantyEn: 'Luxury Gift Packaging',
    deliveryEstimateAr: 'توصيل خلال ٢٤-٤٨ ساعة',
    deliveryEstimateEn: '24-48h delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: true,
    isBestSeller: false,
    isNewArrival: true,
    createdAt: '2026-09-15',
  },

  // 61-64: SMART HEALTH & WELLNESS (seller-2: آفاق التقنية المعتمدة)
  {
    id: 'prod-61',
    sku: 'ATH-HLT-001',
    titleAr: 'خاتم تتبع النوم والمؤشرات الحيوية الذكي من التيتانيوم الخالص (بدون اشتراك شهري) - ذهبي مصقول',
    titleEn: 'Smart Biometric Sleep & Recovery Titanium Ring (Subscription-Free) - Brushed Gold',
    descriptionAr:
      'خاتم ذكي فائق الخفة من التيتانيوم الطبي يتابع جودة النوم العميق، معدل ضربات القلب HRV، تشبع الأكسجين، ومستويات الإجهاد والتعافي ببطارية تدوم ٧ أيام.',
    descriptionEn:
      'Featherlight aerospace titanium smart ring tracking sleep stages, HRV recovery, blood oxygen, and skin temperature with 7-day battery life.',
    categoryId: 'health',
    subcategoryAr: 'أجهزة قياس المؤشرات الحيوية والنوم',
    subcategoryEn: 'Biometric & Sleep Trackers',
    brandId: 'brand-garmin',
    brandNameAr: 'جارمن',
    brandNameEn: 'Garmin',
    sellerId: 'seller-2',
    sellerNameAr: 'آفاق التقنية المعتمدة',
    sellerNameEn: 'Afaq Tech Authorized Store',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 1599,
    originalPrice: 1899,
    discountPercent: 16,
    stock: 27,
    lowStockThreshold: 5,
    status: 'active',
    rating: 4.9,
    reviewCount: 108,
    soldCount: 315,
    images: [
      'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Finish',
        type: 'color',
        options: [
          { id: 'gld', labelAr: 'ذهبي مصقول', labelEn: 'Brushed Gold', value: 'gold', colorHex: '#C59B27', inStock: true },
          { id: 'blk', labelAr: 'تيتانيوم أسود مطفي', labelEn: 'Stealth Matte Black', value: 'black', colorHex: '#1F1F1F', inStock: true },
        ],
      },
      {
        id: 'size',
        nameAr: 'المقاس',
        nameEn: 'Ring Size',
        type: 'size',
        options: [
          { id: 's8', labelAr: 'مقاس 8', labelEn: 'Size 8', value: '8', inStock: true },
          { id: 's9', labelAr: 'مقاس 9', labelEn: 'Size 9', value: '9', inStock: true },
          { id: 's10', labelAr: 'مقاس 10', labelEn: 'Size 10', value: '10', inStock: true },
          { id: 's11', labelAr: 'مقاس 11', labelEn: 'Size 11', value: '11', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'مقاومة الماء', keyEn: 'Waterproof', valueAr: 'مقاوم للماء حتى ١٠٠ متر ومناسب للوضوء والسباحة', valueEn: '100m Water Resistant' },
    ],
    warrantyAr: 'ضمان سنتين واستبدال المقاس مجاناً',
    warrantyEn: '2-Year Warranty & Free Size Exchange',
    deliveryEstimateAr: 'توصيل خلال ٢٤ ساعة',
    deliveryEstimateEn: '24-hour delivery',
    isFlashDeal: false,
    isFeatured: true,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: true,
    createdAt: '2026-09-08',
  },
  {
    id: 'prod-62',
    sku: 'ATH-HLT-002',
    titleAr: 'ميزان تحليل الجسم الطبي الذكي بمقبض تخطيط القلب ECG وقياس الكتلة العضلية والدهون',
    titleEn: 'Clinical Segmental Body Composition Smart Scale with Handle & 6-Lead ECG',
    descriptionAr:
      'محطة فحص صحية منزلية تقيس نسبة الدهون والعضلات في كل ذراع وساق بدقة العيادات، مع تخطيط قلب ECG وعمر الأوعية الدموية وربط مباشر بـ Apple Health.',
    descriptionEn:
      'Clinical-grade segmental body composition analyzer with retractable handle, 6-lead ECG, vascular age assessment, and Wi-Fi sync.',
    categoryId: 'health',
    subcategoryAr: 'أجهزة العناية الصحية المنزلية',
    subcategoryEn: 'Home Medical & Wellness Monitors',
    brandId: 'brand-garmin',
    brandNameAr: 'جارمن',
    brandNameEn: 'Garmin',
    sellerId: 'seller-2',
    sellerNameAr: 'آفاق التقنية المعتمدة',
    sellerNameEn: 'Afaq Tech Authorized Store',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 1490,
    originalPrice: 1790,
    discountPercent: 17,
    stock: 16,
    lowStockThreshold: 4,
    status: 'active',
    rating: 4.85,
    reviewCount: 64,
    soldCount: 180,
    images: [
      'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Color',
        type: 'color',
        options: [
          { id: 'blk', labelAr: 'زجاج أسود مقوى', labelEn: 'Tempered Black Glass', value: 'black', colorHex: '#18181B', inStock: true },
          { id: 'wht', labelAr: 'زجاج أبيض ناصع', labelEn: 'Pure White Glass', value: 'white', colorHex: '#FAF8F5', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'عدد المستخدمين', keyEn: 'User Profiles', valueAr: 'يتعرف تلقائياً على ٨ أفراد من العائلة', valueEn: 'Auto-recognizes up to 8 family members' },
    ],
    warrantyAr: 'ضمان سنتين ومرخص من هيئة الغذاء والدواء',
    warrantyEn: '2-Year Warranty & SFDA Approved',
    deliveryEstimateAr: 'توصيل خلال ٢٤ ساعة',
    deliveryEstimateEn: '24-hour delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-08-19',
  },
  {
    id: 'prod-63',
    sku: 'ATH-HLT-003',
    titleAr: 'جهاز تنقية وتعقيم الهواء دايسون بيورفاير فورمالديهايد مع فلتر HEPA H13 محكم',
    titleEn: 'Dyson Purifier Cool Formaldehyde Air Purifier with Sealed HEPA H13 Filter - White/Gold',
    descriptionAr:
      'ينقي هواء الغرفة بالكامل ويلتقط ٩٩.٩٧٪ من الغبار الدقيق ومسببات الحساسية والغازات مع تدمير الفورمالديهايد باستمرار، مثالي لأجواء الغبار ومواسم الحساسية.',
    descriptionEn:
      'Detects and destroys formaldehyde continuously while capturing 99.97% of ultrafine dust and allergens in a fully sealed HEPA H13 system.',
    categoryId: 'health',
    subcategoryAr: 'أجهزة العناية الصحية المنزلية',
    subcategoryEn: 'Home Medical & Wellness Monitors',
    brandId: 'brand-dyson',
    brandNameAr: 'دايسون',
    brandNameEn: 'Dyson',
    sellerId: 'seller-2',
    sellerNameAr: 'آفاق التقنية المعتمدة',
    sellerNameEn: 'Afaq Tech Authorized Store',
    sellerRating: 4.8,
    sellerVerified: true,
    price: 2999,
    originalPrice: 3499,
    discountPercent: 14,
    stock: 13,
    lowStockThreshold: 3,
    status: 'active',
    rating: 4.9,
    reviewCount: 89,
    soldCount: 240,
    images: [
      'https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Color',
        type: 'color',
        options: [
          { id: 'wht', labelAr: 'أبيض وذهبي ملكي', labelEn: 'White & Satin Gold', value: 'gold', colorHex: '#C59B27', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'الفلتر', keyEn: 'Filtration', valueAr: 'HEPA H13 + كربون نشط + فلتر تحفيزي لا يحتاج استبدال', valueEn: 'HEPA H13 + Activated Carbon + Catalytic Filter' },
    ],
    warrantyAr: 'ضمان سنتين دايسون السعودية',
    warrantyEn: '2-Year Official Dyson KSA Warranty',
    deliveryEstimateAr: 'توصيل مجاني خلال ٢٤-٤٨ ساعة',
    deliveryEstimateEn: 'Free 24-48h delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: true,
    isBestSeller: true,
    isNewArrival: false,
    createdAt: '2026-08-25',
  },
  {
    id: 'prod-64',
    sku: 'ATH-HLT-004',
    titleAr: 'وسادة النوم الفندقية الفاخرة بالحرير الطبيعي ١٠٠٪ (٢٢ مومي) مع قناع عين مبطن',
    titleEn: '100% Pure Mulberry Silk (22-Momme) Luxury Hotel Pillowcase & Sleep Mask Gift Set',
    descriptionAr:
      'مصنوعة من أنقى خيوط حرير التوت الطبيعي بدرجة 6A وكثافة ٢٢ مومي، تحافظ على ترطيب البشرة وتمنع هيشان وتكسر الشعر أثناء النوم.',
    descriptionEn:
      'Woven from Grade-6A 22-momme pure Mulberry silk to preserve skin hydration, prevent sleep creases, and protect hair shine.',
    categoryId: 'health',
    subcategoryAr: 'أجهزة قياس المؤشرات الحيوية والنوم',
    subcategoryEn: 'Biometric & Sleep Trackers',
    brandId: 'brand-najd',
    brandNameAr: 'أتيليه نجد الملكي',
    brandNameEn: 'Najd Royal Atelier',
    sellerId: 'seller-6',
    sellerNameAr: 'واحة الجمال والعناية',
    sellerNameEn: 'Beauty Oasis Luxury Care',
    sellerRating: 4.75,
    sellerVerified: true,
    price: 440,
    originalPrice: 580,
    discountPercent: 24,
    stock: 45,
    lowStockThreshold: 8,
    status: 'active',
    rating: 4.95,
    reviewCount: 112,
    soldCount: 410,
    images: [
      'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=1000&q=85',
    ],
    variants: [
      {
        id: 'color',
        nameAr: 'اللون',
        nameEn: 'Color',
        type: 'color',
        options: [
          { id: 'chm', labelAr: 'بيج شامبين لؤلؤي', labelEn: 'Pearl Champagne', value: 'champagne', colorHex: '#E8DFD1', inStock: true },
          { id: 'emr', labelAr: 'أخضر زمردي ملكي', labelEn: 'Royal Emerald', value: 'emerald', colorHex: '#0B4F3F', inStock: true },
        ],
      },
    ],
    specifications: [
      { keyAr: 'شهادة الجودة', keyEn: 'Certification', valueAr: 'معتمد OEKO-TEX خالٍ من المواد الكيميائية', valueEn: 'OEKO-TEX Standard 100 Certified' },
    ],
    warrantyAr: 'ضمان الحرير الطبيعي ١٠٠٪',
    warrantyEn: '100% Pure Mulberry Silk Guarantee',
    deliveryEstimateAr: 'توصيل خلال ٢٤ ساعة',
    deliveryEstimateEn: '24-hour delivery',
    isFlashDeal: false,
    isFeatured: false,
    isTrending: false,
    isBestSeller: true,
    isNewArrival: true,
    createdAt: '2026-09-12',
  },
];

export const ALL_INITIAL_PRODUCTS: Product[] = [];
